/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * An activity contact.
 */
export type ActivityContact = {
  /**
   * The first name of the attendee.
   */
  firstName?: string | undefined;
  /**
   * The last name of the attendee.
   */
  lastName?: string | undefined;
  /**
   * The email address of the attendee.
   */
  email?: string | undefined;
};

/** @internal */
export const ActivityContact$inboundSchema: z.ZodType<
  ActivityContact,
  z.ZodTypeDef,
  unknown
> = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
});

export function activityContactFromJSON(
  jsonString: string,
): SafeParseResult<ActivityContact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityContact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityContact' from JSON`,
  );
}
