/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Sponsorship level for an activity exhibitor.
 */
export type ActivityExhibitorSponsorshipLevel = {
  /**
   * The unique identifier of the sponsorship level.
   */
  id?: string | undefined;
  /**
   * The name of the sponsorship level.
   */
  name?: string | undefined;
};

/** @internal */
export const ActivityExhibitorSponsorshipLevel$inboundSchema: z.ZodType<
  ActivityExhibitorSponsorshipLevel,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});

export function activityExhibitorSponsorshipLevelFromJSON(
  jsonString: string,
): SafeParseResult<ActivityExhibitorSponsorshipLevel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityExhibitorSponsorshipLevel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityExhibitorSponsorshipLevel' from JSON`,
  );
}
