/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Address details.
 */
export type AddressJson7 = {
  /**
   * Address line 1.
   */
  address1?: string | undefined;
  /**
   * Address line 2.
   */
  address2?: string | undefined;
  /**
   * City name.
   */
  city?: string | undefined;
  /**
   * Region name.
   */
  region?: string | undefined;
  /**
   * Region code.
   */
  regionCode?: string | undefined;
  /**
   * Postal code.
   */
  postalCode?: string | undefined;
  /**
   * Country name.
   */
  country?: string | undefined;
  /**
   * ISO 3166 alpha-2 country code.
   */
  countryCode?: string | undefined;
};

/** @internal */
export const AddressJson7$inboundSchema: z.ZodType<
  AddressJson7,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string().optional(),
  address2: z.string().optional(),
  city: z.string().optional(),
  region: z.string().optional(),
  regionCode: z.string().optional(),
  postalCode: z.string().optional(),
  country: z.string().optional(),
  countryCode: z.string().optional(),
});

export function addressJson7FromJSON(
  jsonString: string,
): SafeParseResult<AddressJson7, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddressJson7$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressJson7' from JSON`,
  );
}
