/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents the budget item where the allocation was made.
 */
export type AllocationBudgetItemId = {
  /**
   * Identifier of a particular budget item.
   */
  id?: string | undefined;
};

/** @internal */
export const AllocationBudgetItemId$inboundSchema: z.ZodType<
  AllocationBudgetItemId,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
});

export function allocationBudgetItemIdFromJSON(
  jsonString: string,
): SafeParseResult<AllocationBudgetItemId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AllocationBudgetItemId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AllocationBudgetItemId' from JSON`,
  );
}
