/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A message attachment.
 */
export type AttachmentJson1 = {
  /**
   * A link to the attachment allowing it to be downloaded
   */
  link: string;
};

/** @internal */
export const AttachmentJson1$inboundSchema: z.ZodType<
  AttachmentJson1,
  z.ZodTypeDef,
  unknown
> = z.object({
  link: z.string(),
});

export function attachmentJson1FromJSON(
  jsonString: string,
): SafeParseResult<AttachmentJson1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AttachmentJson1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AttachmentJson1' from JSON`,
  );
}
