/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { Uuid, Uuid$Outbound, Uuid$outboundSchema } from "./uuid.js";
import {
  WebcastLink,
  WebcastLink$Outbound,
  WebcastLink$outboundSchema,
} from "./webcastlink.js";

/**
 * An attendee link.
 */
export type AttendeeLink = {
  /**
   * The reference to the related entity. Contains only the ID of the related entity.
   */
  webcast: Uuid;
  /**
   * The reference to the related entity. Contains only the ID of the related entity.
   */
  event?: Uuid | undefined;
  /**
   * The reference to the related entity. Contains only the ID of the related entity.
   */
  session?: Uuid | undefined;
  /**
   * The reference to the related entity. Contains only the ID of the related entity.
   */
  attendee: Uuid;
  /**
   * Source Id of the webcast provider
   */
  sourceId?: string | undefined;
  /**
   * Link details for a webcast.
   */
  join?: WebcastLink | undefined;
};

/** @internal */
export type AttendeeLink$Outbound = {
  webcast: Uuid$Outbound;
  event?: Uuid$Outbound | undefined;
  session?: Uuid$Outbound | undefined;
  attendee: Uuid$Outbound;
  sourceId?: string | undefined;
  join?: WebcastLink$Outbound | undefined;
};

/** @internal */
export const AttendeeLink$outboundSchema: z.ZodType<
  AttendeeLink$Outbound,
  z.ZodTypeDef,
  AttendeeLink
> = z.object({
  webcast: Uuid$outboundSchema,
  event: Uuid$outboundSchema.optional(),
  session: Uuid$outboundSchema.optional(),
  attendee: Uuid$outboundSchema,
  sourceId: z.string().optional(),
  join: WebcastLink$outboundSchema.optional(),
});

export function attendeeLinkToJSON(attendeeLink: AttendeeLink): string {
  return JSON.stringify(AttendeeLink$outboundSchema.parse(attendeeLink));
}
