/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Creation type of the audience segment.
 */
export const AudienceSegmentCreationType = {
  Manual: "MANUAL",
} as const;
/**
 * Creation type of the audience segment.
 */
export type AudienceSegmentCreationType = ClosedEnum<
  typeof AudienceSegmentCreationType
>;

/** @internal */
export const AudienceSegmentCreationType$inboundSchema: z.ZodNativeEnum<
  typeof AudienceSegmentCreationType
> = z.nativeEnum(AudienceSegmentCreationType);
/** @internal */
export const AudienceSegmentCreationType$outboundSchema: z.ZodNativeEnum<
  typeof AudienceSegmentCreationType
> = AudienceSegmentCreationType$inboundSchema;
