/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  BadgePrinterPoolReferenceJson,
  BadgePrinterPoolReferenceJson$Outbound,
  BadgePrinterPoolReferenceJson$outboundSchema,
} from "./badgeprinterpoolreferencejson.js";
import {
  BadgePrintJobStatusJson,
  BadgePrintJobStatusJson$outboundSchema,
} from "./badgeprintjobstatusjson.js";

/**
 * The Badge Print Job that was created.
 */
export type BadgePrintJobCreatedInput = {
  /**
   * This is used to indicate the status of the badge print job.
   */
  status?: BadgePrintJobStatusJson | undefined;
  /**
   * Reference to a Badge Print Pool.
   */
  pool: BadgePrinterPoolReferenceJson;
  /**
   * A unique id of the attendee for badge printing, which could be confirmation number or secured badge id depending on whether secured badge id is enabled
   */
  badgeId: string;
};

/** @internal */
export type BadgePrintJobCreatedInput$Outbound = {
  status?: string | undefined;
  pool: BadgePrinterPoolReferenceJson$Outbound;
  badgeId: string;
};

/** @internal */
export const BadgePrintJobCreatedInput$outboundSchema: z.ZodType<
  BadgePrintJobCreatedInput$Outbound,
  z.ZodTypeDef,
  BadgePrintJobCreatedInput
> = z.object({
  status: BadgePrintJobStatusJson$outboundSchema.optional(),
  pool: BadgePrinterPoolReferenceJson$outboundSchema,
  badgeId: z.string(),
});

export function badgePrintJobCreatedInputToJSON(
  badgePrintJobCreatedInput: BadgePrintJobCreatedInput,
): string {
  return JSON.stringify(
    BadgePrintJobCreatedInput$outboundSchema.parse(badgePrintJobCreatedInput),
  );
}
