/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  Attendee12,
  Attendee12$Outbound,
  Attendee12$outboundSchema,
} from "./attendee12.js";
import { Event3, Event3$Outbound, Event3$outboundSchema } from "./event3.js";
import {
  Exhibitor,
  Exhibitor$Outbound,
  Exhibitor$outboundSchema,
} from "./exhibitor.js";

/**
 * A JSON schema representing booth staff.
 */
export type BoothStaffRequest = {
  /**
   * The associated Attendee.
   */
  attendee: Attendee12;
  /**
   * The Associated Event.
   */
  event: Event3;
  /**
   * The Associated Exhibitor.
   */
  exhibitor: Exhibitor;
};

/** @internal */
export type BoothStaffRequest$Outbound = {
  attendee: Attendee12$Outbound;
  event: Event3$Outbound;
  exhibitor: Exhibitor$Outbound;
};

/** @internal */
export const BoothStaffRequest$outboundSchema: z.ZodType<
  BoothStaffRequest$Outbound,
  z.ZodTypeDef,
  BoothStaffRequest
> = z.object({
  attendee: Attendee12$outboundSchema,
  event: Event3$outboundSchema,
  exhibitor: Exhibitor$outboundSchema,
});

export function boothStaffRequestToJSON(
  boothStaffRequest: BoothStaffRequest,
): string {
  return JSON.stringify(
    BoothStaffRequest$outboundSchema.parse(boothStaffRequest),
  );
}
