/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CreateUpdateDiscountCode,
  CreateUpdateDiscountCode$Outbound,
  CreateUpdateDiscountCode$outboundSchema,
} from "./createupdatediscountcode.js";
import {
  CreateUpdateVolumeDiscount,
  CreateUpdateVolumeDiscount$Outbound,
  CreateUpdateVolumeDiscount$outboundSchema,
} from "./createupdatevolumediscount.js";

/**
 * Representation of an existing discount that can be created or updated for an event.
 */
export type CreateUpdateDiscount =
  | CreateUpdateDiscountCode
  | CreateUpdateVolumeDiscount;

/** @internal */
export type CreateUpdateDiscount$Outbound =
  | CreateUpdateDiscountCode$Outbound
  | CreateUpdateVolumeDiscount$Outbound;

/** @internal */
export const CreateUpdateDiscount$outboundSchema: z.ZodType<
  CreateUpdateDiscount$Outbound,
  z.ZodTypeDef,
  CreateUpdateDiscount
> = z.union([
  CreateUpdateDiscountCode$outboundSchema,
  CreateUpdateVolumeDiscount$outboundSchema,
]);

export function createUpdateDiscountToJSON(
  createUpdateDiscount: CreateUpdateDiscount,
): string {
  return JSON.stringify(
    CreateUpdateDiscount$outboundSchema.parse(createUpdateDiscount),
  );
}
