/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { DeviceType, DeviceType$inboundSchema } from "./devicetype.js";

/**
 * The device details used to watched a video. This field has been deprecated.
 *
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type Device1 = {
  /**
   * The unique ID of the device the viewer used to watch the video.
   */
  id?: string | undefined;
  /**
   * The device used to watch the video. Videos can be viewed on desktop, mobile or tablet.
   */
  type?: DeviceType | undefined;
  /**
   * The device's operating system.
   */
  operatingSystem?: string | undefined;
};

/** @internal */
export const Device1$inboundSchema: z.ZodType<Device1, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string().optional(),
    type: DeviceType$inboundSchema.optional(),
    operatingSystem: z.string().optional(),
  });

export function device1FromJSON(
  jsonString: string,
): SafeParseResult<Device1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Device1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Device1' from JSON`,
  );
}
