/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DiscountAgendaItemJson,
  DiscountAgendaItemJson$inboundSchema,
} from "./discountagendaitemjson.js";
import { PagingJson, PagingJson$inboundSchema } from "./pagingjson.js";

/**
 * A paginated response containing a list of agenda items associated with a discount.
 */
export type DiscountAgendaItemsPaginatedResponse = {
  /**
   * Represents pagination information for a collection of resources.
   */
  paging: PagingJson;
  /**
   * Collection of associated agenda items for a discount.
   */
  data: Array<DiscountAgendaItemJson>;
};

/** @internal */
export const DiscountAgendaItemsPaginatedResponse$inboundSchema: z.ZodType<
  DiscountAgendaItemsPaginatedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  paging: PagingJson$inboundSchema,
  data: z.array(DiscountAgendaItemJson$inboundSchema),
});

export function discountAgendaItemsPaginatedResponseFromJSON(
  jsonString: string,
): SafeParseResult<DiscountAgendaItemsPaginatedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DiscountAgendaItemsPaginatedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiscountAgendaItemsPaginatedResponse' from JSON`,
  );
}
