/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EmailStatusJson,
  EmailStatusJson$inboundSchema,
} from "./emailstatusjson.js";
import {
  EmailTypeJson3,
  EmailTypeJson3$inboundSchema,
} from "./emailtypejson3.js";

/**
 * Event Id for email history record.
 */
export type EmailHistoryJsonEvent = {
  /**
   * A string that has to be a format matching the industry standard uuid
   */
  id: string;
};

/**
 * Contact Id for email history record.
 */
export type EmailHistoryJsonContact = {
  /**
   * A string that has to be a format matching the industry standard uuid
   */
  id: string;
};

/**
 * Attendee Id for email history record.
 */
export type EmailHistoryJsonAttendee = {
  /**
   * A string that has to be a format matching the industry standard uuid
   */
  id: string;
};

/**
 * Email History record.
 */
export type EmailHistoryJson = {
  /**
   * The ISO 8601 zoned date time when this record was created.
   */
  created?: Date | undefined;
  /**
   * The identifier of the user that created this record.
   */
  createdBy?: string | undefined;
  /**
   * The ISO 8601 zoned date time when this record was updated.
   */
  lastModified?: Date | undefined;
  /**
   * The identifier of the user that last updated this record.
   */
  lastModifiedBy?: string | undefined;
  /**
   * Unique Id of an email history record.
   */
  id?: string | undefined;
  /**
   * Event Id for email history record.
   */
  event?: EmailHistoryJsonEvent | undefined;
  /**
   * Contact Id for email history record.
   */
  contact?: EmailHistoryJsonContact | undefined;
  /**
   * Attendee Id for email history record.
   */
  attendee?: EmailHistoryJsonAttendee | undefined;
  /**
   * Subject of the email.
   */
  subject?: string | undefined;
  /**
   * From email address of the email.
   */
  from?: string | undefined;
  /**
   * Recipient address of the email.
   */
  to?: string | undefined;
  /**
   * Denotes the type of the email.
   */
  type?: EmailTypeJson3 | undefined;
  /**
   * The ISO 8601 zoned date time when this email was sent.
   */
  sent?: Date | undefined;
  /**
   * This is used to denote the status of the email sending
   */
  status?: EmailStatusJson | undefined;
  /**
   * Flag to indicate if email was undelivered.
   */
  undeliverable?: boolean | undefined;
  /**
   * Flag to indicate if email was opened.
   */
  opened?: boolean | undefined;
  /**
   * The ISO 8601 zoned date time when the email was first opened.
   */
  firstOpened?: Date | undefined;
  /**
   * Flag to indicate if any link in the email was clicked.
   */
  clicked?: boolean | undefined;
  /**
   * The ISO 8601 zoned date time when any link in the email was first clicked.
   */
  firstClicked?: Date | undefined;
  /**
   * Flag to indicate if the email was bounced.
   */
  bounced?: boolean | undefined;
};

/** @internal */
export const EmailHistoryJsonEvent$inboundSchema: z.ZodType<
  EmailHistoryJsonEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export function emailHistoryJsonEventFromJSON(
  jsonString: string,
): SafeParseResult<EmailHistoryJsonEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailHistoryJsonEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailHistoryJsonEvent' from JSON`,
  );
}

/** @internal */
export const EmailHistoryJsonContact$inboundSchema: z.ZodType<
  EmailHistoryJsonContact,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export function emailHistoryJsonContactFromJSON(
  jsonString: string,
): SafeParseResult<EmailHistoryJsonContact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailHistoryJsonContact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailHistoryJsonContact' from JSON`,
  );
}

/** @internal */
export const EmailHistoryJsonAttendee$inboundSchema: z.ZodType<
  EmailHistoryJsonAttendee,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export function emailHistoryJsonAttendeeFromJSON(
  jsonString: string,
): SafeParseResult<EmailHistoryJsonAttendee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailHistoryJsonAttendee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailHistoryJsonAttendee' from JSON`,
  );
}

/** @internal */
export const EmailHistoryJson$inboundSchema: z.ZodType<
  EmailHistoryJson,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  createdBy: z.string().optional(),
  lastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  lastModifiedBy: z.string().optional(),
  id: z.string().optional(),
  event: z.lazy(() => EmailHistoryJsonEvent$inboundSchema).optional(),
  contact: z.lazy(() => EmailHistoryJsonContact$inboundSchema).optional(),
  attendee: z.lazy(() => EmailHistoryJsonAttendee$inboundSchema).optional(),
  subject: z.string().optional(),
  from: z.string().optional(),
  to: z.string().optional(),
  type: EmailTypeJson3$inboundSchema.optional(),
  sent: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  status: EmailStatusJson$inboundSchema.optional(),
  undeliverable: z.boolean().optional(),
  opened: z.boolean().optional(),
  firstOpened: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  clicked: z.boolean().optional(),
  firstClicked: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  bounced: z.boolean().optional(),
});

export function emailHistoryJsonFromJSON(
  jsonString: string,
): SafeParseResult<EmailHistoryJson, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailHistoryJson$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailHistoryJson' from JSON`,
  );
}
