/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Event type.
 */
export const EventTypeJson0 = {
  AnniversaryBirthday: "ANNIVERSARY_BIRTHDAY",
  BachelorBacheloretteParty: "BACHELOR_BACHELORETTE_PARTY",
  BarBatMitzvah: "BAR_BAT_MITZVAH",
  BusinessMeeting: "BUSINESS_MEETING",
  ConferenceConvention: "CONFERENCE_CONVENTION",
  CorporateEvent: "CORPORATE_EVENT",
  CustomerEvent: "CUSTOMER_EVENT",
  EducationalSeminar: "EDUCATIONAL_SEMINAR",
  FraternitySororityGroup: "FRATERNITY_SORORITY_GROUP",
  FundraiserCharityEvent: "FUNDRAISER_CHARITY_EVENT",
  ReceptionHolidayParty: "RECEPTION_HOLIDAY_PARTY",
  IncentiveTravel: "INCENTIVE_TRAVEL",
  Reunion: "REUNION",
  ShareholdersMeeting: "SHAREHOLDERS_MEETING",
  SpecialEvent: "SPECIAL_EVENT",
  SportsEvent: "SPORTS_EVENT",
  TeamBuildingEvent: "TEAM_BUILDING_EVENT",
  TourGroupVacation: "TOUR_GROUP_VACATION",
  TradeShowConsumerShow: "TRADE_SHOW_CONSUMER_SHOW",
  Training: "TRAINING",
  Wedding: "WEDDING",
  Other: "OTHER",
} as const;
/**
 * Event type.
 */
export type EventTypeJson0 = ClosedEnum<typeof EventTypeJson0>;

/** @internal */
export const EventTypeJson0$inboundSchema: z.ZodNativeEnum<
  typeof EventTypeJson0
> = z.nativeEnum(EventTypeJson0);
