/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Event1, Event1$inboundSchema } from "./event1.js";
import { Paging, Paging$inboundSchema } from "./paging.js";

/**
 * Represents a paginated collection of event objects.
 */
export type EventPaginatedResponse = {
  /**
   * Represents pagination information for a collection of resources.
   */
  paging: Paging;
  /**
   * A collection of event objects.
   */
  data: Array<Event1>;
};

/** @internal */
export const EventPaginatedResponse$inboundSchema: z.ZodType<
  EventPaginatedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  paging: Paging$inboundSchema,
  data: z.array(Event1$inboundSchema),
});

export function eventPaginatedResponseFromJSON(
  jsonString: string,
): SafeParseResult<EventPaginatedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventPaginatedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventPaginatedResponse' from JSON`,
  );
}
