/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  HubBackgroundJson,
  HubBackgroundJson$inboundSchema,
} from "./hubbackgroundjson.js";
import {
  HubCalendarJson,
  HubCalendarJson$inboundSchema,
} from "./hubcalendarjson.js";
import { HubColorsJson, HubColorsJson$inboundSchema } from "./hubcolorsjson.js";
import { HubFontsJson, HubFontsJson$inboundSchema } from "./hubfontsjson.js";
import { HubLoginJson, HubLoginJson$inboundSchema } from "./hubloginjson.js";
import { HubLogoJson, HubLogoJson$inboundSchema } from "./hublogojson.js";
import { HubOwnerJson, HubOwnerJson$inboundSchema } from "./hubownerjson.js";
import {
  HubStatusPropertyJson,
  HubStatusPropertyJson$inboundSchema,
} from "./hubstatuspropertyjson.js";
import {
  UtmOverrideJson,
  UtmOverrideJson$inboundSchema,
} from "./utmoverridejson.js";

/**
 * Represents an existing Events+ hub.
 */
export type ExistingHub = {
  /**
   * The ISO 8601 zoned date time when this record was created.
   */
  created?: Date | undefined;
  /**
   * The identifier of the user that created this record.
   */
  createdBy?: string | undefined;
  /**
   * The ISO 8601 zoned date time when this record was updated.
   */
  lastModified?: Date | undefined;
  /**
   * The identifier of the user that last updated this record.
   */
  lastModifiedBy?: string | undefined;
  /**
   * A short descriptor of the Events+ hub.
   */
  title: string;
  /**
   * The owner of the Events+ hub and their information.
   */
  owner: HubOwnerJson;
  /**
   * Custom domain name of the Events+ hub.
   */
  customDomain?: string | undefined;
  /**
   * The URL that links to the Events+ hub.
   */
  url?: string | undefined;
  /**
   * All the colors associated with the Events+ hub.
   */
  colors?: HubColorsJson | undefined;
  /**
   * True guarantees that controls shown on the page will contrast with the background color.
   */
  themeSafeMode?: boolean | undefined;
  /**
   * The logo for the Events+ hub.
   */
  logo?: HubLogoJson | undefined;
  /**
   * The background image of the Events+ hub.
   */
  background?: HubBackgroundJson | undefined;
  /**
   * An IETF BCP 47 language tag used to indicate the language of the Events+ hub.
   */
  locale?: string | undefined;
  /**
   * The event calendar associated with this Events+ hub. The event calendar allows you to share multiple events and sessions in a list or calendar format.
   */
  calendar?: HubCalendarJson | undefined;
  /**
   * Help email address to reach out in case of any issues logging in or registering.
   */
  helpEmailAddress?: string | undefined;
  /**
   * True indicates the Events+ hub should detect the browser locale. If translations for the detected language are enabled in the Events+ hub, the Events+ hub will switch to the detected language.
   */
  autoDetectBrowserLocale?: boolean | undefined;
  /**
   * URL of the Events+ hub favicon.
   */
  faviconUrl?: string | undefined;
  /**
   * Specifies how UTM (urchin tracking module: a key and value that is attached to URLs for the purpose of identifying and tracking traffic) settings will override passed in items.
   */
  utmOverride?: UtmOverrideJson | undefined;
  /**
   * The fonts of the Events+ hub.
   */
  fonts?: HubFontsJson | undefined;
  /**
   * Fields relating to the login process for the Events+ hub.
   */
  login?: HubLoginJson | undefined;
  /**
   * The unique ID of an Events+ Hub.
   */
  id?: string | undefined;
  /**
   * The current Events+ Hub status. Inactive: The Events+ Hub is inactive and unavailable to members. Active: Members can access the Events+ Hub. Deleted: The Events+ Hub has been deleted and is unavailable to members or planners.
   */
  status?: HubStatusPropertyJson | undefined;
};

/** @internal */
export const ExistingHub$inboundSchema: z.ZodType<
  ExistingHub,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  createdBy: z.string().optional(),
  lastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  lastModifiedBy: z.string().optional(),
  title: z.string(),
  owner: HubOwnerJson$inboundSchema,
  customDomain: z.string().optional(),
  url: z.string().optional(),
  colors: HubColorsJson$inboundSchema.optional(),
  themeSafeMode: z.boolean().default(false),
  logo: HubLogoJson$inboundSchema.optional(),
  background: HubBackgroundJson$inboundSchema.optional(),
  locale: z.string().optional(),
  calendar: HubCalendarJson$inboundSchema.optional(),
  helpEmailAddress: z.string().optional(),
  autoDetectBrowserLocale: z.boolean().optional(),
  faviconUrl: z.string().optional(),
  utmOverride: UtmOverrideJson$inboundSchema.default("use-existing-parameter"),
  fonts: HubFontsJson$inboundSchema.optional(),
  login: HubLoginJson$inboundSchema.optional(),
  id: z.string().optional(),
  status: HubStatusPropertyJson$inboundSchema.optional(),
});

export function existingHubFromJSON(
  jsonString: string,
): SafeParseResult<ExistingHub, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExistingHub$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExistingHub' from JSON`,
  );
}
