/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Answer2, Answer2$inboundSchema } from "./answer2.js";
import { Event21, Event21$inboundSchema } from "./event21.js";
import { Exhibitor, Exhibitor$inboundSchema } from "./exhibitor.js";
import { Uuid, Uuid$inboundSchema } from "./uuid.js";

/**
 * Existing Exhibitor Answer schema
 */
export type ExistingExhibitorAnswer = {
  /**
   * The ISO 8601 zoned date time when this record was created.
   */
  created?: Date | undefined;
  /**
   * The identifier of the user that created this record.
   */
  createdBy?: string | undefined;
  /**
   * The ISO 8601 zoned date time when this record was updated.
   */
  lastModified?: Date | undefined;
  /**
   * The identifier of the user that last updated this record.
   */
  lastModifiedBy?: string | undefined;
  /**
   * The reference to the related entity. Contains only the ID of the related entity.
   */
  question: Uuid;
  /**
   * The Associated Event.
   */
  event: Event21;
  /**
   * The Associated Exhibitor.
   */
  exhibitor: Exhibitor;
  /**
   * List of answers
   */
  answers: Array<Answer2>;
  /**
   * Exhibitor Answer id
   */
  id: string;
};

/** @internal */
export const ExistingExhibitorAnswer$inboundSchema: z.ZodType<
  ExistingExhibitorAnswer,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  createdBy: z.string().optional(),
  lastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  lastModifiedBy: z.string().optional(),
  question: Uuid$inboundSchema,
  event: Event21$inboundSchema,
  exhibitor: Exhibitor$inboundSchema,
  answers: z.array(Answer2$inboundSchema),
  id: z.string(),
});

export function existingExhibitorAnswerFromJSON(
  jsonString: string,
): SafeParseResult<ExistingExhibitorAnswer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExistingExhibitorAnswer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExistingExhibitorAnswer' from JSON`,
  );
}
