/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AdditionalChoice,
  AdditionalChoice$inboundSchema,
} from "./additionalchoice.js";
import { Choice, Choice$inboundSchema } from "./choice.js";
import { Event1, Event1$inboundSchema } from "./event1.js";
import { Exhibitor, Exhibitor$inboundSchema } from "./exhibitor.js";

/**
 * Type of question
 */
export const LeadQualificationQuestionType = {
  MultiChoice: "MultiChoice",
  SingleChoice: "SingleChoice",
  Rating: "Rating",
  OpenEndedTextOneLine: "OpenEndedTextOneLine",
  OpenEndedTextCommentBox: "OpenEndedTextCommentBox",
  OpenEndedDateTime: "OpenEndedDateTime",
} as const;
/**
 * Type of question
 */
export type LeadQualificationQuestionType = ClosedEnum<
  typeof LeadQualificationQuestionType
>;

/**
 * A JSON schema representing a Lead Qualification Question model
 */
export type LeadQualificationQuestion = {
  /**
   * The ISO 8601 zoned date time when this record was created.
   */
  created?: Date | undefined;
  /**
   * The identifier of the user that created this record.
   */
  createdBy?: string | undefined;
  /**
   * The ISO 8601 zoned date time when this record was updated.
   */
  lastModified?: Date | undefined;
  /**
   * The identifier of the user that last updated this record.
   */
  lastModifiedBy?: string | undefined;
  /**
   * Lead Qualification Question id
   */
  id?: string | undefined;
  /**
   * The Associated Event.
   */
  event?: Event1 | undefined;
  /**
   * The Associated Exhibitor.
   */
  exhibitor?: Exhibitor | undefined;
  /**
   * Type of question
   */
  type?: LeadQualificationQuestionType | undefined;
  /**
   * question code
   */
  code?: string | undefined;
  /**
   * List of available choices for the question
   */
  choices?: Array<Choice> | undefined;
  /**
   * Contains text of additional choice
   */
  notApplicableAnswer?: AdditionalChoice | undefined;
  /**
   * Contains text of additional choice
   */
  otherAnswers?: AdditionalChoice | undefined;
  /**
   * A boolean indicating whether the question is mandatory or not
   */
  required?: boolean | undefined;
  /**
   * text of the question
   */
  text?: string | undefined;
};

/** @internal */
export const LeadQualificationQuestionType$inboundSchema: z.ZodNativeEnum<
  typeof LeadQualificationQuestionType
> = z.nativeEnum(LeadQualificationQuestionType);

/** @internal */
export const LeadQualificationQuestion$inboundSchema: z.ZodType<
  LeadQualificationQuestion,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  createdBy: z.string().optional(),
  lastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  lastModifiedBy: z.string().optional(),
  id: z.string().optional(),
  event: Event1$inboundSchema.optional(),
  exhibitor: Exhibitor$inboundSchema.optional(),
  type: LeadQualificationQuestionType$inboundSchema.optional(),
  code: z.string().optional(),
  choices: z.array(Choice$inboundSchema).optional(),
  notApplicableAnswer: AdditionalChoice$inboundSchema.optional(),
  otherAnswers: AdditionalChoice$inboundSchema.optional(),
  required: z.boolean().optional(),
  text: z.string().optional(),
});

export function leadQualificationQuestionFromJSON(
  jsonString: string,
): SafeParseResult<LeadQualificationQuestion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeadQualificationQuestion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeadQualificationQuestion' from JSON`,
  );
}
