/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Used to denote a locations name and abbreviation.
 */
export type LocationJson2 = {
  /**
   * A string that has to be a format matching the industry standard uuid
   */
  id?: string | undefined;
  /**
   * Code / Abbreviation of the location.
   */
  code?: string | undefined;
  /**
   * Name of the location.
   */
  name?: string | undefined;
};

/** @internal */
export const LocationJson2$inboundSchema: z.ZodType<
  LocationJson2,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  code: z.string().optional(),
  name: z.string().optional(),
});

export function locationJson2FromJSON(
  jsonString: string,
): SafeParseResult<LocationJson2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LocationJson2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LocationJson2' from JSON`,
  );
}
