/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The answer format that a given number is stored in.
 */
export const NumericAnswerFormat = {
  Currency: "Currency",
  Decimal: "Decimal",
  Number: "Number",
} as const;
/**
 * The answer format that a given number is stored in.
 */
export type NumericAnswerFormat = ClosedEnum<typeof NumericAnswerFormat>;

/** @internal */
export const NumericAnswerFormat$inboundSchema: z.ZodNativeEnum<
  typeof NumericAnswerFormat
> = z.nativeEnum(NumericAnswerFormat);
