/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PagingJson, PagingJson$inboundSchema } from "./pagingjson.js";
import {
  RfpRecipientLogEntryJson,
  RfpRecipientLogEntryJson$inboundSchema,
} from "./rfprecipientlogentryjson.js";

/**
 * Paginated response containing logs of all the recipients that were copied on an RFP.
 */
export type PaginatedRfpRecipientsHistory = {
  /**
   * Represents pagination information for a collection of resources.
   */
  paging: PagingJson;
  /**
   * List of RFP recipient logs.
   */
  data: Array<RfpRecipientLogEntryJson>;
};

/** @internal */
export const PaginatedRfpRecipientsHistory$inboundSchema: z.ZodType<
  PaginatedRfpRecipientsHistory,
  z.ZodTypeDef,
  unknown
> = z.object({
  paging: PagingJson$inboundSchema,
  data: z.array(RfpRecipientLogEntryJson$inboundSchema),
});

export function paginatedRfpRecipientsHistoryFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedRfpRecipientsHistory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedRfpRecipientsHistory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedRfpRecipientsHistory' from JSON`,
  );
}
