/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents a planner for an appointment event and the planner's related details.
 */
export type PlannerJson = {
  /**
   * The first name of the planner.
   */
  firstName?: string | undefined;
  /**
   * The last name of the planner.
   */
  lastName?: string | undefined;
  /**
   * The email address of the planner.
   */
  email?: string | undefined;
  /**
   * The company/organization the planner belongs to.
   */
  company?: string | undefined;
  /**
   * The job title of the planner.
   */
  title?: string | undefined;
  /**
   * Denotes what is traditionally a title of an individual.
   */
  prefix?: string | undefined;
};

/** @internal */
export const PlannerJson$inboundSchema: z.ZodType<
  PlannerJson,
  z.ZodTypeDef,
  unknown
> = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
  company: z.string().optional(),
  title: z.string().optional(),
  prefix: z.string().optional(),
});

export function plannerJsonFromJSON(
  jsonString: string,
): SafeParseResult<PlannerJson, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlannerJson$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlannerJson' from JSON`,
  );
}
