/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AddressJson3, AddressJson3$inboundSchema } from "./addressjson3.js";
import {
  OtherPaymentJson,
  OtherPaymentJson$inboundSchema,
} from "./otherpaymentjson.js";
import {
  PaymentTypesJson,
  PaymentTypesJson$inboundSchema,
} from "./paymenttypesjson.js";
import {
  TokenizedCreditCardJsonOutput,
  TokenizedCreditCardJsonOutput$inboundSchema,
} from "./tokenizedcreditcardjsonoutput.js";

/**
 * Payment information.
 */
export type ReservationPaymentInfoJsonOutput = {
  /**
   * Payment type.
   */
  paymentType?: PaymentTypesJson | undefined;
  /**
   * Full name.
   */
  fullName?: string | undefined;
  /**
   * Address details. Required to create/update a guest's reservation if the hotel/event requires an address in reservations.
   */
  address?: AddressJson3 | undefined;
  /**
   * Phone number.
   */
  phone?: string | undefined;
  /**
   * Other payment details.
   */
  other?: OtherPaymentJson | undefined;
  /**
   * Credit card info.
   */
  creditCard?: TokenizedCreditCardJsonOutput | undefined;
};

/** @internal */
export const ReservationPaymentInfoJsonOutput$inboundSchema: z.ZodType<
  ReservationPaymentInfoJsonOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  paymentType: PaymentTypesJson$inboundSchema.optional(),
  fullName: z.string().optional(),
  address: AddressJson3$inboundSchema.optional(),
  phone: z.string().optional(),
  other: OtherPaymentJson$inboundSchema.optional(),
  creditCard: TokenizedCreditCardJsonOutput$inboundSchema.optional(),
});

export function reservationPaymentInfoJsonOutputFromJSON(
  jsonString: string,
): SafeParseResult<ReservationPaymentInfoJsonOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReservationPaymentInfoJsonOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReservationPaymentInfoJsonOutput' from JSON`,
  );
}
