/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * An activity speaker.
 */
export type Speaker1 = {
  /**
   * The unique identifier of the speaker.
   */
  id?: string | undefined;
  /**
   * Name of the speaker.
   */
  name?: string | undefined;
};

/** @internal */
export const Speaker1$inboundSchema: z.ZodType<
  Speaker1,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});

export function speaker1FromJSON(
  jsonString: string,
): SafeParseResult<Speaker1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Speaker1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Speaker1' from JSON`,
  );
}
