/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TravelBidDispositionJson,
  TravelBidDispositionJson$inboundSchema,
} from "./travelbiddispositionjson.js";

/**
 * Represent proposal disposition details.
 */
export type TravelProposalDispositionJson = {
  /**
   * List of bid dispositions.
   */
  bidDispositions?: Array<TravelBidDispositionJson> | undefined;
  /**
   * Indicates if the group and meeting is accepted.
   */
  groupAndMeetingAccepted?: boolean | undefined;
};

/** @internal */
export const TravelProposalDispositionJson$inboundSchema: z.ZodType<
  TravelProposalDispositionJson,
  z.ZodTypeDef,
  unknown
> = z.object({
  bidDispositions: z.array(TravelBidDispositionJson$inboundSchema).optional(),
  groupAndMeetingAccepted: z.boolean().optional(),
});

export function travelProposalDispositionJsonFromJSON(
  jsonString: string,
): SafeParseResult<TravelProposalDispositionJson, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TravelProposalDispositionJson$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TravelProposalDispositionJson' from JSON`,
  );
}
