/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unit position used for text box question type.
 */
export const UnitPositionJson = {
  Left: "Left",
  Right: "Right",
} as const;
/**
 * Unit position used for text box question type.
 */
export type UnitPositionJson = ClosedEnum<typeof UnitPositionJson>;

/** @internal */
export const UnitPositionJson$inboundSchema: z.ZodNativeEnum<
  typeof UnitPositionJson
> = z.nativeEnum(UnitPositionJson);
