/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Venue Address details
 */
export type VenueAddressJsonInput = {
  /**
   * The first line of an address.
   */
  address1?: string | undefined;
  /**
   * The second line of an address.
   */
  address2?: string | undefined;
  /**
   * The third line of an address.
   */
  address3?: string | undefined;
  /**
   * The name of the city.
   */
  city?: string | undefined;
  /**
   * ISO 3166 two-letter (alpha-2) country code.
   */
  countryCode?: string | undefined;
  /**
   * Postal code (also known as zipcode) of the address.
   */
  postalCode?: string | undefined;
  /**
   * The abbreviation of the state/province/region of the address.
   */
  regionCode?: string | undefined;
};

/** @internal */
export type VenueAddressJsonInput$Outbound = {
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  city?: string | undefined;
  countryCode?: string | undefined;
  postalCode?: string | undefined;
  regionCode?: string | undefined;
};

/** @internal */
export const VenueAddressJsonInput$outboundSchema: z.ZodType<
  VenueAddressJsonInput$Outbound,
  z.ZodTypeDef,
  VenueAddressJsonInput
> = z.object({
  address1: z.string().optional(),
  address2: z.string().optional(),
  address3: z.string().optional(),
  city: z.string().optional(),
  countryCode: z.string().optional(),
  postalCode: z.string().optional(),
  regionCode: z.string().optional(),
});

export function venueAddressJsonInputToJSON(
  venueAddressJsonInput: VenueAddressJsonInput,
): string {
  return JSON.stringify(
    VenueAddressJsonInput$outboundSchema.parse(venueAddressJsonInput),
  );
}
