/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Video that this asset was created with.
 */
export type VideoAssetIdJson = {
  /**
   * The identifier of a video.
   */
  id: string;
};

/** @internal */
export const VideoAssetIdJson$inboundSchema: z.ZodType<
  VideoAssetIdJson,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type VideoAssetIdJson$Outbound = {
  id: string;
};

/** @internal */
export const VideoAssetIdJson$outboundSchema: z.ZodType<
  VideoAssetIdJson$Outbound,
  z.ZodTypeDef,
  VideoAssetIdJson
> = z.object({
  id: z.string(),
});

export function videoAssetIdJsonToJSON(
  videoAssetIdJson: VideoAssetIdJson,
): string {
  return JSON.stringify(
    VideoAssetIdJson$outboundSchema.parse(videoAssetIdJson),
  );
}
export function videoAssetIdJsonFromJSON(
  jsonString: string,
): SafeParseResult<VideoAssetIdJson, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VideoAssetIdJson$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VideoAssetIdJson' from JSON`,
  );
}
