/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Booth staff for an activity.
 */
export type ZeroAllOf4 = {
  /**
   * The unique identifier of the exhibitor booth staff.
   */
  id?: string | undefined;
  /**
   * The first name of the booth staff that captured the lead.
   */
  firstName?: string | undefined;
  /**
   * The last name of the booth staff that captured the lead.
   */
  lastName?: string | undefined;
  /**
   * The email address of the booth staff that captured the lead.
   */
  email?: string | undefined;
};

/** @internal */
export const ZeroAllOf4$inboundSchema: z.ZodType<
  ZeroAllOf4,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
});

export function zeroAllOf4FromJSON(
  jsonString: string,
): SafeParseResult<ZeroAllOf4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ZeroAllOf4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ZeroAllOf4' from JSON`,
  );
}
