/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import static com.cvent.operations.Operations.RequestOperation;

import com.cvent.SDKConfiguration;
import com.cvent.operations.GetAppointmentById;
import com.cvent.utils.Headers;
import com.cvent.utils.Options;
import com.cvent.utils.RetryConfig;
import com.cvent.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

public class GetAppointmentByIdRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GetAppointmentByIdRequest request;
    private final Options.Builder optionsBuilder;

    public GetAppointmentByIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public GetAppointmentByIdRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public GetAppointmentByIdRequestBuilder request(@Nonnull GetAppointmentByIdRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private GetAppointmentByIdRequest _buildRequest() {
        return this.request;
    }

    public GetAppointmentByIdRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
     * Executes the request and returns the response.
     *
     * @return The response from the server.
     */
    public GetAppointmentByIdResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<GetAppointmentByIdRequest, GetAppointmentByIdResponse> operation =
                new GetAppointmentById.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
