/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import com.cvent.utils.SpeakeasyMetadata;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

public class GetEventEmailStatusRequest {
    /**
     * Used to get status of emails which were sent with this email request ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=emailRequestId")
    private String emailRequestId;

    @JsonCreator
    public GetEventEmailStatusRequest(@Nonnull String emailRequestId) {
        this.emailRequestId = Optional.ofNullable(emailRequestId)
                .orElseThrow(() -> new IllegalArgumentException("emailRequestId cannot be null"));
    }

    /**
     * Used to get status of emails which were sent with this email request ID.
     */
    public String emailRequestId() {
        return this.emailRequestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Used to get status of emails which were sent with this email request ID.
     */
    public GetEventEmailStatusRequest withEmailRequestId(@Nonnull String emailRequestId) {
        this.emailRequestId = Utils.checkNotNull(emailRequestId, "emailRequestId");
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetEventEmailStatusRequest other = (GetEventEmailStatusRequest) o;
        return Utils.enhancedDeepEquals(this.emailRequestId, other.emailRequestId);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(emailRequestId);
    }

    @Override
    public String toString() {
        return Utils.toString(GetEventEmailStatusRequest.class, "emailRequestId", emailRequestId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String emailRequestId;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * Used to get status of emails which were sent with this email request ID.
         */
        public Builder emailRequestId(@Nonnull String emailRequestId) {
            this.emailRequestId = Utils.checkNotNull(emailRequestId, "emailRequestId");
            return this;
        }

        public GetEventEmailStatusRequest build() {
            return new GetEventEmailStatusRequest(emailRequestId);
        }
    }
}
