/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import com.cvent.models.components.LeadQualificationQuestionsListResponse;
import com.cvent.utils.Response;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetLeadQualificationQuestionsResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Successfully retrieved a list of Lead Qualification Questions.
     */
    private LeadQualificationQuestionsListResponse leadQualificationQuestionsListResponse;

    @JsonCreator
    public GetLeadQualificationQuestionsResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable LeadQualificationQuestionsListResponse leadQualificationQuestionsListResponse) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.leadQualificationQuestionsListResponse = leadQualificationQuestionsListResponse;
    }
    
    public GetLeadQualificationQuestionsResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * Successfully retrieved a list of Lead Qualification Questions.
     */
    public Optional<LeadQualificationQuestionsListResponse> leadQualificationQuestionsListResponse() {
        return Optional.ofNullable(this.leadQualificationQuestionsListResponse);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetLeadQualificationQuestionsResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public GetLeadQualificationQuestionsResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetLeadQualificationQuestionsResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * Successfully retrieved a list of Lead Qualification Questions.
     */
    public GetLeadQualificationQuestionsResponse withLeadQualificationQuestionsListResponse(@Nullable LeadQualificationQuestionsListResponse leadQualificationQuestionsListResponse) {
        this.leadQualificationQuestionsListResponse = leadQualificationQuestionsListResponse;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetLeadQualificationQuestionsResponse other = (GetLeadQualificationQuestionsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.leadQualificationQuestionsListResponse, other.leadQualificationQuestionsListResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            leadQualificationQuestionsListResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetLeadQualificationQuestionsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "leadQualificationQuestionsListResponse", leadQualificationQuestionsListResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private LeadQualificationQuestionsListResponse leadQualificationQuestionsListResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * Successfully retrieved a list of Lead Qualification Questions.
         */
        public Builder leadQualificationQuestionsListResponse(@Nullable LeadQualificationQuestionsListResponse leadQualificationQuestionsListResponse) {
            this.leadQualificationQuestionsListResponse = leadQualificationQuestionsListResponse;
            return this;
        }

        public GetLeadQualificationQuestionsResponse build() {
            return new GetLeadQualificationQuestionsResponse(
                contentType, statusCode, rawResponse,
                leadQualificationQuestionsListResponse);
        }

    }
}
