/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import com.cvent.utils.SpeakeasyMetadata;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

public class GetSessionProgramSpeakerRequest {
    /**
     * The unique identifier of a program item.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=programItemId")
    private String programItemId;

    /**
     * The unique identifier of a speaker.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    @JsonCreator
    public GetSessionProgramSpeakerRequest(@Nonnull String programItemId, @Nonnull String id) {
        this.programItemId = Optional.ofNullable(programItemId)
                .orElseThrow(() -> new IllegalArgumentException("programItemId cannot be null"));
        this.id = Optional.ofNullable(id).orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
    }

    /**
     * The unique identifier of a program item.
     */
    public String programItemId() {
        return this.programItemId;
    }

    /**
     * The unique identifier of a speaker.
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * The unique identifier of a program item.
     */
    public GetSessionProgramSpeakerRequest withProgramItemId(@Nonnull String programItemId) {
        this.programItemId = Utils.checkNotNull(programItemId, "programItemId");
        return this;
    }

    /**
     * The unique identifier of a speaker.
     */
    public GetSessionProgramSpeakerRequest withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSessionProgramSpeakerRequest other = (GetSessionProgramSpeakerRequest) o;
        return Utils.enhancedDeepEquals(this.programItemId, other.programItemId)
                && Utils.enhancedDeepEquals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(programItemId, id);
    }

    @Override
    public String toString() {
        return Utils.toString(GetSessionProgramSpeakerRequest.class, "programItemId", programItemId, "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String programItemId;

        private String id;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * The unique identifier of a program item.
         */
        public Builder programItemId(@Nonnull String programItemId) {
            this.programItemId = Utils.checkNotNull(programItemId, "programItemId");
            return this;
        }

        /**
         * The unique identifier of a speaker.
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public GetSessionProgramSpeakerRequest build() {
            return new GetSessionProgramSpeakerRequest(programItemId, id);
        }
    }
}
