/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import com.cvent.utils.LazySingletonValue;
import com.cvent.utils.SpeakeasyMetadata;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetUserGroupsRequest {
    /**
     * Starting index of the response.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=startIndex")
    private Long startIndex;

    /**
     * The count of records to be retrieved in a response.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=count")
    private Long count;

    @JsonCreator
    public GetUserGroupsRequest(
            @Nullable Long startIndex,
            @Nullable Long count) {
        this.startIndex = Optional.ofNullable(startIndex)
            .orElse(Builder._SINGLETON_VALUE_StartIndex.value());
        this.count = Optional.ofNullable(count)
            .orElse(Builder._SINGLETON_VALUE_Count.value());
    }
    
    public GetUserGroupsRequest() {
        this(null, null);
    }

    /**
     * Starting index of the response.
     */
    public Optional<Long> startIndex() {
        return Optional.ofNullable(this.startIndex);
    }

    /**
     * The count of records to be retrieved in a response.
     */
    public Optional<Long> count() {
        return Optional.ofNullable(this.count);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Starting index of the response.
     */
    public GetUserGroupsRequest withStartIndex(@Nullable Long startIndex) {
        this.startIndex = startIndex;
        return this;
    }


    /**
     * The count of records to be retrieved in a response.
     */
    public GetUserGroupsRequest withCount(@Nullable Long count) {
        this.count = count;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetUserGroupsRequest other = (GetUserGroupsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.startIndex, other.startIndex) &&
            Utils.enhancedDeepEquals(this.count, other.count);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            startIndex, count);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetUserGroupsRequest.class,
                "startIndex", startIndex,
                "count", count);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Long startIndex;

        private Long count;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Starting index of the response.
         */
        public Builder startIndex(@Nullable Long startIndex) {
            this.startIndex = startIndex;
            return this;
        }

        /**
         * The count of records to be retrieved in a response.
         */
        public Builder count(@Nullable Long count) {
            this.count = count;
            return this;
        }

        public GetUserGroupsRequest build() {
            return new GetUserGroupsRequest(
                startIndex, count);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_StartIndex =
                new LazySingletonValue<>(
                        "startIndex",
                        "1",
                        new TypeReference<Long>() {});

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Count =
                new LazySingletonValue<>(
                        "count",
                        "100",
                        new TypeReference<Long>() {});
    }
}
