/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import com.cvent.models.components.EventRoleExpand;
import com.cvent.utils.LazySingletonValue;
import com.cvent.utils.SpeakeasyMetadata;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class ListEventRoleAssignmentRequest {
    /**
     * The maximum number of event role assignments that can be fetched at once.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    private Long limit;

    /**
     * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
     * This will override any other pageable parameters provided.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    private String token;

    /**
     * Use the `expand` query parameter to request additional details for each field specified.
     * 
     * <p>Each event role assignment includes the ID of its associated event role. By using the expand
     * parameter, you can also retrieve the name of the event role.
     * 
     * <p>The following fields are expandable:
     * * eventRole
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=expand")
    private List<EventRoleExpand> expand;

    /**
     * A filter query string narrows search results and supports the combination of logical and comparison
     * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
     * This is the comparison type that can be used in filter expressions:
     * * equal: eq
     * 
     * <p>The following fields are filterable:
     * * event.id (eq)
     * * eventRole.id (eq)
     * * user.id (eq)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")
    private String filter;

    @JsonCreator
    public ListEventRoleAssignmentRequest(
            @Nullable Long limit,
            @Nullable String token,
            @Nullable List<EventRoleExpand> expand,
            @Nullable String filter) {
        this.limit = Optional.ofNullable(limit)
            .orElse(Builder._SINGLETON_VALUE_Limit.value());
        this.token = token;
        this.expand = expand;
        this.filter = filter;
    }
    
    public ListEventRoleAssignmentRequest() {
        this(null, null, null,
            null);
    }

    /**
     * The maximum number of event role assignments that can be fetched at once.
     */
    public Optional<Long> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
     * This will override any other pageable parameters provided.
     */
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }

    /**
     * Use the `expand` query parameter to request additional details for each field specified.
     * 
     * <p>Each event role assignment includes the ID of its associated event role. By using the expand
     * parameter, you can also retrieve the name of the event role.
     * 
     * <p>The following fields are expandable:
     * * eventRole
     */
    public Optional<List<EventRoleExpand>> expand() {
        return Optional.ofNullable(this.expand);
    }

    /**
     * A filter query string narrows search results and supports the combination of logical and comparison
     * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
     * This is the comparison type that can be used in filter expressions:
     * * equal: eq
     * 
     * <p>The following fields are filterable:
     * * event.id (eq)
     * * eventRole.id (eq)
     * * user.id (eq)
     */
    public Optional<String> filter() {
        return Optional.ofNullable(this.filter);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The maximum number of event role assignments that can be fetched at once.
     */
    public ListEventRoleAssignmentRequest withLimit(@Nullable Long limit) {
        this.limit = limit;
        return this;
    }


    /**
     * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
     * This will override any other pageable parameters provided.
     */
    public ListEventRoleAssignmentRequest withToken(@Nullable String token) {
        this.token = token;
        return this;
    }


    /**
     * Use the `expand` query parameter to request additional details for each field specified.
     * 
     * <p>Each event role assignment includes the ID of its associated event role. By using the expand
     * parameter, you can also retrieve the name of the event role.
     * 
     * <p>The following fields are expandable:
     * * eventRole
     */
    public ListEventRoleAssignmentRequest withExpand(@Nullable List<EventRoleExpand> expand) {
        this.expand = expand;
        return this;
    }


    /**
     * A filter query string narrows search results and supports the combination of logical and comparison
     * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
     * This is the comparison type that can be used in filter expressions:
     * * equal: eq
     * 
     * <p>The following fields are filterable:
     * * event.id (eq)
     * * eventRole.id (eq)
     * * user.id (eq)
     */
    public ListEventRoleAssignmentRequest withFilter(@Nullable String filter) {
        this.filter = filter;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListEventRoleAssignmentRequest other = (ListEventRoleAssignmentRequest) o;
        return 
            Utils.enhancedDeepEquals(this.limit, other.limit) &&
            Utils.enhancedDeepEquals(this.token, other.token) &&
            Utils.enhancedDeepEquals(this.expand, other.expand) &&
            Utils.enhancedDeepEquals(this.filter, other.filter);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            limit, token, expand,
            filter);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListEventRoleAssignmentRequest.class,
                "limit", limit,
                "token", token,
                "expand", expand,
                "filter", filter);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Long limit;

        private String token;

        private List<EventRoleExpand> expand;

        private String filter;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The maximum number of event role assignments that can be fetched at once.
         */
        public Builder limit(@Nullable Long limit) {
            this.limit = limit;
            return this;
        }

        /**
         * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
         * This will override any other pageable parameters provided.
         */
        public Builder token(@Nullable String token) {
            this.token = token;
            return this;
        }

        /**
         * Use the `expand` query parameter to request additional details for each field specified.
         * 
         * <p>Each event role assignment includes the ID of its associated event role. By using the expand
         * parameter, you can also retrieve the name of the event role.
         * 
         * <p>The following fields are expandable:
         * * eventRole
         */
        public Builder expand(@Nullable List<EventRoleExpand> expand) {
            this.expand = expand;
            return this;
        }

        /**
         * A filter query string narrows search results and supports the combination of logical and comparison
         * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
         * This is the comparison type that can be used in filter expressions:
         * * equal: eq
         * 
         * <p>The following fields are filterable:
         * * event.id (eq)
         * * eventRole.id (eq)
         * * user.id (eq)
         */
        public Builder filter(@Nullable String filter) {
            this.filter = filter;
            return this;
        }

        public ListEventRoleAssignmentRequest build() {
            return new ListEventRoleAssignmentRequest(
                limit, token, expand,
                filter);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Limit =
                new LazySingletonValue<>(
                        "limit",
                        "10",
                        new TypeReference<Long>() {});
    }
}
