/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import com.cvent.models.components.EventRoleAssignmentsPaginatedResponse;
import com.cvent.utils.Response;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListEventRoleAssignmentResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Successfully retrieved a paginated list of event role assignments.
     */
    private EventRoleAssignmentsPaginatedResponse eventRoleAssignmentsPaginatedResponse;

    @JsonCreator
    public ListEventRoleAssignmentResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable EventRoleAssignmentsPaginatedResponse eventRoleAssignmentsPaginatedResponse) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.eventRoleAssignmentsPaginatedResponse = eventRoleAssignmentsPaginatedResponse;
    }
    
    public ListEventRoleAssignmentResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * Successfully retrieved a paginated list of event role assignments.
     */
    public Optional<EventRoleAssignmentsPaginatedResponse> eventRoleAssignmentsPaginatedResponse() {
        return Optional.ofNullable(this.eventRoleAssignmentsPaginatedResponse);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListEventRoleAssignmentResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public ListEventRoleAssignmentResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListEventRoleAssignmentResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * Successfully retrieved a paginated list of event role assignments.
     */
    public ListEventRoleAssignmentResponse withEventRoleAssignmentsPaginatedResponse(@Nullable EventRoleAssignmentsPaginatedResponse eventRoleAssignmentsPaginatedResponse) {
        this.eventRoleAssignmentsPaginatedResponse = eventRoleAssignmentsPaginatedResponse;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListEventRoleAssignmentResponse other = (ListEventRoleAssignmentResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.eventRoleAssignmentsPaginatedResponse, other.eventRoleAssignmentsPaginatedResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            eventRoleAssignmentsPaginatedResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListEventRoleAssignmentResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "eventRoleAssignmentsPaginatedResponse", eventRoleAssignmentsPaginatedResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private EventRoleAssignmentsPaginatedResponse eventRoleAssignmentsPaginatedResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * Successfully retrieved a paginated list of event role assignments.
         */
        public Builder eventRoleAssignmentsPaginatedResponse(@Nullable EventRoleAssignmentsPaginatedResponse eventRoleAssignmentsPaginatedResponse) {
            this.eventRoleAssignmentsPaginatedResponse = eventRoleAssignmentsPaginatedResponse;
            return this;
        }

        public ListEventRoleAssignmentResponse build() {
            return new ListEventRoleAssignmentResponse(
                contentType, statusCode, rawResponse,
                eventRoleAssignmentsPaginatedResponse);
        }

    }
}
