/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import com.cvent.utils.LazySingletonValue;
import com.cvent.utils.SpeakeasyMetadata;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

public class ListContactsRequest {
    /**
     * Used to query records that have been added or updated after this time point. Default to the
     * beginning of time of the data store.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=after")
    private OffsetDateTime after;

    /**
     * Used to query records that have been added or updated before this time point.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=before")
    private OffsetDateTime before;

    /**
     * The maximum number of records to return per page.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    private Long limit;

    /**
     * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
     * This will override any other pageable parameters provided.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    private String token;

    /**
     * A filter query string narrows search results and supports the combination of logical and comparison
     * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
     * There are eight comparison types that can be used in filter expressions:
     * * equal: eq
     * * not equal: ne
     * * greater than: gt
     * * greater or equal: ge
     * * less than: lt
     * * less than or equal: le
     * * starts with: sw
     * * contains a value: contains
     *
     * <p>The following fields are filterable:
     * * id (eq|ne)
     * * sourceId (eq|ne)
     * * firstName (eq|ne|contains)
     * * lastName (eq|ne|contains)
     * * email (eq|ne|contains)
     * * ccEmail (eq|ne)
     * * company (eq|ne)
     * * type.id (eq|ne)
     * * nickname (eq|ne)
     * * title (eq|ne)
     * * workPhone (eq|ne)
     * * middleName (eq|ne)
     * * mobilePhone (eq|ne)
     * * homeFax (eq|ne)
     * * designation (eq|ne)
     * * homePhone (eq|ne)
     * * pager (eq|ne)
     * * workFax (eq|ne)
     * * lastModifiedBy (eq|ne)
     * * lastModified (eq|ne|lt|le|gt|ge)
     * * created (eq|ne|lt|le|gt|ge)
     * * createdBy (eq|ne)
     * * workAddress.address1 (eq|ne)
     * * workAddress.address2 (eq|ne)
     * * workAddress.address3 (eq|ne)
     * * workAddress.city (eq|ne)
     * * workAddress.country (eq|ne)
     * * homeAddress.address1 (eq|ne)
     * * homeAddress.address2 (eq|ne)
     * * homeAddress.address3 (eq|ne)
     * * homeAddress.city (eq|ne)
     * * homeAddress.country (eq|ne)
     * * deleted (eq|ne) - This filters for deleted contacts. To retrieve purged contacts, see the
     * `includePurged` parameter.
     * * customField.{uuid of custom field} (eq|ne|lt|le|gt|ge|sw|contains)
     * * optOut.optedOut (eq|ne)
     *
     * <p>The following operators are available:
     * * and
     * * or
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")
    private String filter;

    @JsonCreator
    public ListContactsRequest(
            @Nullable OffsetDateTime after,
            @Nullable OffsetDateTime before,
            @Nullable Long limit,
            @Nullable String token,
            @Nullable String filter) {
        this.after = after;
        this.before = before;
        this.limit = Optional.ofNullable(limit).orElse(Builder._SINGLETON_VALUE_Limit.value());
        this.token = token;
        this.filter = filter;
    }

    public ListContactsRequest() {
        this(null, null, null, null, null);
    }

    /**
     * Used to query records that have been added or updated after this time point. Default to the
     * beginning of time of the data store.
     */
    public Optional<OffsetDateTime> after() {
        return Optional.ofNullable(this.after);
    }

    /**
     * Used to query records that have been added or updated before this time point.
     */
    public Optional<OffsetDateTime> before() {
        return Optional.ofNullable(this.before);
    }

    /**
     * The maximum number of records to return per page.
     */
    public Optional<Long> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
     * This will override any other pageable parameters provided.
     */
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }

    /**
     * A filter query string narrows search results and supports the combination of logical and comparison
     * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
     * There are eight comparison types that can be used in filter expressions:
     * * equal: eq
     * * not equal: ne
     * * greater than: gt
     * * greater or equal: ge
     * * less than: lt
     * * less than or equal: le
     * * starts with: sw
     * * contains a value: contains
     *
     * <p>The following fields are filterable:
     * * id (eq|ne)
     * * sourceId (eq|ne)
     * * firstName (eq|ne|contains)
     * * lastName (eq|ne|contains)
     * * email (eq|ne|contains)
     * * ccEmail (eq|ne)
     * * company (eq|ne)
     * * type.id (eq|ne)
     * * nickname (eq|ne)
     * * title (eq|ne)
     * * workPhone (eq|ne)
     * * middleName (eq|ne)
     * * mobilePhone (eq|ne)
     * * homeFax (eq|ne)
     * * designation (eq|ne)
     * * homePhone (eq|ne)
     * * pager (eq|ne)
     * * workFax (eq|ne)
     * * lastModifiedBy (eq|ne)
     * * lastModified (eq|ne|lt|le|gt|ge)
     * * created (eq|ne|lt|le|gt|ge)
     * * createdBy (eq|ne)
     * * workAddress.address1 (eq|ne)
     * * workAddress.address2 (eq|ne)
     * * workAddress.address3 (eq|ne)
     * * workAddress.city (eq|ne)
     * * workAddress.country (eq|ne)
     * * homeAddress.address1 (eq|ne)
     * * homeAddress.address2 (eq|ne)
     * * homeAddress.address3 (eq|ne)
     * * homeAddress.city (eq|ne)
     * * homeAddress.country (eq|ne)
     * * deleted (eq|ne) - This filters for deleted contacts. To retrieve purged contacts, see the
     * `includePurged` parameter.
     * * customField.{uuid of custom field} (eq|ne|lt|le|gt|ge|sw|contains)
     * * optOut.optedOut (eq|ne)
     *
     * <p>The following operators are available:
     * * and
     * * or
     */
    public Optional<String> filter() {
        return Optional.ofNullable(this.filter);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Used to query records that have been added or updated after this time point. Default to the
     * beginning of time of the data store.
     */
    public ListContactsRequest withAfter(@Nullable OffsetDateTime after) {
        this.after = after;
        return this;
    }

    /**
     * Used to query records that have been added or updated before this time point.
     */
    public ListContactsRequest withBefore(@Nullable OffsetDateTime before) {
        this.before = before;
        return this;
    }

    /**
     * The maximum number of records to return per page.
     */
    public ListContactsRequest withLimit(@Nullable Long limit) {
        this.limit = limit;
        return this;
    }

    /**
     * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
     * This will override any other pageable parameters provided.
     */
    public ListContactsRequest withToken(@Nullable String token) {
        this.token = token;
        return this;
    }

    /**
     * A filter query string narrows search results and supports the combination of logical and comparison
     * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
     * There are eight comparison types that can be used in filter expressions:
     * * equal: eq
     * * not equal: ne
     * * greater than: gt
     * * greater or equal: ge
     * * less than: lt
     * * less than or equal: le
     * * starts with: sw
     * * contains a value: contains
     *
     * <p>The following fields are filterable:
     * * id (eq|ne)
     * * sourceId (eq|ne)
     * * firstName (eq|ne|contains)
     * * lastName (eq|ne|contains)
     * * email (eq|ne|contains)
     * * ccEmail (eq|ne)
     * * company (eq|ne)
     * * type.id (eq|ne)
     * * nickname (eq|ne)
     * * title (eq|ne)
     * * workPhone (eq|ne)
     * * middleName (eq|ne)
     * * mobilePhone (eq|ne)
     * * homeFax (eq|ne)
     * * designation (eq|ne)
     * * homePhone (eq|ne)
     * * pager (eq|ne)
     * * workFax (eq|ne)
     * * lastModifiedBy (eq|ne)
     * * lastModified (eq|ne|lt|le|gt|ge)
     * * created (eq|ne|lt|le|gt|ge)
     * * createdBy (eq|ne)
     * * workAddress.address1 (eq|ne)
     * * workAddress.address2 (eq|ne)
     * * workAddress.address3 (eq|ne)
     * * workAddress.city (eq|ne)
     * * workAddress.country (eq|ne)
     * * homeAddress.address1 (eq|ne)
     * * homeAddress.address2 (eq|ne)
     * * homeAddress.address3 (eq|ne)
     * * homeAddress.city (eq|ne)
     * * homeAddress.country (eq|ne)
     * * deleted (eq|ne) - This filters for deleted contacts. To retrieve purged contacts, see the
     * `includePurged` parameter.
     * * customField.{uuid of custom field} (eq|ne|lt|le|gt|ge|sw|contains)
     * * optOut.optedOut (eq|ne)
     *
     * <p>The following operators are available:
     * * and
     * * or
     */
    public ListContactsRequest withFilter(@Nullable String filter) {
        this.filter = filter;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListContactsRequest other = (ListContactsRequest) o;
        return Utils.enhancedDeepEquals(this.after, other.after)
                && Utils.enhancedDeepEquals(this.before, other.before)
                && Utils.enhancedDeepEquals(this.limit, other.limit)
                && Utils.enhancedDeepEquals(this.token, other.token)
                && Utils.enhancedDeepEquals(this.filter, other.filter);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(after, before, limit, token, filter);
    }

    @Override
    public String toString() {
        return Utils.toString(
                ListContactsRequest.class,
                "after",
                after,
                "before",
                before,
                "limit",
                limit,
                "token",
                token,
                "filter",
                filter);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private OffsetDateTime after;

        private OffsetDateTime before;

        private Long limit;

        private String token;

        private String filter;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * Used to query records that have been added or updated after this time point. Default to the
         * beginning of time of the data store.
         */
        public Builder after(@Nullable OffsetDateTime after) {
            this.after = after;
            return this;
        }

        /**
         * Used to query records that have been added or updated before this time point.
         */
        public Builder before(@Nullable OffsetDateTime before) {
            this.before = before;
            return this;
        }

        /**
         * The maximum number of records to return per page.
         */
        public Builder limit(@Nullable Long limit) {
            this.limit = limit;
            return this;
        }

        /**
         * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
         * This will override any other pageable parameters provided.
         */
        public Builder token(@Nullable String token) {
            this.token = token;
            return this;
        }

        /**
         * A filter query string narrows search results and supports the combination of logical and comparison
         * operators. The filter adheres to the pattern filter='field' comparisonType 'value'.
         * There are eight comparison types that can be used in filter expressions:
         * * equal: eq
         * * not equal: ne
         * * greater than: gt
         * * greater or equal: ge
         * * less than: lt
         * * less than or equal: le
         * * starts with: sw
         * * contains a value: contains
         *
         * <p>The following fields are filterable:
         * * id (eq|ne)
         * * sourceId (eq|ne)
         * * firstName (eq|ne|contains)
         * * lastName (eq|ne|contains)
         * * email (eq|ne|contains)
         * * ccEmail (eq|ne)
         * * company (eq|ne)
         * * type.id (eq|ne)
         * * nickname (eq|ne)
         * * title (eq|ne)
         * * workPhone (eq|ne)
         * * middleName (eq|ne)
         * * mobilePhone (eq|ne)
         * * homeFax (eq|ne)
         * * designation (eq|ne)
         * * homePhone (eq|ne)
         * * pager (eq|ne)
         * * workFax (eq|ne)
         * * lastModifiedBy (eq|ne)
         * * lastModified (eq|ne|lt|le|gt|ge)
         * * created (eq|ne|lt|le|gt|ge)
         * * createdBy (eq|ne)
         * * workAddress.address1 (eq|ne)
         * * workAddress.address2 (eq|ne)
         * * workAddress.address3 (eq|ne)
         * * workAddress.city (eq|ne)
         * * workAddress.country (eq|ne)
         * * homeAddress.address1 (eq|ne)
         * * homeAddress.address2 (eq|ne)
         * * homeAddress.address3 (eq|ne)
         * * homeAddress.city (eq|ne)
         * * homeAddress.country (eq|ne)
         * * deleted (eq|ne) - This filters for deleted contacts. To retrieve purged contacts, see the
         * `includePurged` parameter.
         * * customField.{uuid of custom field} (eq|ne|lt|le|gt|ge|sw|contains)
         * * optOut.optedOut (eq|ne)
         *
         * <p>The following operators are available:
         * * and
         * * or
         */
        public Builder filter(@Nullable String filter) {
            this.filter = filter;
            return this;
        }

        public ListContactsRequest build() {
            return new ListContactsRequest(after, before, limit, token, filter);
        }

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Limit =
                new LazySingletonValue<>("limit", "100", new TypeReference<Long>() {});
    }
}
