/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import static com.cvent.operations.Operations.RequestOperation;

import com.cvent.SDKConfiguration;
import com.cvent.operations.PatchContactById;
import com.cvent.utils.Headers;
import com.cvent.utils.Utils;
import jakarta.annotation.Nonnull;

public class PatchContactByIdRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private PatchContactByIdRequest request;

    public PatchContactByIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PatchContactByIdRequestBuilder request(@Nonnull PatchContactByIdRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private PatchContactByIdRequest _buildRequest() {
        return this.request;
    }

    public PatchContactByIdRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
     * Executes the request and returns the response.
     *
     * @return The response from the server.
     */
    public PatchContactByIdResponse call() {
        RequestOperation<PatchContactByIdRequest, PatchContactByIdResponse> operation =
                new PatchContactById.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
