/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations;

import static com.cvent.operations.Operations.RequestOperation;

import com.cvent.SDKConfiguration;
import com.cvent.operations.UpdateAttendee;
import com.cvent.utils.Headers;
import com.cvent.utils.Options;
import com.cvent.utils.RetryConfig;
import com.cvent.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

public class UpdateAttendeeRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private UpdateAttendeeRequest request;
    private final Options.Builder optionsBuilder;

    public UpdateAttendeeRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public UpdateAttendeeRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public UpdateAttendeeRequestBuilder request(@Nonnull UpdateAttendeeRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private UpdateAttendeeRequest _buildRequest() {
        return this.request;
    }

    public UpdateAttendeeRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
     * Executes the request and returns the response.
     *
     * @return The response from the server.
     */
    public UpdateAttendeeResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<UpdateAttendeeRequest, UpdateAttendeeResponse> operation =
                new UpdateAttendee.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
