//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Requests
{
    using Cvent.SDK.Models.Components;
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Threading.Tasks;

    public class GetEventSurveysResponse
    {
        public Func<Task<GetEventSurveysResponse?>>? Next { get; set; }
        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// Successfully retrieved a paginated list of event surveys (id refers to chapter id and parentId is the survey id).
        /// </summary>
        public EventSurveysPaginatedResponse? EventSurveysPaginatedResponse { get; set; }
    }
}