//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Requests
{
    using Cvent.SDK.Utils;
    using System;
    
    public class ListEventDiscountsRequest
    {

        /// <summary>
        /// Unique ID of an event.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The maximum number of records to return per page.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 100;

        /// <summary>
        /// The continuation token returned from a previous class. This must be a valid UUID v4 if provided.<br/>
        /// 
        /// <remarks>
        /// This will override any other pageable parameters provided.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")]
        public string? Token { get; set; }

        /// <summary>
        /// The sort order passed as a parameter, used to control the order of the<br/>
        /// 
        /// <remarks>
        /// search results as a priority ordered list of sorts.<br/>
        /// <br/>
        /// There are two orders:<br/>
        ///   * ascending: ASC<br/>
        ///   * descending: DESC<br/>
        /// <br/>
        /// The following fields are sortable:<br/>
        ///   * name<br/>
        ///   * code<br/>
        ///   * method.type<br/>
        ///   * effectiveTo<br/>
        ///   * effectiveFrom<br/>
        ///   * type<br/>
        ///   * level<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")]
        public string? Sort { get; set; }

        /// <summary>
        /// A filter query string narrows search results and supports the combination of logical and comparison operators.<br/>
        /// 
        /// <remarks>
        /// The filter adheres to the pattern filter=&apos;field&apos; comparisonType &apos;value&apos;.<br/>
        /// <br/>
        /// There are two comparison types that can be used in filter expressions:<br/>
        ///    * equal: eq<br/>
        ///    * includes value(s): in<br/>
        /// <br/>
        /// The following fields are filterable:<br/>
        ///    * id (in)<br/>
        ///    * method.type (eq)<br/>
        ///    * type (eq)<br/>
        ///    * level (eq)<br/>
        /// <br/>
        /// The following operators are available:<br/>
        ///    * and<br/>
        ///    * or<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")]
        public string? Filter { get; set; }

        /// <summary>
        /// Used to query records that have been added or updated before this time point.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=before")]
        public DateTime? Before { get; set; }

        /// <summary>
        /// Used to query records that have been added or updated after this time point. Default to the beginning of time of the data store.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=after")]
        public DateTime? After { get; set; }
    }
}