//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Requests
{
    using Cvent.SDK.Utils;
    using System;

    public class ListDurationsRequest
    {
        /// <summary>
        /// Used to query records that have been added or updated after this time point. Default to the beginning of time of the data store.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=after")]
        public DateTime? After { get; set; }

        /// <summary>
        /// Used to query records that have been added or updated before this time point.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=before")]
        public DateTime? Before { get; set; }

        /// <summary>
        /// The maximum number of attendance duration records returned per page.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 1000;

        /// <summary>
        /// The continuation token returned from a previous class. This must be a valid UUID v4 if provided.<br/>
        /// This will override any other pageable parameters provided.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")]
        public string? Token { get; set; }

        /// <summary>
        /// The sort order passed as a parameter, used to control the order of the<br/>
        /// search results as a priority ordered list of sorts<br/>
        /// <br/>
        /// There are two orders:<br/>
        ///   * ascending: ASC<br/>
        ///   * descending: DESC<br/>
        /// <br/>
        /// The following fields are sortable:<br/>
        ///   * event<br/>
        ///   * session<br/>
        ///   * attendee<br/>
        ///   * type<br/>
        ///   * firstSeen<br/>
        ///   * duration<br/>
        ///   * lastModified - default.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=false,name=sort")]
        public string? Sort { get; set; }

        /// <summary>
        /// A filter string passed in the body of the request, narrows search results and supports the combination of logical and comparison operators.<br/>
        /// The filter adheres to the pattern filter='field' comparisonType 'value'.<br/>
        /// <br/>
        /// There are eight comparison types that can be used in filter expressions:<br/>
        ///   * equal: eq<br/>
        ///   * not equal: ne<br/>
        ///   * greater than: gt<br/>
        ///   * greater or equal: ge<br/>
        ///   * less than: lt<br/>
        ///   * less than or equal: le<br/>
        ///   * starts with: sw<br/>
        ///   * contains a value: contains<br/>
        ///   * includes value(s): in<br/>
        /// <br/>
        /// The following fields are filterable:<br/>
        ///   * id (eq|ne)<br/>
        ///   * event.id (eq|ne|in)<br/>
        ///   * session.id (eq|ne|in)<br/>
        ///   * attendee.id (eq|ne|in)<br/>
        ///   * type (contains|eq|ne|in)<br/>
        ///   * deleted (eq|ne)<br/>
        ///   * firstSeen (eq|ne|lt|le|gt|ge)<br/>
        ///   * lastSeen (eq|ne|lt|le|gt|ge)<br/>
        ///   * duration (eq|ne|lt|le|gt|ge)<br/>
        ///   * created (eq|ne|lt|le|gt|ge)<br/>
        /// <br/>
        /// The following operators are available:<br/>
        ///   * and<br/>
        ///   * or.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")]
        public string? Filter { get; set; }
    }
}