//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Requests
{
    using Cvent.SDK.Utils;
    using System;

    public class ListAttendeeActivitiesRequest
    {
        /// <summary>
        /// Used to query records that have been added or updated after this time point. Default to the beginning of time of the data store.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=after")]
        public DateTime? After { get; set; }

        /// <summary>
        /// Used to query records that have been added or updated before this time point.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=before")]
        public DateTime? Before { get; set; }

        /// <summary>
        /// The maximum number of records to return per page.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 100;

        /// <summary>
        /// The continuation token returned from a previous class. This must be a valid UUID v4 if provided.<br/>
        /// This will override any other pageable parameters provided.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")]
        public string? Token { get; set; }

        /// <summary>
        /// Use filter query parameters to limit results<br/>
        /// to data that matches your criteria. See<br/>
        /// <a href="/docs/rest-api/reference/filters">Filters</a> for details.<br/>
        /// <br/>
        /// Supported fields and operators are listed below:<br/>
        /// <br/>
        /// | Field                | Operators                          |<br/>
        /// |----------------------|------------------------------------|<br/>
        /// | id                   | `eq`, `ne`                         |<br/>
        /// | created              | `eq`, `ne`, `lt`, `le`, `gt`, `ge` |<br/>
        /// | event.id             | `eq`, `ne`                         |<br/>
        /// | attendee.id          | `eq`, `ne`                         |<br/>
        /// | type                 | `eq`, `ne`                         |<br/>
        /// | exhibitor.id         | `eq`, `ne`                         |<br/>
        /// | session.id           | `eq`, `ne`                         |<br/>
        /// | appointment.id       | `eq`, `ne`                         |<br/>
        /// | speaker.id           | `eq`, `ne`                         |<br/>
        /// | data.id              | `eq`, `ne`                         |<br/>
        /// | name                 | `eq`, `ne`                         |<br/>
        /// | externalActivityDate | `eq`, `ne`, `lt`, `le`, `gt`, `ge` |<br/>
        /// | time                 | `eq`, `ne`, `lt`, `le`, `gt`, `ge` |<br/>
        /// <br/>
        /// The following logical operators are supported for combining filters:<br/>
        /// * and<br/>
        /// * or.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")]
        public string? Filter { get; set; }
    }
}