/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exhibitorContentCreateExhibitorWeblink } from "../funcs/exhibitorContentCreateExhibitorWeblink.js";
import { exhibitorContentDeleteExhibitorWeblink } from "../funcs/exhibitorContentDeleteExhibitorWeblink.js";
import { exhibitorContentDisassociateExhibitorFile } from "../funcs/exhibitorContentDisassociateExhibitorFile.js";
import { exhibitorContentGetExhibitorFile } from "../funcs/exhibitorContentGetExhibitorFile.js";
import { exhibitorContentGetExhibitorWeblink } from "../funcs/exhibitorContentGetExhibitorWeblink.js";
import { exhibitorContentListExhibitorFiles } from "../funcs/exhibitorContentListExhibitorFiles.js";
import { exhibitorContentListExhibitorWeblinks } from "../funcs/exhibitorContentListExhibitorWeblinks.js";
import { exhibitorContentUpdateExhibitorFile } from "../funcs/exhibitorContentUpdateExhibitorFile.js";
import { exhibitorContentUpdateExhibitorWeblink } from "../funcs/exhibitorContentUpdateExhibitorWeblink.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ExhibitorContent extends ClientSDK {
  /**
   * List Exhibitor Files
   *
   * @remarks
   * Retrieves a list of files associated with an exhibitor.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async listExhibitorFiles(
    request: operations.ListExhibitorFilesRequest,
    options?: RequestOptions,
  ): Promise<components.FileListResponse> {
    return unwrapAsync(exhibitorContentListExhibitorFiles(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Exhibitor File
   *
   * @remarks
   * Get a single file for an exhibitor.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async getExhibitorFile(
    request: operations.GetExhibitorFileRequest,
    options?: RequestOptions,
  ): Promise<components.ExistingFile> {
    return unwrapAsync(exhibitorContentGetExhibitorFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Associate Exhibitor File
   *
   * @remarks
   * Associate a file to an exhibitor using a file ID taken from the <a href="#operation/uploadFile">file upload</a> endpoint.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async updateExhibitorFile(
    request: operations.UpdateExhibitorFileRequest,
    options?: RequestOptions,
  ): Promise<components.ExistingFile> {
    return unwrapAsync(exhibitorContentUpdateExhibitorFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Disassociate Exhibitor File
   *
   * @remarks
   * Disassociate a single file from an exhibitor.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async disassociateExhibitorFile(
    request: operations.DisassociateExhibitorFileRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(exhibitorContentDisassociateExhibitorFile(
      this,
      request,
      options,
    ));
  }

  /**
   * List Exhibitor Weblinks
   *
   * @remarks
   * Retrieves a list of content weblinks associated with an exhibitor.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async listExhibitorWeblinks(
    request: operations.ListExhibitorWeblinksRequest,
    options?: RequestOptions,
  ): Promise<components.WeblinkListResponse> {
    return unwrapAsync(exhibitorContentListExhibitorWeblinks(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Exhibitor Weblink
   *
   * @remarks
   * Creates a single content weblink for an exhibitor.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async createExhibitorWeblink(
    request: operations.CreateExhibitorWeblinkRequest,
    options?: RequestOptions,
  ): Promise<components.ExistingWeblink> {
    return unwrapAsync(exhibitorContentCreateExhibitorWeblink(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Exhibitor Weblink
   *
   * @remarks
   * Retrieves a single content weblink for an exhibitor.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async getExhibitorWeblink(
    request: operations.GetExhibitorWeblinkRequest,
    options?: RequestOptions,
  ): Promise<components.ExistingWeblink> {
    return unwrapAsync(exhibitorContentGetExhibitorWeblink(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Exhibitor Weblink
   *
   * @remarks
   * Updates content weblink data in an event for a given exhibitor ID.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async updateExhibitorWeblink(
    request: operations.UpdateExhibitorWeblinkRequest,
    options?: RequestOptions,
  ): Promise<components.ExistingWeblink> {
    return unwrapAsync(exhibitorContentUpdateExhibitorWeblink(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Exhibitor Weblink
   *
   * @remarks
   * Deletes a single exhibitor content weblink.
   *
   * @see {@link #oauth2-auth-code-planner-admin} - More about OAuth2 authorization code support for administrators
   */
  async deleteExhibitorWeblink(
    request: operations.DeleteExhibitorWeblinkRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(exhibitorContentDeleteExhibitorWeblink(
      this,
      request,
      options,
    ));
  }
}
