/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent;

import static com.cvent.operations.Operations.AsyncRequestOperation;

import com.cvent.models.operations.AssociateBoothStaffRequest;
import com.cvent.models.operations.DeleteBoothStaffRequest;
import com.cvent.models.operations.GetBoothStaffRequest;
import com.cvent.models.operations.GetExhibitorAdminRequest;
import com.cvent.models.operations.ListBoothStaffRequest;
import com.cvent.models.operations.ListExhibitorAdminsRequest;
import com.cvent.models.operations.PostExhibitorAdminRequest;
import com.cvent.models.operations.UpdateExhibitorAdminRequest;
import com.cvent.models.operations.async.AssociateBoothStaffRequestBuilder;
import com.cvent.models.operations.async.AssociateBoothStaffResponse;
import com.cvent.models.operations.async.DeleteBoothStaffRequestBuilder;
import com.cvent.models.operations.async.DeleteBoothStaffResponse;
import com.cvent.models.operations.async.GetBoothStaffRequestBuilder;
import com.cvent.models.operations.async.GetBoothStaffResponse;
import com.cvent.models.operations.async.GetExhibitorAdminRequestBuilder;
import com.cvent.models.operations.async.GetExhibitorAdminResponse;
import com.cvent.models.operations.async.ListBoothStaffRequestBuilder;
import com.cvent.models.operations.async.ListBoothStaffResponse;
import com.cvent.models.operations.async.ListExhibitorAdminsRequestBuilder;
import com.cvent.models.operations.async.ListExhibitorAdminsResponse;
import com.cvent.models.operations.async.PostExhibitorAdminRequestBuilder;
import com.cvent.models.operations.async.PostExhibitorAdminResponse;
import com.cvent.models.operations.async.UpdateExhibitorAdminRequestBuilder;
import com.cvent.models.operations.async.UpdateExhibitorAdminResponse;
import com.cvent.operations.AssociateBoothStaff;
import com.cvent.operations.DeleteBoothStaff;
import com.cvent.operations.GetBoothStaff;
import com.cvent.operations.GetExhibitorAdmin;
import com.cvent.operations.ListBoothStaff;
import com.cvent.operations.ListExhibitorAdmins;
import com.cvent.operations.PostExhibitorAdmin;
import com.cvent.operations.UpdateExhibitorAdmin;
import com.cvent.utils.Headers;
import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;

/**
 * * **Exhibitor Admin -** Exhibitor Admins are administrators that have access to the exhibitor
 * portal. In the portal, they are able to complete pre-event tasks, manage their team, purchase
 * LeadCapture (if applicable), and download leads. Use this API to get details for existing admins,
 * create new admins, and update admin details.
 *
 * <p>* **Exhibitor Booth Staff -** Exhibitor booth staff is someone that manages the frontline of the
 * exhibitor's booth onsite or virtually. Booth staff needs to be registered for the event in order to
 * be associated with an exhibitor. Use this API to get details for the existing booth staff(s) for a
 * specific exhibitor, associate new booth staff to the exhibitor, and delete the association of a
 * booth staff if required.
 */
public class AsyncExhibitorTeam {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final ExhibitorTeam syncSDK;

    AsyncExhibitorTeam(ExhibitorTeam syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     *
     * @return The sync SDK
     */
    public ExhibitorTeam sync() {
        return syncSDK;
    }

    /**
     * List Exhibitor Admins
     *
     * <p>Retrieves a paginated list of exhibitor admins for an exhibitor within an event.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public ListExhibitorAdminsRequestBuilder listExhibitorAdmins() {
        return new ListExhibitorAdminsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Exhibitor Admins
     *
     * <p>Retrieves a paginated list of exhibitor admins for an exhibitor within an event.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ListExhibitorAdminsResponse>} - The async response
     */
    public CompletableFuture<ListExhibitorAdminsResponse> listExhibitorAdmins(
            @Nonnull ListExhibitorAdminsRequest request) {
        AsyncRequestOperation<ListExhibitorAdminsRequest, ListExhibitorAdminsResponse> operation =
                new ListExhibitorAdmins.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Create Exhibitor Admin
     *
     * <p>Creates an exhibitor admin for the given exhibitor.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public PostExhibitorAdminRequestBuilder postExhibitorAdmin() {
        return new PostExhibitorAdminRequestBuilder(sdkConfiguration);
    }

    /**
     * Create Exhibitor Admin
     *
     * <p>Creates an exhibitor admin for the given exhibitor.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<PostExhibitorAdminResponse>} - The async response
     */
    public CompletableFuture<PostExhibitorAdminResponse> postExhibitorAdmin(
            @Nonnull PostExhibitorAdminRequest request) {
        AsyncRequestOperation<PostExhibitorAdminRequest, PostExhibitorAdminResponse> operation =
                new PostExhibitorAdmin.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Get Exhibitor Admin
     *
     * <p>Gets the details of a single exhibitor admin, such as name or contact email.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public GetExhibitorAdminRequestBuilder getExhibitorAdmin() {
        return new GetExhibitorAdminRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Exhibitor Admin
     *
     * <p>Gets the details of a single exhibitor admin, such as name or contact email.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetExhibitorAdminResponse>} - The async response
     */
    public CompletableFuture<GetExhibitorAdminResponse> getExhibitorAdmin(@Nonnull GetExhibitorAdminRequest request) {
        AsyncRequestOperation<GetExhibitorAdminRequest, GetExhibitorAdminResponse> operation =
                new GetExhibitorAdmin.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Update Exhibitor Admin
     *
     * <p>Updates a single exhibitor admin.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public UpdateExhibitorAdminRequestBuilder updateExhibitorAdmin() {
        return new UpdateExhibitorAdminRequestBuilder(sdkConfiguration);
    }

    /**
     * Update Exhibitor Admin
     *
     * <p>Updates a single exhibitor admin.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<UpdateExhibitorAdminResponse>} - The async response
     */
    public CompletableFuture<UpdateExhibitorAdminResponse> updateExhibitorAdmin(
            @Nonnull UpdateExhibitorAdminRequest request) {
        AsyncRequestOperation<UpdateExhibitorAdminRequest, UpdateExhibitorAdminResponse> operation =
                new UpdateExhibitorAdmin.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * List Booth Staff
     *
     * <p>Gets a list of booth staff members for a given event and exhibitor id.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public ListBoothStaffRequestBuilder listBoothStaff() {
        return new ListBoothStaffRequestBuilder(sdkConfiguration);
    }

    /**
     * List Booth Staff
     *
     * <p>Gets a list of booth staff members for a given event and exhibitor id.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ListBoothStaffResponse>} - The async response
     */
    public CompletableFuture<ListBoothStaffResponse> listBoothStaff(@Nonnull ListBoothStaffRequest request) {
        AsyncRequestOperation<ListBoothStaffRequest, ListBoothStaffResponse> operation =
                new ListBoothStaff.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Create Booth Staff
     *
     * <p>Associates a registered attendee as a booth staff to a specific exhibitor id within an event.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public AssociateBoothStaffRequestBuilder associateBoothStaff() {
        return new AssociateBoothStaffRequestBuilder(sdkConfiguration);
    }

    /**
     * Create Booth Staff
     *
     * <p>Associates a registered attendee as a booth staff to a specific exhibitor id within an event.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AssociateBoothStaffResponse>} - The async response
     */
    public CompletableFuture<AssociateBoothStaffResponse> associateBoothStaff(
            @Nonnull AssociateBoothStaffRequest request) {
        AsyncRequestOperation<AssociateBoothStaffRequest, AssociateBoothStaffResponse> operation =
                new AssociateBoothStaff.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Get Booth Staff member
     *
     * <p>Retrieves the attendee id associated with an exhibitor booth staff member.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public GetBoothStaffRequestBuilder getBoothStaff() {
        return new GetBoothStaffRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Booth Staff member
     *
     * <p>Retrieves the attendee id associated with an exhibitor booth staff member.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetBoothStaffResponse>} - The async response
     */
    public CompletableFuture<GetBoothStaffResponse> getBoothStaff(@Nonnull GetBoothStaffRequest request) {
        AsyncRequestOperation<GetBoothStaffRequest, GetBoothStaffResponse> operation =
                new GetBoothStaff.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Delete Booth Staff member
     *
     * <p>Disassociate a single booth staff member from a single exhibitor.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @return The async call builder
     */
    public DeleteBoothStaffRequestBuilder deleteBoothStaff() {
        return new DeleteBoothStaffRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete Booth Staff member
     *
     * <p>Disassociate a single booth staff member from a single exhibitor.
     *
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<DeleteBoothStaffResponse>} - The async response
     */
    public CompletableFuture<DeleteBoothStaffResponse> deleteBoothStaff(@Nonnull DeleteBoothStaffRequest request) {
        AsyncRequestOperation<DeleteBoothStaffRequest, DeleteBoothStaffResponse> operation =
                new DeleteBoothStaff.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }
}
