/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent;

import static com.cvent.operations.Operations.RequestOperation;

import com.cvent.models.operations.GetEventTableAssignmentsRequest;
import com.cvent.models.operations.GetEventTableAssignmentsRequestBuilder;
import com.cvent.models.operations.GetEventTableAssignmentsResponse;
import com.cvent.models.operations.GetSeatRequest;
import com.cvent.models.operations.GetSeatRequestBuilder;
import com.cvent.models.operations.GetSeatResponse;
import com.cvent.models.operations.GetSeatingRequest;
import com.cvent.models.operations.GetSeatingRequestBuilder;
import com.cvent.models.operations.GetSeatingResponse;
import com.cvent.models.operations.GetTableAssignmentRequest;
import com.cvent.models.operations.GetTableAssignmentRequestBuilder;
import com.cvent.models.operations.GetTableAssignmentResponse;
import com.cvent.models.operations.GetTableRequest;
import com.cvent.models.operations.GetTableRequestBuilder;
import com.cvent.models.operations.GetTableResponse;
import com.cvent.models.operations.ListSeatingRequest;
import com.cvent.models.operations.ListSeatingRequestBuilder;
import com.cvent.models.operations.ListSeatingResponse;
import com.cvent.models.operations.ListSeatsRequest;
import com.cvent.models.operations.ListSeatsRequestBuilder;
import com.cvent.models.operations.ListSeatsResponse;
import com.cvent.models.operations.ListTablesRequest;
import com.cvent.models.operations.ListTablesRequestBuilder;
import com.cvent.models.operations.ListTablesResponse;
import com.cvent.operations.GetEventTableAssignments;
import com.cvent.operations.GetSeat;
import com.cvent.operations.GetSeating;
import com.cvent.operations.GetTable;
import com.cvent.operations.GetTableAssignment;
import com.cvent.operations.ListSeating;
import com.cvent.operations.ListSeats;
import com.cvent.operations.ListTables;
import com.cvent.utils.Headers;
import jakarta.annotation.Nonnull;

/**
 * Seating lets you plan seating at your events by configuring tables and assigning seats to your
 * attendees. The seating APIs allow you to create, update, and delete seating, tables, seats, and
 * seating assignments.
 * * **Seating** - A diagram of tables and seats. Your event can have many seatings.
 * * **Table** - A communal location where chairs are assigned. Each table is assigned to a seating.
 * * **Seat** - Individual seat at a table. Each seat can be assigned to an attendee.
 * * **Assignments** - Seat that is assigned to an attendee.
 */
public class Seating {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSeating asyncSDK;

    Seating(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSeating(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSeating async() {
        return asyncSDK;
    }

    /**
     * List Seating
     * 
     * <p>Get seating details for the given event.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public ListSeatingRequestBuilder listSeating() {
        return new ListSeatingRequestBuilder(sdkConfiguration);
    }

    /**
     * List Seating
     * 
     * <p>Get seating details for the given event.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListSeatingResponse listSeating(@Nonnull ListSeatingRequest request) {
        RequestOperation<ListSeatingRequest, ListSeatingResponse> operation
              = new ListSeating.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List All Seating Assignments
     * 
     * <p>Gets all the table assignments across all the seatings in an event.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public GetEventTableAssignmentsRequestBuilder getEventTableAssignments() {
        return new GetEventTableAssignmentsRequestBuilder(sdkConfiguration);
    }

    /**
     * List All Seating Assignments
     * 
     * <p>Gets all the table assignments across all the seatings in an event.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetEventTableAssignmentsResponse getEventTableAssignments(@Nonnull GetEventTableAssignmentsRequest request) {
        RequestOperation<GetEventTableAssignmentsRequest, GetEventTableAssignmentsResponse> operation
              = new GetEventTableAssignments.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get Seating
     * 
     * <p>Get seating details for the given event by seating ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public GetSeatingRequestBuilder getSeating() {
        return new GetSeatingRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Seating
     * 
     * <p>Get seating details for the given event by seating ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetSeatingResponse getSeating(@Nonnull GetSeatingRequest request) {
        RequestOperation<GetSeatingRequest, GetSeatingResponse> operation
              = new GetSeating.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Seating Assignments
     * 
     * <p>Gets the table assignments for a given seating ID in an event.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public GetTableAssignmentRequestBuilder getTableAssignment() {
        return new GetTableAssignmentRequestBuilder(sdkConfiguration);
    }

    /**
     * List Seating Assignments
     * 
     * <p>Gets the table assignments for a given seating ID in an event.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTableAssignmentResponse getTableAssignment(@Nonnull GetTableAssignmentRequest request) {
        RequestOperation<GetTableAssignmentRequest, GetTableAssignmentResponse> operation
              = new GetTableAssignment.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Tables
     * 
     * <p>Get table details for a given seating.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public ListTablesRequestBuilder listTables() {
        return new ListTablesRequestBuilder(sdkConfiguration);
    }

    /**
     * List Tables
     * 
     * <p>Get table details for a given seating.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListTablesResponse listTables(@Nonnull ListTablesRequest request) {
        RequestOperation<ListTablesRequest, ListTablesResponse> operation
              = new ListTables.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get Table
     * 
     * <p>Get table info for given event by seating ID and table ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public GetTableRequestBuilder getTable() {
        return new GetTableRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Table
     * 
     * <p>Get table info for given event by seating ID and table ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTableResponse getTable(@Nonnull GetTableRequest request) {
        RequestOperation<GetTableRequest, GetTableResponse> operation
              = new GetTable.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Seats
     * 
     * <p>Get seat details for given table ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public ListSeatsRequestBuilder listSeats() {
        return new ListSeatsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Seats
     * 
     * <p>Get seat details for given table ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListSeatsResponse listSeats(@Nonnull ListSeatsRequest request) {
        RequestOperation<ListSeatsRequest, ListSeatsResponse> operation
              = new ListSeats.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get Seat
     * 
     * <p>Get seat info for given event by seating ID, table ID, and seat ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @return The call builder
     */
    public GetSeatRequestBuilder getSeat() {
        return new GetSeatRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Seat
     * 
     * <p>Get seat info for given event by seating ID, table ID, and seat ID.
     * 
     * <p><a href="#oauth2-auth-code-planner-admin">More about OAuth2 authorization code support for administrators</a>
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetSeatResponse getSeat(@Nonnull GetSeatRequest request) {
        RequestOperation<GetSeatRequest, GetSeatResponse> operation
              = new GetSeat.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
