/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.OneOfDeserializer;
import com.cvent.utils.TypedObject;
import com.cvent.utils.Utils;
import com.cvent.utils.Utils.JsonShape;
import com.cvent.utils.Utils.TypeReferenceWithShape;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * ActivityData
 *
 * <p>This is used to denote the type of the attendee activity
 */
@JsonDeserialize(using = ActivityData._Deserializer.class)
public class ActivityData {

    @JsonValue
    private final TypedObject value;

    private ActivityData(TypedObject value) {
        this.value = value;
    }

    public static ActivityData of(AppointmentAccepted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(AppointmentCancelled value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(AppointmentCheckedIn value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(AppointmentCreated value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(AppointmentDeclined value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(AppointmentDenied value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(AppointmentRescheduled value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EmailBounced value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EmailClicked value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EmailOpened value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EmailSent value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EmailUndelivered value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventAttendeeHubVisited value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventAttendeeSubstituted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventBannerLinkClicked value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventCheckedIn value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventCheckedOut value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventCustomCardOpened value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventFeedbackSubmitted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventNoShow value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventPageVisitTracked value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventRegistered value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventRegistrationAbandoned value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventRegistrationCancelled value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventVideoPlayed value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventWaitlisted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ExhibitorDocumentOpened value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ExhibitorSocialLinkOpened value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ExhibitorViewed value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ExhibitorVirtualBoothJoined value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ExhibitorWeblinkOpened value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(LeadInboundCreated value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(LeadQualified value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(LeadScanned value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionCheckedIn value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionCheckedOut value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionEnrolled value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionFeedbackSubmitted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionNoShow value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionPollResponseSubmitted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionQuestionAsked value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionQuestionUpvoted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionUnenrolled value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SessionWaitlisted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SpeakerFeedbackSubmitted value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(SpeakerFileDownloaded value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ActivityDataAppointmentExternal value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ActivityDataEventExternal value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ActivityDataExhibitorExternal value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(ActivityDataSessionExternal value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventAdViewed value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    public static ActivityData of(EventAdClicked value) {
        Utils.checkNotNull(value, "value");
        return new ActivityData(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>() {}));
    }

    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.cvent.models.components.AppointmentAccepted}</li>
     * <li>{@code com.cvent.models.components.AppointmentCancelled}</li>
     * <li>{@code com.cvent.models.components.AppointmentCheckedIn}</li>
     * <li>{@code com.cvent.models.components.AppointmentCreated}</li>
     * <li>{@code com.cvent.models.components.AppointmentDeclined}</li>
     * <li>{@code com.cvent.models.components.AppointmentDenied}</li>
     * <li>{@code com.cvent.models.components.AppointmentRescheduled}</li>
     * <li>{@code com.cvent.models.components.EmailBounced}</li>
     * <li>{@code com.cvent.models.components.EmailClicked}</li>
     * <li>{@code com.cvent.models.components.EmailOpened}</li>
     * <li>{@code com.cvent.models.components.EmailSent}</li>
     * <li>{@code com.cvent.models.components.EmailUndelivered}</li>
     * <li>{@code com.cvent.models.components.EventAttendeeHubVisited}</li>
     * <li>{@code com.cvent.models.components.EventAttendeeSubstituted}</li>
     * <li>{@code com.cvent.models.components.EventBannerLinkClicked}</li>
     * <li>{@code com.cvent.models.components.EventCheckedIn}</li>
     * <li>{@code com.cvent.models.components.EventCheckedOut}</li>
     * <li>{@code com.cvent.models.components.EventCustomCardOpened}</li>
     * <li>{@code com.cvent.models.components.EventFeedbackSubmitted}</li>
     * <li>{@code com.cvent.models.components.EventNoShow}</li>
     * <li>{@code com.cvent.models.components.EventPageVisitTracked}</li>
     * <li>{@code com.cvent.models.components.EventRegistered}</li>
     * <li>{@code com.cvent.models.components.EventRegistrationAbandoned}</li>
     * <li>{@code com.cvent.models.components.EventRegistrationCancelled}</li>
     * <li>{@code com.cvent.models.components.EventVideoPlayed}</li>
     * <li>{@code com.cvent.models.components.EventWaitlisted}</li>
     * <li>{@code com.cvent.models.components.ExhibitorDocumentOpened}</li>
     * <li>{@code com.cvent.models.components.ExhibitorSocialLinkOpened}</li>
     * <li>{@code com.cvent.models.components.ExhibitorViewed}</li>
     * <li>{@code com.cvent.models.components.ExhibitorVirtualBoothJoined}</li>
     * <li>{@code com.cvent.models.components.ExhibitorWeblinkOpened}</li>
     * <li>{@code com.cvent.models.components.LeadInboundCreated}</li>
     * <li>{@code com.cvent.models.components.LeadQualified}</li>
     * <li>{@code com.cvent.models.components.LeadScanned}</li>
     * <li>{@code com.cvent.models.components.SessionCheckedIn}</li>
     * <li>{@code com.cvent.models.components.SessionCheckedOut}</li>
     * <li>{@code com.cvent.models.components.SessionEnrolled}</li>
     * <li>{@code com.cvent.models.components.SessionFeedbackSubmitted}</li>
     * <li>{@code com.cvent.models.components.SessionNoShow}</li>
     * <li>{@code com.cvent.models.components.SessionPollResponseSubmitted}</li>
     * <li>{@code com.cvent.models.components.SessionQuestionAsked}</li>
     * <li>{@code com.cvent.models.components.SessionQuestionUpvoted}</li>
     * <li>{@code com.cvent.models.components.SessionUnenrolled}</li>
     * <li>{@code com.cvent.models.components.SessionWaitlisted}</li>
     * <li>{@code com.cvent.models.components.SpeakerFeedbackSubmitted}</li>
     * <li>{@code com.cvent.models.components.SpeakerFileDownloaded}</li>
     * <li>{@code com.cvent.models.components.ActivityDataAppointmentExternal}</li>
     * <li>{@code com.cvent.models.components.ActivityDataEventExternal}</li>
     * <li>{@code com.cvent.models.components.ActivityDataExhibitorExternal}</li>
     * <li>{@code com.cvent.models.components.ActivityDataSessionExternal}</li>
     * <li>{@code com.cvent.models.components.EventAdViewed}</li>
     * <li>{@code com.cvent.models.components.EventAdClicked}</li>
     * </ul>
     *
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     *
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     *
     * @return value of oneOf type
     **/
    public java.lang.Object value() {
        return value.value();
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActivityData other = (ActivityData) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }

    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<ActivityData> {

        public _Deserializer() {
            super(
                    ActivityData.class,
                    false,
                    TypeReferenceWithShape.of(new TypeReference<AppointmentAccepted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<AppointmentCancelled>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<AppointmentCheckedIn>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<AppointmentCreated>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<AppointmentDeclined>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<AppointmentDenied>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<AppointmentRescheduled>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EmailBounced>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EmailClicked>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EmailOpened>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EmailSent>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EmailUndelivered>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventAttendeeHubVisited>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventAttendeeSubstituted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventBannerLinkClicked>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventCheckedIn>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventCheckedOut>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventCustomCardOpened>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventFeedbackSubmitted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventNoShow>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventPageVisitTracked>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventRegistered>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventRegistrationAbandoned>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventRegistrationCancelled>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventVideoPlayed>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventWaitlisted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ExhibitorDocumentOpened>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ExhibitorSocialLinkOpened>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ExhibitorViewed>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ExhibitorVirtualBoothJoined>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ExhibitorWeblinkOpened>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<LeadInboundCreated>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<LeadQualified>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<LeadScanned>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionCheckedIn>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionCheckedOut>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionEnrolled>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionFeedbackSubmitted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionNoShow>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionPollResponseSubmitted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionQuestionAsked>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionQuestionUpvoted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionUnenrolled>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SessionWaitlisted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SpeakerFeedbackSubmitted>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<SpeakerFileDownloaded>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(
                            new TypeReference<ActivityDataAppointmentExternal>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ActivityDataEventExternal>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ActivityDataExhibitorExternal>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<ActivityDataSessionExternal>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventAdViewed>() {}, JsonShape.DEFAULT),
                    TypeReferenceWithShape.of(new TypeReference<EventAdClicked>() {}, JsonShape.DEFAULT));
        }
    }

    @Override
    public String toString() {
        return Utils.toString(ActivityData.class, "value", value);
    }
}
