/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * AirActualDetail
 * 
 * <p>The response from a request to get the list of air actual for the attendees. This includes the
 * paging object as well as the collection of air actual details.
 */
public class AirActualDetail {
    /**
     * Represents pagination information for a collection of resources.
     */
    @JsonProperty("paging")
    private PagingJson paging;

    /**
     * Collection of air actuals for attendees.
     */
    @JsonProperty("data")
    private List<AirActualDetailResponseJson> data;

    @JsonCreator
    public AirActualDetail(
            @JsonProperty("paging") @Nonnull PagingJson paging,
            @JsonProperty("data") @Nonnull List<AirActualDetailResponseJson> data) {
        this.paging = Optional.ofNullable(paging)
            .orElseThrow(() -> new IllegalArgumentException("paging cannot be null"));
        this.data = Optional.ofNullable(data)
            .orElseThrow(() -> new IllegalArgumentException("data cannot be null"));
    }

    /**
     * Represents pagination information for a collection of resources.
     */
    public PagingJson paging() {
        return this.paging;
    }

    /**
     * Collection of air actuals for attendees.
     */
    public List<AirActualDetailResponseJson> data() {
        return this.data;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Represents pagination information for a collection of resources.
     */
    public AirActualDetail withPaging(@Nonnull PagingJson paging) {
        this.paging = Utils.checkNotNull(paging, "paging");
        return this;
    }


    /**
     * Collection of air actuals for attendees.
     */
    public AirActualDetail withData(@Nonnull List<AirActualDetailResponseJson> data) {
        this.data = Utils.checkNotNull(data, "data");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AirActualDetail other = (AirActualDetail) o;
        return 
            Utils.enhancedDeepEquals(this.paging, other.paging) &&
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            paging, data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AirActualDetail.class,
                "paging", paging,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PagingJson paging;

        private List<AirActualDetailResponseJson> data;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Represents pagination information for a collection of resources.
         */
        public Builder paging(@Nonnull PagingJson paging) {
            this.paging = Utils.checkNotNull(paging, "paging");
            return this;
        }

        /**
         * Collection of air actuals for attendees.
         */
        public Builder data(@Nonnull List<AirActualDetailResponseJson> data) {
            this.data = Utils.checkNotNull(data, "data");
            return this;
        }

        public AirActualDetail build() {
            return new AirActualDetail(
                paging, data);
        }

    }
}
