/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * AttendeeAnswerJsonQuestion
 *
 * <p>The registration question.
 */
public class AttendeeAnswerJsonQuestion {
    /**
     * The ID of the question.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    @JsonCreator
    public AttendeeAnswerJsonQuestion(@JsonProperty("id") @Nullable String id) {
        this.id = id;
    }

    public AttendeeAnswerJsonQuestion() {
        this(null);
    }

    /**
     * The ID of the question.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * The ID of the question.
     */
    public AttendeeAnswerJsonQuestion withId(@Nullable String id) {
        this.id = id;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AttendeeAnswerJsonQuestion other = (AttendeeAnswerJsonQuestion) o;
        return Utils.enhancedDeepEquals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(id);
    }

    @Override
    public String toString() {
        return Utils.toString(AttendeeAnswerJsonQuestion.class, "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String id;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * The ID of the question.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public AttendeeAnswerJsonQuestion build() {
            return new AttendeeAnswerJsonQuestion(id);
        }
    }
}
