/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * AttendeeUpdateRegistrationType
 * 
 * <p>The attendee's registration type.
 */
public class AttendeeUpdateRegistrationType {
    /**
     * The ID of the registration type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    @JsonCreator
    public AttendeeUpdateRegistrationType(
            @JsonProperty("id") @Nullable String id) {
        this.id = id;
    }
    
    public AttendeeUpdateRegistrationType() {
        this(null);
    }

    /**
     * The ID of the registration type.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the registration type.
     */
    public AttendeeUpdateRegistrationType withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AttendeeUpdateRegistrationType other = (AttendeeUpdateRegistrationType) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AttendeeUpdateRegistrationType.class,
                "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the registration type.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public AttendeeUpdateRegistrationType build() {
            return new AttendeeUpdateRegistrationType(
                id);
        }

    }
}
