/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * BoothStaffRequest
 *
 * <p>A JSON schema representing booth staff.
 */
public class BoothStaffRequest {
    /**
     * A JSON Schema for an Attendee object
     */
    @JsonProperty("attendee")
    private AttendeeJson3 attendee;

    /**
     * The Associated Event.
     */
    @JsonProperty("event")
    private EventJson5 event;

    /**
     * The Associated Exhibitor.
     */
    @JsonProperty("exhibitor")
    private ExhibitorJson exhibitor;

    @JsonCreator
    public BoothStaffRequest(
            @JsonProperty("attendee") @Nonnull AttendeeJson3 attendee,
            @JsonProperty("event") @Nonnull EventJson5 event,
            @JsonProperty("exhibitor") @Nonnull ExhibitorJson exhibitor) {
        this.attendee = Optional.ofNullable(attendee)
                .orElseThrow(() -> new IllegalArgumentException("attendee cannot be null"));
        this.event = Optional.ofNullable(event).orElseThrow(() -> new IllegalArgumentException("event cannot be null"));
        this.exhibitor = Optional.ofNullable(exhibitor)
                .orElseThrow(() -> new IllegalArgumentException("exhibitor cannot be null"));
    }

    /**
     * A JSON Schema for an Attendee object
     */
    public AttendeeJson3 attendee() {
        return this.attendee;
    }

    /**
     * The Associated Event.
     */
    public EventJson5 event() {
        return this.event;
    }

    /**
     * The Associated Exhibitor.
     */
    public ExhibitorJson exhibitor() {
        return this.exhibitor;
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * A JSON Schema for an Attendee object
     */
    public BoothStaffRequest withAttendee(@Nonnull AttendeeJson3 attendee) {
        this.attendee = Utils.checkNotNull(attendee, "attendee");
        return this;
    }

    /**
     * The Associated Event.
     */
    public BoothStaffRequest withEvent(@Nonnull EventJson5 event) {
        this.event = Utils.checkNotNull(event, "event");
        return this;
    }

    /**
     * The Associated Exhibitor.
     */
    public BoothStaffRequest withExhibitor(@Nonnull ExhibitorJson exhibitor) {
        this.exhibitor = Utils.checkNotNull(exhibitor, "exhibitor");
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BoothStaffRequest other = (BoothStaffRequest) o;
        return Utils.enhancedDeepEquals(this.attendee, other.attendee)
                && Utils.enhancedDeepEquals(this.event, other.event)
                && Utils.enhancedDeepEquals(this.exhibitor, other.exhibitor);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(attendee, event, exhibitor);
    }

    @Override
    public String toString() {
        return Utils.toString(BoothStaffRequest.class, "attendee", attendee, "event", event, "exhibitor", exhibitor);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private AttendeeJson3 attendee;

        private EventJson5 event;

        private ExhibitorJson exhibitor;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * A JSON Schema for an Attendee object
         */
        public Builder attendee(@Nonnull AttendeeJson3 attendee) {
            this.attendee = Utils.checkNotNull(attendee, "attendee");
            return this;
        }

        /**
         * The Associated Event.
         */
        public Builder event(@Nonnull EventJson5 event) {
            this.event = Utils.checkNotNull(event, "event");
            return this;
        }

        /**
         * The Associated Exhibitor.
         */
        public Builder exhibitor(@Nonnull ExhibitorJson exhibitor) {
            this.exhibitor = Utils.checkNotNull(exhibitor, "exhibitor");
            return this;
        }

        public BoothStaffRequest build() {
            return new BoothStaffRequest(attendee, event, exhibitor);
        }
    }
}
