/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ContactTypeJson
 *
 * <p>The contact types used for the proposal.
 */
public enum ContactTypeJson {
    PRIMARY("PRIMARY"),
    SECONDARY("SECONDARY");

    @JsonValue
    private final String value;

    ContactTypeJson(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static Optional<ContactTypeJson> fromValue(String value) {
        for (ContactTypeJson o : ContactTypeJson.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
