/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.time.LocalDate;
import java.util.Optional;

/**
 * ContactCreateRequestJson
 *
 * <p>This entity is used to represent a single item that is posted for a contact create
 */
public class ContactCreateRequestJson {
    /**
     * The first name of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    private String firstName;

    /**
     * The last name of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastName")
    private String lastName;

    /**
     * The middle name of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("middleName")
    private String middleName;

    /**
     * The nickname of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nickname")
    private String nickname;

    /**
     * The email address of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    private String email;

    /**
     * An alternate email address of the contact that can be cc'd on email communications.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ccEmail")
    private String ccEmail;

    /**
     * The gender of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("gender")
    private GenderJson gender;

    /**
     * The company/organization the contact belongs to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company")
    private String company;

    /**
     * The designation of the contact, typically an award or credential.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("designation")
    private String designation;

    /**
     * The job title of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private String title;

    /**
     * Contains details related to the attendee's contact type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private AttendeeContactTypeJsonInput type;

    /**
     * The type of address.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("primaryAddressType")
    private AddressTypeJson primaryAddressType;

    /**
     * Contact address details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("homeAddress")
    private AddressJsonInput homeAddress;

    /**
     * The phone number of the contact at their place of residence.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("homePhone")
    private String homePhone;

    /**
     * The fax number of the contact at their place of residence.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("homeFax")
    private String homeFax;

    /**
     * Contact address details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workAddress")
    private AddressJsonInput workAddress;

    /**
     * The phone number of the contact at their place of work.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workPhone")
    private String workPhone;

    /**
     * The fax number of the contact at their place of work.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workFax")
    private String workFax;

    /**
     * This is a ID for the contact in an external system. NOTE: This value is expected to be unique for
     * each contact within an account. Consider adding the external system name as part of the ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sourceId")
    private String sourceId;

    /**
     * The contact's mobile phone number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mobilePhone")
    private String mobilePhone;

    /**
     * Denotes what is traditionally a title of an individual.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prefix")
    private String prefix;

    /**
     * The pager number of the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pager")
    private String pager;

    /**
     * Details of an opt-out for a Contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("optOut")
    private OptOutJsonInput optOut;

    /**
     * Unique 10-digit identification number issued by the Centers for Medicare and Medicaid Services for
     * health care providers in the United States.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("npi")
    private String npi;

    /**
     * Collection of social media links for the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("_links")
    private ContactLinksJsonInput links;

    /**
     * The date of birth of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dateOfBirth")
    private LocalDate dateOfBirth;

    /**
     * The passport number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively. This field has been deprecated. Instead, use
     * the passport.number field.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("passportNumber")
    @Deprecated
    private String passportNumber;

    /**
     * This entity represents a contact's passport information.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("passport")
    private PassportJsonInput passport;

    /**
     * The social security number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("socialSecurityNumber")
    private String socialSecurityNumber;

    /**
     * The national identification number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nationalIdentificationNumber")
    private String nationalIdentificationNumber;

    /**
     * The headline of the contact's profile, which summarizes their professional experience and qualities.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("headline")
    private String headline;

    /**
     * A contact's personal website URL.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("personalWebsite")
    private String personalWebsite;

    /**
     * A contact's biographical writeup.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("biography")
    private String biography;

    /**
     * Represents the preferred pronouns of a contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pronouns")
    private String pronouns;

    /**
     * ID of the parent contact, applicable with contact snapshot. This field has been deprecated. If the
     * event has contact snapshot enabled, snapshot will be automatically created through the Add attendees
     * API.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parentId")
    @Deprecated
    private String parentId;

    /**
     * Event ID
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event")
    @Deprecated
    private ContactCreateRequestJsonEvent event;

    @JsonCreator
    public ContactCreateRequestJson(
            @JsonProperty("firstName") @Nullable String firstName,
            @JsonProperty("lastName") @Nullable String lastName,
            @JsonProperty("middleName") @Nullable String middleName,
            @JsonProperty("nickname") @Nullable String nickname,
            @JsonProperty("email") @Nullable String email,
            @JsonProperty("ccEmail") @Nullable String ccEmail,
            @JsonProperty("gender") @Nullable GenderJson gender,
            @JsonProperty("company") @Nullable String company,
            @JsonProperty("designation") @Nullable String designation,
            @JsonProperty("title") @Nullable String title,
            @JsonProperty("type") @Nullable AttendeeContactTypeJsonInput type,
            @JsonProperty("primaryAddressType") @Nullable AddressTypeJson primaryAddressType,
            @JsonProperty("homeAddress") @Nullable AddressJsonInput homeAddress,
            @JsonProperty("homePhone") @Nullable String homePhone,
            @JsonProperty("homeFax") @Nullable String homeFax,
            @JsonProperty("workAddress") @Nullable AddressJsonInput workAddress,
            @JsonProperty("workPhone") @Nullable String workPhone,
            @JsonProperty("workFax") @Nullable String workFax,
            @JsonProperty("sourceId") @Nullable String sourceId,
            @JsonProperty("mobilePhone") @Nullable String mobilePhone,
            @JsonProperty("prefix") @Nullable String prefix,
            @JsonProperty("pager") @Nullable String pager,
            @JsonProperty("optOut") @Nullable OptOutJsonInput optOut,
            @JsonProperty("npi") @Nullable String npi,
            @JsonProperty("_links") @Nullable ContactLinksJsonInput links,
            @JsonProperty("dateOfBirth") @Nullable LocalDate dateOfBirth,
            @JsonProperty("passportNumber") @Nullable String passportNumber,
            @JsonProperty("passport") @Nullable PassportJsonInput passport,
            @JsonProperty("socialSecurityNumber") @Nullable String socialSecurityNumber,
            @JsonProperty("nationalIdentificationNumber") @Nullable String nationalIdentificationNumber,
            @JsonProperty("headline") @Nullable String headline,
            @JsonProperty("personalWebsite") @Nullable String personalWebsite,
            @JsonProperty("biography") @Nullable String biography,
            @JsonProperty("pronouns") @Nullable String pronouns,
            @JsonProperty("parentId") @Nullable String parentId,
            @JsonProperty("event") @Nullable ContactCreateRequestJsonEvent event) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
        this.nickname = nickname;
        this.email = email;
        this.ccEmail = ccEmail;
        this.gender = gender;
        this.company = company;
        this.designation = designation;
        this.title = title;
        this.type = type;
        this.primaryAddressType = primaryAddressType;
        this.homeAddress = homeAddress;
        this.homePhone = homePhone;
        this.homeFax = homeFax;
        this.workAddress = workAddress;
        this.workPhone = workPhone;
        this.workFax = workFax;
        this.sourceId = sourceId;
        this.mobilePhone = mobilePhone;
        this.prefix = prefix;
        this.pager = pager;
        this.optOut = optOut;
        this.npi = npi;
        this.links = links;
        this.dateOfBirth = dateOfBirth;
        this.passportNumber = passportNumber;
        this.passport = passport;
        this.socialSecurityNumber = socialSecurityNumber;
        this.nationalIdentificationNumber = nationalIdentificationNumber;
        this.headline = headline;
        this.personalWebsite = personalWebsite;
        this.biography = biography;
        this.pronouns = pronouns;
        this.parentId = parentId;
        this.event = event;
    }

    public ContactCreateRequestJson() {
        this(
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    /**
     * The first name of the contact.
     */
    public Optional<String> firstName() {
        return Optional.ofNullable(this.firstName);
    }

    /**
     * The last name of the contact.
     */
    public Optional<String> lastName() {
        return Optional.ofNullable(this.lastName);
    }

    /**
     * The middle name of the contact.
     */
    public Optional<String> middleName() {
        return Optional.ofNullable(this.middleName);
    }

    /**
     * The nickname of the contact.
     */
    public Optional<String> nickname() {
        return Optional.ofNullable(this.nickname);
    }

    /**
     * The email address of the contact.
     */
    public Optional<String> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * An alternate email address of the contact that can be cc'd on email communications.
     */
    public Optional<String> ccEmail() {
        return Optional.ofNullable(this.ccEmail);
    }

    /**
     * The gender of the contact.
     */
    public Optional<GenderJson> gender() {
        return Optional.ofNullable(this.gender);
    }

    /**
     * The company/organization the contact belongs to.
     */
    public Optional<String> company() {
        return Optional.ofNullable(this.company);
    }

    /**
     * The designation of the contact, typically an award or credential.
     */
    public Optional<String> designation() {
        return Optional.ofNullable(this.designation);
    }

    /**
     * The job title of the contact.
     */
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * Contains details related to the attendee's contact type.
     */
    public Optional<AttendeeContactTypeJsonInput> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * The type of address.
     */
    public Optional<AddressTypeJson> primaryAddressType() {
        return Optional.ofNullable(this.primaryAddressType);
    }

    /**
     * Contact address details.
     */
    public Optional<AddressJsonInput> homeAddress() {
        return Optional.ofNullable(this.homeAddress);
    }

    /**
     * The phone number of the contact at their place of residence.
     */
    public Optional<String> homePhone() {
        return Optional.ofNullable(this.homePhone);
    }

    /**
     * The fax number of the contact at their place of residence.
     */
    public Optional<String> homeFax() {
        return Optional.ofNullable(this.homeFax);
    }

    /**
     * Contact address details.
     */
    public Optional<AddressJsonInput> workAddress() {
        return Optional.ofNullable(this.workAddress);
    }

    /**
     * The phone number of the contact at their place of work.
     */
    public Optional<String> workPhone() {
        return Optional.ofNullable(this.workPhone);
    }

    /**
     * The fax number of the contact at their place of work.
     */
    public Optional<String> workFax() {
        return Optional.ofNullable(this.workFax);
    }

    /**
     * This is a ID for the contact in an external system. NOTE: This value is expected to be unique for
     * each contact within an account. Consider adding the external system name as part of the ID.
     */
    public Optional<String> sourceId() {
        return Optional.ofNullable(this.sourceId);
    }

    /**
     * The contact's mobile phone number.
     */
    public Optional<String> mobilePhone() {
        return Optional.ofNullable(this.mobilePhone);
    }

    /**
     * Denotes what is traditionally a title of an individual.
     */
    public Optional<String> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    /**
     * The pager number of the contact.
     */
    public Optional<String> pager() {
        return Optional.ofNullable(this.pager);
    }

    /**
     * Details of an opt-out for a Contact.
     */
    public Optional<OptOutJsonInput> optOut() {
        return Optional.ofNullable(this.optOut);
    }

    /**
     * Unique 10-digit identification number issued by the Centers for Medicare and Medicaid Services for
     * health care providers in the United States.
     */
    public Optional<String> npi() {
        return Optional.ofNullable(this.npi);
    }

    /**
     * Collection of social media links for the contact.
     */
    public Optional<ContactLinksJsonInput> links() {
        return Optional.ofNullable(this.links);
    }

    /**
     * The date of birth of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    public Optional<LocalDate> dateOfBirth() {
        return Optional.ofNullable(this.dateOfBirth);
    }

    /**
     * The passport number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively. This field has been deprecated. Instead, use
     * the passport.number field.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> passportNumber() {
        return Optional.ofNullable(this.passportNumber);
    }

    /**
     * This entity represents a contact's passport information.
     */
    public Optional<PassportJsonInput> passport() {
        return Optional.ofNullable(this.passport);
    }

    /**
     * The social security number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    public Optional<String> socialSecurityNumber() {
        return Optional.ofNullable(this.socialSecurityNumber);
    }

    /**
     * The national identification number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    public Optional<String> nationalIdentificationNumber() {
        return Optional.ofNullable(this.nationalIdentificationNumber);
    }

    /**
     * The headline of the contact's profile, which summarizes their professional experience and qualities.
     */
    public Optional<String> headline() {
        return Optional.ofNullable(this.headline);
    }

    /**
     * A contact's personal website URL.
     */
    public Optional<String> personalWebsite() {
        return Optional.ofNullable(this.personalWebsite);
    }

    /**
     * A contact's biographical writeup.
     */
    public Optional<String> biography() {
        return Optional.ofNullable(this.biography);
    }

    /**
     * Represents the preferred pronouns of a contact.
     */
    public Optional<String> pronouns() {
        return Optional.ofNullable(this.pronouns);
    }

    /**
     * ID of the parent contact, applicable with contact snapshot. This field has been deprecated. If the
     * event has contact snapshot enabled, snapshot will be automatically created through the Add attendees
     * API.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> parentId() {
        return Optional.ofNullable(this.parentId);
    }

    /**
     * Event ID
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<ContactCreateRequestJsonEvent> event() {
        return Optional.ofNullable(this.event);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * The first name of the contact.
     */
    public ContactCreateRequestJson withFirstName(@Nullable String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * The last name of the contact.
     */
    public ContactCreateRequestJson withLastName(@Nullable String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * The middle name of the contact.
     */
    public ContactCreateRequestJson withMiddleName(@Nullable String middleName) {
        this.middleName = middleName;
        return this;
    }

    /**
     * The nickname of the contact.
     */
    public ContactCreateRequestJson withNickname(@Nullable String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * The email address of the contact.
     */
    public ContactCreateRequestJson withEmail(@Nullable String email) {
        this.email = email;
        return this;
    }

    /**
     * An alternate email address of the contact that can be cc'd on email communications.
     */
    public ContactCreateRequestJson withCcEmail(@Nullable String ccEmail) {
        this.ccEmail = ccEmail;
        return this;
    }

    /**
     * The gender of the contact.
     */
    public ContactCreateRequestJson withGender(@Nullable GenderJson gender) {
        this.gender = gender;
        return this;
    }

    /**
     * The company/organization the contact belongs to.
     */
    public ContactCreateRequestJson withCompany(@Nullable String company) {
        this.company = company;
        return this;
    }

    /**
     * The designation of the contact, typically an award or credential.
     */
    public ContactCreateRequestJson withDesignation(@Nullable String designation) {
        this.designation = designation;
        return this;
    }

    /**
     * The job title of the contact.
     */
    public ContactCreateRequestJson withTitle(@Nullable String title) {
        this.title = title;
        return this;
    }

    /**
     * Contains details related to the attendee's contact type.
     */
    public ContactCreateRequestJson withType(@Nullable AttendeeContactTypeJsonInput type) {
        this.type = type;
        return this;
    }

    /**
     * The type of address.
     */
    public ContactCreateRequestJson withPrimaryAddressType(@Nullable AddressTypeJson primaryAddressType) {
        this.primaryAddressType = primaryAddressType;
        return this;
    }

    /**
     * Contact address details.
     */
    public ContactCreateRequestJson withHomeAddress(@Nullable AddressJsonInput homeAddress) {
        this.homeAddress = homeAddress;
        return this;
    }

    /**
     * The phone number of the contact at their place of residence.
     */
    public ContactCreateRequestJson withHomePhone(@Nullable String homePhone) {
        this.homePhone = homePhone;
        return this;
    }

    /**
     * The fax number of the contact at their place of residence.
     */
    public ContactCreateRequestJson withHomeFax(@Nullable String homeFax) {
        this.homeFax = homeFax;
        return this;
    }

    /**
     * Contact address details.
     */
    public ContactCreateRequestJson withWorkAddress(@Nullable AddressJsonInput workAddress) {
        this.workAddress = workAddress;
        return this;
    }

    /**
     * The phone number of the contact at their place of work.
     */
    public ContactCreateRequestJson withWorkPhone(@Nullable String workPhone) {
        this.workPhone = workPhone;
        return this;
    }

    /**
     * The fax number of the contact at their place of work.
     */
    public ContactCreateRequestJson withWorkFax(@Nullable String workFax) {
        this.workFax = workFax;
        return this;
    }

    /**
     * This is a ID for the contact in an external system. NOTE: This value is expected to be unique for
     * each contact within an account. Consider adding the external system name as part of the ID.
     */
    public ContactCreateRequestJson withSourceId(@Nullable String sourceId) {
        this.sourceId = sourceId;
        return this;
    }

    /**
     * The contact's mobile phone number.
     */
    public ContactCreateRequestJson withMobilePhone(@Nullable String mobilePhone) {
        this.mobilePhone = mobilePhone;
        return this;
    }

    /**
     * Denotes what is traditionally a title of an individual.
     */
    public ContactCreateRequestJson withPrefix(@Nullable String prefix) {
        this.prefix = prefix;
        return this;
    }

    /**
     * The pager number of the contact.
     */
    public ContactCreateRequestJson withPager(@Nullable String pager) {
        this.pager = pager;
        return this;
    }

    /**
     * Details of an opt-out for a Contact.
     */
    public ContactCreateRequestJson withOptOut(@Nullable OptOutJsonInput optOut) {
        this.optOut = optOut;
        return this;
    }

    /**
     * Unique 10-digit identification number issued by the Centers for Medicare and Medicaid Services for
     * health care providers in the United States.
     */
    public ContactCreateRequestJson withNpi(@Nullable String npi) {
        this.npi = npi;
        return this;
    }

    /**
     * Collection of social media links for the contact.
     */
    public ContactCreateRequestJson withLinks(@Nullable ContactLinksJsonInput links) {
        this.links = links;
        return this;
    }

    /**
     * The date of birth of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    public ContactCreateRequestJson withDateOfBirth(@Nullable LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }

    /**
     * The passport number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively. This field has been deprecated. Instead, use
     * the passport.number field.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public ContactCreateRequestJson withPassportNumber(@Nullable String passportNumber) {
        this.passportNumber = passportNumber;
        return this;
    }

    /**
     * This entity represents a contact's passport information.
     */
    public ContactCreateRequestJson withPassport(@Nullable PassportJsonInput passport) {
        this.passport = passport;
        return this;
    }

    /**
     * The social security number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    public ContactCreateRequestJson withSocialSecurityNumber(@Nullable String socialSecurityNumber) {
        this.socialSecurityNumber = socialSecurityNumber;
        return this;
    }

    /**
     * The national identification number of the contact.
     *
     * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
     * `event/contacts:write-sensitive` scopes respectively.
     */
    public ContactCreateRequestJson withNationalIdentificationNumber(@Nullable String nationalIdentificationNumber) {
        this.nationalIdentificationNumber = nationalIdentificationNumber;
        return this;
    }

    /**
     * The headline of the contact's profile, which summarizes their professional experience and qualities.
     */
    public ContactCreateRequestJson withHeadline(@Nullable String headline) {
        this.headline = headline;
        return this;
    }

    /**
     * A contact's personal website URL.
     */
    public ContactCreateRequestJson withPersonalWebsite(@Nullable String personalWebsite) {
        this.personalWebsite = personalWebsite;
        return this;
    }

    /**
     * A contact's biographical writeup.
     */
    public ContactCreateRequestJson withBiography(@Nullable String biography) {
        this.biography = biography;
        return this;
    }

    /**
     * Represents the preferred pronouns of a contact.
     */
    public ContactCreateRequestJson withPronouns(@Nullable String pronouns) {
        this.pronouns = pronouns;
        return this;
    }

    /**
     * ID of the parent contact, applicable with contact snapshot. This field has been deprecated. If the
     * event has contact snapshot enabled, snapshot will be automatically created through the Add attendees
     * API.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public ContactCreateRequestJson withParentId(@Nullable String parentId) {
        this.parentId = parentId;
        return this;
    }

    /**
     * Event ID
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public ContactCreateRequestJson withEvent(@Nullable ContactCreateRequestJsonEvent event) {
        this.event = event;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContactCreateRequestJson other = (ContactCreateRequestJson) o;
        return Utils.enhancedDeepEquals(this.firstName, other.firstName)
                && Utils.enhancedDeepEquals(this.lastName, other.lastName)
                && Utils.enhancedDeepEquals(this.middleName, other.middleName)
                && Utils.enhancedDeepEquals(this.nickname, other.nickname)
                && Utils.enhancedDeepEquals(this.email, other.email)
                && Utils.enhancedDeepEquals(this.ccEmail, other.ccEmail)
                && Utils.enhancedDeepEquals(this.gender, other.gender)
                && Utils.enhancedDeepEquals(this.company, other.company)
                && Utils.enhancedDeepEquals(this.designation, other.designation)
                && Utils.enhancedDeepEquals(this.title, other.title)
                && Utils.enhancedDeepEquals(this.type, other.type)
                && Utils.enhancedDeepEquals(this.primaryAddressType, other.primaryAddressType)
                && Utils.enhancedDeepEquals(this.homeAddress, other.homeAddress)
                && Utils.enhancedDeepEquals(this.homePhone, other.homePhone)
                && Utils.enhancedDeepEquals(this.homeFax, other.homeFax)
                && Utils.enhancedDeepEquals(this.workAddress, other.workAddress)
                && Utils.enhancedDeepEquals(this.workPhone, other.workPhone)
                && Utils.enhancedDeepEquals(this.workFax, other.workFax)
                && Utils.enhancedDeepEquals(this.sourceId, other.sourceId)
                && Utils.enhancedDeepEquals(this.mobilePhone, other.mobilePhone)
                && Utils.enhancedDeepEquals(this.prefix, other.prefix)
                && Utils.enhancedDeepEquals(this.pager, other.pager)
                && Utils.enhancedDeepEquals(this.optOut, other.optOut)
                && Utils.enhancedDeepEquals(this.npi, other.npi)
                && Utils.enhancedDeepEquals(this.links, other.links)
                && Utils.enhancedDeepEquals(this.dateOfBirth, other.dateOfBirth)
                && Utils.enhancedDeepEquals(this.passportNumber, other.passportNumber)
                && Utils.enhancedDeepEquals(this.passport, other.passport)
                && Utils.enhancedDeepEquals(this.socialSecurityNumber, other.socialSecurityNumber)
                && Utils.enhancedDeepEquals(this.nationalIdentificationNumber, other.nationalIdentificationNumber)
                && Utils.enhancedDeepEquals(this.headline, other.headline)
                && Utils.enhancedDeepEquals(this.personalWebsite, other.personalWebsite)
                && Utils.enhancedDeepEquals(this.biography, other.biography)
                && Utils.enhancedDeepEquals(this.pronouns, other.pronouns)
                && Utils.enhancedDeepEquals(this.parentId, other.parentId)
                && Utils.enhancedDeepEquals(this.event, other.event);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(
                firstName,
                lastName,
                middleName,
                nickname,
                email,
                ccEmail,
                gender,
                company,
                designation,
                title,
                type,
                primaryAddressType,
                homeAddress,
                homePhone,
                homeFax,
                workAddress,
                workPhone,
                workFax,
                sourceId,
                mobilePhone,
                prefix,
                pager,
                optOut,
                npi,
                links,
                dateOfBirth,
                passportNumber,
                passport,
                socialSecurityNumber,
                nationalIdentificationNumber,
                headline,
                personalWebsite,
                biography,
                pronouns,
                parentId,
                event);
    }

    @Override
    public String toString() {
        return Utils.toString(
                ContactCreateRequestJson.class,
                "firstName",
                firstName,
                "lastName",
                lastName,
                "middleName",
                middleName,
                "nickname",
                nickname,
                "email",
                email,
                "ccEmail",
                ccEmail,
                "gender",
                gender,
                "company",
                company,
                "designation",
                designation,
                "title",
                title,
                "type",
                type,
                "primaryAddressType",
                primaryAddressType,
                "homeAddress",
                homeAddress,
                "homePhone",
                homePhone,
                "homeFax",
                homeFax,
                "workAddress",
                workAddress,
                "workPhone",
                workPhone,
                "workFax",
                workFax,
                "sourceId",
                sourceId,
                "mobilePhone",
                mobilePhone,
                "prefix",
                prefix,
                "pager",
                pager,
                "optOut",
                optOut,
                "npi",
                npi,
                "links",
                links,
                "dateOfBirth",
                dateOfBirth,
                "passportNumber",
                passportNumber,
                "passport",
                passport,
                "socialSecurityNumber",
                socialSecurityNumber,
                "nationalIdentificationNumber",
                nationalIdentificationNumber,
                "headline",
                headline,
                "personalWebsite",
                personalWebsite,
                "biography",
                biography,
                "pronouns",
                pronouns,
                "parentId",
                parentId,
                "event",
                event);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String firstName;

        private String lastName;

        private String middleName;

        private String nickname;

        private String email;

        private String ccEmail;

        private GenderJson gender;

        private String company;

        private String designation;

        private String title;

        private AttendeeContactTypeJsonInput type;

        private AddressTypeJson primaryAddressType;

        private AddressJsonInput homeAddress;

        private String homePhone;

        private String homeFax;

        private AddressJsonInput workAddress;

        private String workPhone;

        private String workFax;

        private String sourceId;

        private String mobilePhone;

        private String prefix;

        private String pager;

        private OptOutJsonInput optOut;

        private String npi;

        private ContactLinksJsonInput links;

        private LocalDate dateOfBirth;

        @Deprecated
        private String passportNumber;

        private PassportJsonInput passport;

        private String socialSecurityNumber;

        private String nationalIdentificationNumber;

        private String headline;

        private String personalWebsite;

        private String biography;

        private String pronouns;

        @Deprecated
        private String parentId;

        @Deprecated
        private ContactCreateRequestJsonEvent event;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * The first name of the contact.
         */
        public Builder firstName(@Nullable String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * The last name of the contact.
         */
        public Builder lastName(@Nullable String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * The middle name of the contact.
         */
        public Builder middleName(@Nullable String middleName) {
            this.middleName = middleName;
            return this;
        }

        /**
         * The nickname of the contact.
         */
        public Builder nickname(@Nullable String nickname) {
            this.nickname = nickname;
            return this;
        }

        /**
         * The email address of the contact.
         */
        public Builder email(@Nullable String email) {
            this.email = email;
            return this;
        }

        /**
         * An alternate email address of the contact that can be cc'd on email communications.
         */
        public Builder ccEmail(@Nullable String ccEmail) {
            this.ccEmail = ccEmail;
            return this;
        }

        /**
         * The gender of the contact.
         */
        public Builder gender(@Nullable GenderJson gender) {
            this.gender = gender;
            return this;
        }

        /**
         * The company/organization the contact belongs to.
         */
        public Builder company(@Nullable String company) {
            this.company = company;
            return this;
        }

        /**
         * The designation of the contact, typically an award or credential.
         */
        public Builder designation(@Nullable String designation) {
            this.designation = designation;
            return this;
        }

        /**
         * The job title of the contact.
         */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /**
         * Contains details related to the attendee's contact type.
         */
        public Builder type(@Nullable AttendeeContactTypeJsonInput type) {
            this.type = type;
            return this;
        }

        /**
         * The type of address.
         */
        public Builder primaryAddressType(@Nullable AddressTypeJson primaryAddressType) {
            this.primaryAddressType = primaryAddressType;
            return this;
        }

        /**
         * Contact address details.
         */
        public Builder homeAddress(@Nullable AddressJsonInput homeAddress) {
            this.homeAddress = homeAddress;
            return this;
        }

        /**
         * The phone number of the contact at their place of residence.
         */
        public Builder homePhone(@Nullable String homePhone) {
            this.homePhone = homePhone;
            return this;
        }

        /**
         * The fax number of the contact at their place of residence.
         */
        public Builder homeFax(@Nullable String homeFax) {
            this.homeFax = homeFax;
            return this;
        }

        /**
         * Contact address details.
         */
        public Builder workAddress(@Nullable AddressJsonInput workAddress) {
            this.workAddress = workAddress;
            return this;
        }

        /**
         * The phone number of the contact at their place of work.
         */
        public Builder workPhone(@Nullable String workPhone) {
            this.workPhone = workPhone;
            return this;
        }

        /**
         * The fax number of the contact at their place of work.
         */
        public Builder workFax(@Nullable String workFax) {
            this.workFax = workFax;
            return this;
        }

        /**
         * This is a ID for the contact in an external system. NOTE: This value is expected to be unique for
         * each contact within an account. Consider adding the external system name as part of the ID.
         */
        public Builder sourceId(@Nullable String sourceId) {
            this.sourceId = sourceId;
            return this;
        }

        /**
         * The contact's mobile phone number.
         */
        public Builder mobilePhone(@Nullable String mobilePhone) {
            this.mobilePhone = mobilePhone;
            return this;
        }

        /**
         * Denotes what is traditionally a title of an individual.
         */
        public Builder prefix(@Nullable String prefix) {
            this.prefix = prefix;
            return this;
        }

        /**
         * The pager number of the contact.
         */
        public Builder pager(@Nullable String pager) {
            this.pager = pager;
            return this;
        }

        /**
         * Details of an opt-out for a Contact.
         */
        public Builder optOut(@Nullable OptOutJsonInput optOut) {
            this.optOut = optOut;
            return this;
        }

        /**
         * Unique 10-digit identification number issued by the Centers for Medicare and Medicaid Services for
         * health care providers in the United States.
         */
        public Builder npi(@Nullable String npi) {
            this.npi = npi;
            return this;
        }

        /**
         * Collection of social media links for the contact.
         */
        public Builder links(@Nullable ContactLinksJsonInput links) {
            this.links = links;
            return this;
        }

        /**
         * The date of birth of the contact.
         *
         * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
         * `event/contacts:write-sensitive` scopes respectively.
         */
        public Builder dateOfBirth(@Nullable LocalDate dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        /**
         * The passport number of the contact.
         *
         * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
         * `event/contacts:write-sensitive` scopes respectively. This field has been deprecated. Instead, use
         * the passport.number field.
         *
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder passportNumber(@Nullable String passportNumber) {
            this.passportNumber = passportNumber;
            return this;
        }

        /**
         * This entity represents a contact's passport information.
         */
        public Builder passport(@Nullable PassportJsonInput passport) {
            this.passport = passport;
            return this;
        }

        /**
         * The social security number of the contact.
         *
         * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
         * `event/contacts:write-sensitive` scopes respectively.
         */
        public Builder socialSecurityNumber(@Nullable String socialSecurityNumber) {
            this.socialSecurityNumber = socialSecurityNumber;
            return this;
        }

        /**
         * The national identification number of the contact.
         *
         * <p>Reading and writing of this field require the `event/contacts:read-sensitive` and
         * `event/contacts:write-sensitive` scopes respectively.
         */
        public Builder nationalIdentificationNumber(@Nullable String nationalIdentificationNumber) {
            this.nationalIdentificationNumber = nationalIdentificationNumber;
            return this;
        }

        /**
         * The headline of the contact's profile, which summarizes their professional experience and qualities.
         */
        public Builder headline(@Nullable String headline) {
            this.headline = headline;
            return this;
        }

        /**
         * A contact's personal website URL.
         */
        public Builder personalWebsite(@Nullable String personalWebsite) {
            this.personalWebsite = personalWebsite;
            return this;
        }

        /**
         * A contact's biographical writeup.
         */
        public Builder biography(@Nullable String biography) {
            this.biography = biography;
            return this;
        }

        /**
         * Represents the preferred pronouns of a contact.
         */
        public Builder pronouns(@Nullable String pronouns) {
            this.pronouns = pronouns;
            return this;
        }

        /**
         * ID of the parent contact, applicable with contact snapshot. This field has been deprecated. If the
         * event has contact snapshot enabled, snapshot will be automatically created through the Add attendees
         * API.
         *
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder parentId(@Nullable String parentId) {
            this.parentId = parentId;
            return this;
        }

        /**
         * Event ID
         *
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder event(@Nullable ContactCreateRequestJsonEvent event) {
            this.event = event;
            return this;
        }

        public ContactCreateRequestJson build() {
            return new ContactCreateRequestJson(
                    firstName,
                    lastName,
                    middleName,
                    nickname,
                    email,
                    ccEmail,
                    gender,
                    company,
                    designation,
                    title,
                    type,
                    primaryAddressType,
                    homeAddress,
                    homePhone,
                    homeFax,
                    workAddress,
                    workPhone,
                    workFax,
                    sourceId,
                    mobilePhone,
                    prefix,
                    pager,
                    optOut,
                    npi,
                    links,
                    dateOfBirth,
                    passportNumber,
                    passport,
                    socialSecurityNumber,
                    nationalIdentificationNumber,
                    headline,
                    personalWebsite,
                    biography,
                    pronouns,
                    parentId,
                    event);
        }
    }
}
