/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * DiscountTypeJson
 *
 * <p>This is used to denote the type of discount
 */
public enum DiscountTypeJson {
    AMOUNT("Amount"),
    PERCENTAGE("Percentage"),
    FLAT_PRICE("FlatPrice");

    @JsonValue
    private final String value;

    DiscountTypeJson(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static Optional<DiscountTypeJson> fromValue(String value) {
        for (DiscountTypeJson o : DiscountTypeJson.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
