/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ExistingVenueFacilityDoubleRate
 *
 * <p>Published rate range for double-occupancy rooms, expressed in the venue's configured currency.
 */
public class ExistingVenueFacilityDoubleRate {
    /**
     * Lowest published rate for a double-occupancy room.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("low")
    private Double low;

    /**
     * Highest published rate for a double-occupancy room.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("high")
    private Double high;

    @JsonCreator
    public ExistingVenueFacilityDoubleRate(
            @JsonProperty("low") @Nullable Double low, @JsonProperty("high") @Nullable Double high) {
        this.low = low;
        this.high = high;
    }

    public ExistingVenueFacilityDoubleRate() {
        this(null, null);
    }

    /**
     * Lowest published rate for a double-occupancy room.
     */
    public Optional<Double> low() {
        return Optional.ofNullable(this.low);
    }

    /**
     * Highest published rate for a double-occupancy room.
     */
    public Optional<Double> high() {
        return Optional.ofNullable(this.high);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Lowest published rate for a double-occupancy room.
     */
    public ExistingVenueFacilityDoubleRate withLow(@Nullable Double low) {
        this.low = low;
        return this;
    }

    /**
     * Highest published rate for a double-occupancy room.
     */
    public ExistingVenueFacilityDoubleRate withHigh(@Nullable Double high) {
        this.high = high;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExistingVenueFacilityDoubleRate other = (ExistingVenueFacilityDoubleRate) o;
        return Utils.enhancedDeepEquals(this.low, other.low) && Utils.enhancedDeepEquals(this.high, other.high);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(low, high);
    }

    @Override
    public String toString() {
        return Utils.toString(ExistingVenueFacilityDoubleRate.class, "low", low, "high", high);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private Double low;

        private Double high;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * Lowest published rate for a double-occupancy room.
         */
        public Builder low(@Nullable Double low) {
            this.low = low;
            return this;
        }

        /**
         * Highest published rate for a double-occupancy room.
         */
        public Builder high(@Nullable Double high) {
            this.high = high;
            return this;
        }

        public ExistingVenueFacilityDoubleRate build() {
            return new ExistingVenueFacilityDoubleRate(low, high);
        }
    }
}
