/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ExternalActivityInput
 * 
 * <p>An external attendee activity.
 */
public class ExternalActivityInput {
    /**
     * The reference to the related entity. Contains only the ID of the related entity.
     */
    @JsonProperty("attendee")
    private UuidJson attendee;

    /**
     * Details for an event activity.
     */
    @JsonProperty("event")
    private EventActivityDetailsJsonInput event;

    /**
     * Name for the external attendee activity.
     */
    @JsonProperty("name")
    private String name;

    /**
     * This is used to denote the type of the external attendee activity.
     */
    @JsonProperty("type")
    private ExternalActivityTypeJson type;

    /**
     * This is used to denote the type of the external attendee activity.
     */
    @JsonProperty("data")
    private ExternalActivityDataJson data;

    @JsonCreator
    public ExternalActivityInput(
            @JsonProperty("attendee") @Nonnull UuidJson attendee,
            @JsonProperty("event") @Nonnull EventActivityDetailsJsonInput event,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("type") @Nonnull ExternalActivityTypeJson type,
            @JsonProperty("data") @Nonnull ExternalActivityDataJson data) {
        this.attendee = Optional.ofNullable(attendee)
            .orElseThrow(() -> new IllegalArgumentException("attendee cannot be null"));
        this.event = Optional.ofNullable(event)
            .orElseThrow(() -> new IllegalArgumentException("event cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.data = Optional.ofNullable(data)
            .orElseThrow(() -> new IllegalArgumentException("data cannot be null"));
    }

    /**
     * The reference to the related entity. Contains only the ID of the related entity.
     */
    public UuidJson attendee() {
        return this.attendee;
    }

    /**
     * Details for an event activity.
     */
    public EventActivityDetailsJsonInput event() {
        return this.event;
    }

    /**
     * Name for the external attendee activity.
     */
    public String name() {
        return this.name;
    }

    /**
     * This is used to denote the type of the external attendee activity.
     */
    public ExternalActivityTypeJson type() {
        return this.type;
    }

    /**
     * This is used to denote the type of the external attendee activity.
     */
    public ExternalActivityDataJson data() {
        return this.data;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The reference to the related entity. Contains only the ID of the related entity.
     */
    public ExternalActivityInput withAttendee(@Nonnull UuidJson attendee) {
        this.attendee = Utils.checkNotNull(attendee, "attendee");
        return this;
    }


    /**
     * Details for an event activity.
     */
    public ExternalActivityInput withEvent(@Nonnull EventActivityDetailsJsonInput event) {
        this.event = Utils.checkNotNull(event, "event");
        return this;
    }


    /**
     * Name for the external attendee activity.
     */
    public ExternalActivityInput withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * This is used to denote the type of the external attendee activity.
     */
    public ExternalActivityInput withType(@Nonnull ExternalActivityTypeJson type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * This is used to denote the type of the external attendee activity.
     */
    public ExternalActivityInput withData(@Nonnull ExternalActivityDataJson data) {
        this.data = Utils.checkNotNull(data, "data");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExternalActivityInput other = (ExternalActivityInput) o;
        return 
            Utils.enhancedDeepEquals(this.attendee, other.attendee) &&
            Utils.enhancedDeepEquals(this.event, other.event) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            attendee, event, name,
            type, data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ExternalActivityInput.class,
                "attendee", attendee,
                "event", event,
                "name", name,
                "type", type,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private UuidJson attendee;

        private EventActivityDetailsJsonInput event;

        private String name;

        private ExternalActivityTypeJson type;

        private ExternalActivityDataJson data;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The reference to the related entity. Contains only the ID of the related entity.
         */
        public Builder attendee(@Nonnull UuidJson attendee) {
            this.attendee = Utils.checkNotNull(attendee, "attendee");
            return this;
        }

        /**
         * Details for an event activity.
         */
        public Builder event(@Nonnull EventActivityDetailsJsonInput event) {
            this.event = Utils.checkNotNull(event, "event");
            return this;
        }

        /**
         * Name for the external attendee activity.
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * This is used to denote the type of the external attendee activity.
         */
        public Builder type(@Nonnull ExternalActivityTypeJson type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * This is used to denote the type of the external attendee activity.
         */
        public Builder data(@Nonnull ExternalActivityDataJson data) {
            this.data = Utils.checkNotNull(data, "data");
            return this;
        }

        public ExternalActivityInput build() {
            return new ExternalActivityInput(
                attendee, event, name,
                type, data);
        }

    }
}
