/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * FieldType
 *
 * <p>Determines the required format for a field. `DateTime`: Data is in date-time format. `MultiChoice`:
 * Data is one or more options from a list.
 *
 * <p>`Number`: Data is a number. `SingleChoice`: Data is a a single option from a list. `Text`: Data is
 * free-text input.
 */
public enum FieldType {
    DATE_TIME("DateTime"),
    MULTI_CHOICE("MultiChoice"),
    NUMBER("Number"),
    SINGLE_CHOICE("SingleChoice"),
    TEXT("Text");

    @JsonValue
    private final String value;

    FieldType(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static Optional<FieldType> fromValue(String value) {
        for (FieldType o : FieldType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
