/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * RateTypeJson
 *
 * <p>Rate type.
 */
public enum RateTypeJson {
    FIXED("fixed"),
    DYNAMIC("dynamic"),
    DYNAMICWITHCEILING("dynamicwithceiling");

    @JsonValue
    private final String value;

    RateTypeJson(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static Optional<RateTypeJson> fromValue(String value) {
        for (RateTypeJson o : RateTypeJson.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
