/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ReconciliationStatus
 *
 * <p>This is used to denote the reconciliation status for a transaction.
 */
public enum ReconciliationStatus {
    RECONCILED("Reconciled"),
    NOT_RECONCILED("Not Reconciled");

    @JsonValue
    private final String value;

    ReconciliationStatus(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static Optional<ReconciliationStatus> fromValue(String value) {
        for (ReconciliationStatus o : ReconciliationStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
