/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * RespondedThroughJson
 *
 * <p>Indicates the mode by which a respondent submitted their response.
 *
 * <p>This field contains one of the enumerated, string constants listed below.
 *
 * <p>Enum values:
 *
 * <p>- "Not Responded": Respondent did not provide a response.
 * - "API": Response was submitted via an API.
 * - "Import": Response was created by a bulk import process.
 * - "Mobile" (deprecated): Historically indicated submission from a mobile device. This value is
 * deprecated.
 * - "Desktop" (deprecated): Historically indicated submission from a desktop device. This value is
 * deprecated.
 */
public enum RespondedThroughJson {
    NOT_RESPONDED("Not Responded"),
    API("API"),
    IMPORT("Import"),
    MOBILE("Mobile"),
    DESKTOP("Desktop");

    @JsonValue
    private final String value;

    RespondedThroughJson(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static Optional<RespondedThroughJson> fromValue(String value) {
        for (RespondedThroughJson o : RespondedThroughJson.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
