/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * RfpEvent
 *
 * <p>RFP event details.
 */
public class RfpEvent {
    /**
     * Event details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event")
    private Event12 event;

    /**
     * Name of the event linked with the RFP.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * Location where the contract will be signed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contractSignatureLocation")
    private String contractSignatureLocation;

    /**
     * Destinations under consideration for the event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("destinationsUnderConsideration")
    private String destinationsUnderConsideration;

    /**
     * True indicates that the event is associated with an external meeting request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("externalMeetingRequest")
    private Boolean externalMeetingRequest;

    /**
     * Event type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private EventType1 type;

    /**
     * Space area divisons.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("totalMeetingSpaceRequired")
    private SpaceArea totalMeetingSpaceRequired;

    /**
     * Audio visual requirements.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("audioVisualNeeds")
    private String audioVisualNeeds;

    /**
     * Maximum number of meeting rooms required during the event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("peakMeetingRooms")
    private Long peakMeetingRooms;

    /**
     * True indicates the event dates are flexible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("flexibleDates")
    private Boolean flexibleDates;

    /**
     * True indicates event is a repeat occurrence.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("repeat")
    private Boolean repeat;

    /**
     * Number of in-person attendees per day.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("attendeesPerDay")
    private Long attendeesPerDay;

    /**
     * Reference number for the event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("referenceNumber")
    private String referenceNumber;

    /**
     * Space area divisons.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("largestMeetingSpaceRequired")
    private SpaceArea largestMeetingSpaceRequired;

    /**
     * Unique identifier for meeting request associated with the event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meetingRequestId")
    private String meetingRequestId;

    /**
     * Event format type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("formatType")
    private EventFormatType formatType;

    /**
     * Number of virtual attendees per day.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("virtualAttendeesPerDay")
    private Long virtualAttendeesPerDay;

    /**
     * Total budget amount.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("budget")
    private Double budget;

    /**
     * Budget for rooms rates.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("roomRateBudget")
    private Double roomRateBudget;

    /**
     * Budget for food and beverage.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("foodBeverageBudget")
    private Double foodBeverageBudget;

    @JsonCreator
    public RfpEvent(
            @JsonProperty("event") @Nullable Event12 event,
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("contractSignatureLocation") @Nullable String contractSignatureLocation,
            @JsonProperty("destinationsUnderConsideration") @Nullable String destinationsUnderConsideration,
            @JsonProperty("externalMeetingRequest") @Nullable Boolean externalMeetingRequest,
            @JsonProperty("type") @Nullable EventType1 type,
            @JsonProperty("totalMeetingSpaceRequired") @Nullable SpaceArea totalMeetingSpaceRequired,
            @JsonProperty("audioVisualNeeds") @Nullable String audioVisualNeeds,
            @JsonProperty("peakMeetingRooms") @Nullable Long peakMeetingRooms,
            @JsonProperty("flexibleDates") @Nullable Boolean flexibleDates,
            @JsonProperty("repeat") @Nullable Boolean repeat,
            @JsonProperty("attendeesPerDay") @Nullable Long attendeesPerDay,
            @JsonProperty("referenceNumber") @Nullable String referenceNumber,
            @JsonProperty("largestMeetingSpaceRequired") @Nullable SpaceArea largestMeetingSpaceRequired,
            @JsonProperty("meetingRequestId") @Nullable String meetingRequestId,
            @JsonProperty("formatType") @Nullable EventFormatType formatType,
            @JsonProperty("virtualAttendeesPerDay") @Nullable Long virtualAttendeesPerDay,
            @JsonProperty("budget") @Nullable Double budget,
            @JsonProperty("roomRateBudget") @Nullable Double roomRateBudget,
            @JsonProperty("foodBeverageBudget") @Nullable Double foodBeverageBudget) {
        this.event = event;
        this.name = name;
        this.contractSignatureLocation = contractSignatureLocation;
        this.destinationsUnderConsideration = destinationsUnderConsideration;
        this.externalMeetingRequest = externalMeetingRequest;
        this.type = type;
        this.totalMeetingSpaceRequired = totalMeetingSpaceRequired;
        this.audioVisualNeeds = audioVisualNeeds;
        this.peakMeetingRooms = peakMeetingRooms;
        this.flexibleDates = flexibleDates;
        this.repeat = repeat;
        this.attendeesPerDay = attendeesPerDay;
        this.referenceNumber = referenceNumber;
        this.largestMeetingSpaceRequired = largestMeetingSpaceRequired;
        this.meetingRequestId = meetingRequestId;
        this.formatType = formatType;
        this.virtualAttendeesPerDay = virtualAttendeesPerDay;
        this.budget = budget;
        this.roomRateBudget = roomRateBudget;
        this.foodBeverageBudget = foodBeverageBudget;
    }

    public RfpEvent() {
        this(
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    /**
     * Event details.
     */
    public Optional<Event12> event() {
        return Optional.ofNullable(this.event);
    }

    /**
     * Name of the event linked with the RFP.
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Location where the contract will be signed.
     */
    public Optional<String> contractSignatureLocation() {
        return Optional.ofNullable(this.contractSignatureLocation);
    }

    /**
     * Destinations under consideration for the event.
     */
    public Optional<String> destinationsUnderConsideration() {
        return Optional.ofNullable(this.destinationsUnderConsideration);
    }

    /**
     * True indicates that the event is associated with an external meeting request.
     */
    public Optional<Boolean> externalMeetingRequest() {
        return Optional.ofNullable(this.externalMeetingRequest);
    }

    /**
     * Event type.
     */
    public Optional<EventType1> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * Space area divisons.
     */
    public Optional<SpaceArea> totalMeetingSpaceRequired() {
        return Optional.ofNullable(this.totalMeetingSpaceRequired);
    }

    /**
     * Audio visual requirements.
     */
    public Optional<String> audioVisualNeeds() {
        return Optional.ofNullable(this.audioVisualNeeds);
    }

    /**
     * Maximum number of meeting rooms required during the event.
     */
    public Optional<Long> peakMeetingRooms() {
        return Optional.ofNullable(this.peakMeetingRooms);
    }

    /**
     * True indicates the event dates are flexible.
     */
    public Optional<Boolean> flexibleDates() {
        return Optional.ofNullable(this.flexibleDates);
    }

    /**
     * True indicates event is a repeat occurrence.
     */
    public Optional<Boolean> repeat() {
        return Optional.ofNullable(this.repeat);
    }

    /**
     * Number of in-person attendees per day.
     */
    public Optional<Long> attendeesPerDay() {
        return Optional.ofNullable(this.attendeesPerDay);
    }

    /**
     * Reference number for the event.
     */
    public Optional<String> referenceNumber() {
        return Optional.ofNullable(this.referenceNumber);
    }

    /**
     * Space area divisons.
     */
    public Optional<SpaceArea> largestMeetingSpaceRequired() {
        return Optional.ofNullable(this.largestMeetingSpaceRequired);
    }

    /**
     * Unique identifier for meeting request associated with the event.
     */
    public Optional<String> meetingRequestId() {
        return Optional.ofNullable(this.meetingRequestId);
    }

    /**
     * Event format type.
     */
    public Optional<EventFormatType> formatType() {
        return Optional.ofNullable(this.formatType);
    }

    /**
     * Number of virtual attendees per day.
     */
    public Optional<Long> virtualAttendeesPerDay() {
        return Optional.ofNullable(this.virtualAttendeesPerDay);
    }

    /**
     * Total budget amount.
     */
    public Optional<Double> budget() {
        return Optional.ofNullable(this.budget);
    }

    /**
     * Budget for rooms rates.
     */
    public Optional<Double> roomRateBudget() {
        return Optional.ofNullable(this.roomRateBudget);
    }

    /**
     * Budget for food and beverage.
     */
    public Optional<Double> foodBeverageBudget() {
        return Optional.ofNullable(this.foodBeverageBudget);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Event details.
     */
    public RfpEvent withEvent(@Nullable Event12 event) {
        this.event = event;
        return this;
    }

    /**
     * Name of the event linked with the RFP.
     */
    public RfpEvent withName(@Nullable String name) {
        this.name = name;
        return this;
    }

    /**
     * Location where the contract will be signed.
     */
    public RfpEvent withContractSignatureLocation(@Nullable String contractSignatureLocation) {
        this.contractSignatureLocation = contractSignatureLocation;
        return this;
    }

    /**
     * Destinations under consideration for the event.
     */
    public RfpEvent withDestinationsUnderConsideration(@Nullable String destinationsUnderConsideration) {
        this.destinationsUnderConsideration = destinationsUnderConsideration;
        return this;
    }

    /**
     * True indicates that the event is associated with an external meeting request.
     */
    public RfpEvent withExternalMeetingRequest(@Nullable Boolean externalMeetingRequest) {
        this.externalMeetingRequest = externalMeetingRequest;
        return this;
    }

    /**
     * Event type.
     */
    public RfpEvent withType(@Nullable EventType1 type) {
        this.type = type;
        return this;
    }

    /**
     * Space area divisons.
     */
    public RfpEvent withTotalMeetingSpaceRequired(@Nullable SpaceArea totalMeetingSpaceRequired) {
        this.totalMeetingSpaceRequired = totalMeetingSpaceRequired;
        return this;
    }

    /**
     * Audio visual requirements.
     */
    public RfpEvent withAudioVisualNeeds(@Nullable String audioVisualNeeds) {
        this.audioVisualNeeds = audioVisualNeeds;
        return this;
    }

    /**
     * Maximum number of meeting rooms required during the event.
     */
    public RfpEvent withPeakMeetingRooms(@Nullable Long peakMeetingRooms) {
        this.peakMeetingRooms = peakMeetingRooms;
        return this;
    }

    /**
     * True indicates the event dates are flexible.
     */
    public RfpEvent withFlexibleDates(@Nullable Boolean flexibleDates) {
        this.flexibleDates = flexibleDates;
        return this;
    }

    /**
     * True indicates event is a repeat occurrence.
     */
    public RfpEvent withRepeat(@Nullable Boolean repeat) {
        this.repeat = repeat;
        return this;
    }

    /**
     * Number of in-person attendees per day.
     */
    public RfpEvent withAttendeesPerDay(@Nullable Long attendeesPerDay) {
        this.attendeesPerDay = attendeesPerDay;
        return this;
    }

    /**
     * Reference number for the event.
     */
    public RfpEvent withReferenceNumber(@Nullable String referenceNumber) {
        this.referenceNumber = referenceNumber;
        return this;
    }

    /**
     * Space area divisons.
     */
    public RfpEvent withLargestMeetingSpaceRequired(@Nullable SpaceArea largestMeetingSpaceRequired) {
        this.largestMeetingSpaceRequired = largestMeetingSpaceRequired;
        return this;
    }

    /**
     * Unique identifier for meeting request associated with the event.
     */
    public RfpEvent withMeetingRequestId(@Nullable String meetingRequestId) {
        this.meetingRequestId = meetingRequestId;
        return this;
    }

    /**
     * Event format type.
     */
    public RfpEvent withFormatType(@Nullable EventFormatType formatType) {
        this.formatType = formatType;
        return this;
    }

    /**
     * Number of virtual attendees per day.
     */
    public RfpEvent withVirtualAttendeesPerDay(@Nullable Long virtualAttendeesPerDay) {
        this.virtualAttendeesPerDay = virtualAttendeesPerDay;
        return this;
    }

    /**
     * Total budget amount.
     */
    public RfpEvent withBudget(@Nullable Double budget) {
        this.budget = budget;
        return this;
    }

    /**
     * Budget for rooms rates.
     */
    public RfpEvent withRoomRateBudget(@Nullable Double roomRateBudget) {
        this.roomRateBudget = roomRateBudget;
        return this;
    }

    /**
     * Budget for food and beverage.
     */
    public RfpEvent withFoodBeverageBudget(@Nullable Double foodBeverageBudget) {
        this.foodBeverageBudget = foodBeverageBudget;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RfpEvent other = (RfpEvent) o;
        return Utils.enhancedDeepEquals(this.event, other.event)
                && Utils.enhancedDeepEquals(this.name, other.name)
                && Utils.enhancedDeepEquals(this.contractSignatureLocation, other.contractSignatureLocation)
                && Utils.enhancedDeepEquals(this.destinationsUnderConsideration, other.destinationsUnderConsideration)
                && Utils.enhancedDeepEquals(this.externalMeetingRequest, other.externalMeetingRequest)
                && Utils.enhancedDeepEquals(this.type, other.type)
                && Utils.enhancedDeepEquals(this.totalMeetingSpaceRequired, other.totalMeetingSpaceRequired)
                && Utils.enhancedDeepEquals(this.audioVisualNeeds, other.audioVisualNeeds)
                && Utils.enhancedDeepEquals(this.peakMeetingRooms, other.peakMeetingRooms)
                && Utils.enhancedDeepEquals(this.flexibleDates, other.flexibleDates)
                && Utils.enhancedDeepEquals(this.repeat, other.repeat)
                && Utils.enhancedDeepEquals(this.attendeesPerDay, other.attendeesPerDay)
                && Utils.enhancedDeepEquals(this.referenceNumber, other.referenceNumber)
                && Utils.enhancedDeepEquals(this.largestMeetingSpaceRequired, other.largestMeetingSpaceRequired)
                && Utils.enhancedDeepEquals(this.meetingRequestId, other.meetingRequestId)
                && Utils.enhancedDeepEquals(this.formatType, other.formatType)
                && Utils.enhancedDeepEquals(this.virtualAttendeesPerDay, other.virtualAttendeesPerDay)
                && Utils.enhancedDeepEquals(this.budget, other.budget)
                && Utils.enhancedDeepEquals(this.roomRateBudget, other.roomRateBudget)
                && Utils.enhancedDeepEquals(this.foodBeverageBudget, other.foodBeverageBudget);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(
                event,
                name,
                contractSignatureLocation,
                destinationsUnderConsideration,
                externalMeetingRequest,
                type,
                totalMeetingSpaceRequired,
                audioVisualNeeds,
                peakMeetingRooms,
                flexibleDates,
                repeat,
                attendeesPerDay,
                referenceNumber,
                largestMeetingSpaceRequired,
                meetingRequestId,
                formatType,
                virtualAttendeesPerDay,
                budget,
                roomRateBudget,
                foodBeverageBudget);
    }

    @Override
    public String toString() {
        return Utils.toString(
                RfpEvent.class,
                "event",
                event,
                "name",
                name,
                "contractSignatureLocation",
                contractSignatureLocation,
                "destinationsUnderConsideration",
                destinationsUnderConsideration,
                "externalMeetingRequest",
                externalMeetingRequest,
                "type",
                type,
                "totalMeetingSpaceRequired",
                totalMeetingSpaceRequired,
                "audioVisualNeeds",
                audioVisualNeeds,
                "peakMeetingRooms",
                peakMeetingRooms,
                "flexibleDates",
                flexibleDates,
                "repeat",
                repeat,
                "attendeesPerDay",
                attendeesPerDay,
                "referenceNumber",
                referenceNumber,
                "largestMeetingSpaceRequired",
                largestMeetingSpaceRequired,
                "meetingRequestId",
                meetingRequestId,
                "formatType",
                formatType,
                "virtualAttendeesPerDay",
                virtualAttendeesPerDay,
                "budget",
                budget,
                "roomRateBudget",
                roomRateBudget,
                "foodBeverageBudget",
                foodBeverageBudget);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private Event12 event;

        private String name;

        private String contractSignatureLocation;

        private String destinationsUnderConsideration;

        private Boolean externalMeetingRequest;

        private EventType1 type;

        private SpaceArea totalMeetingSpaceRequired;

        private String audioVisualNeeds;

        private Long peakMeetingRooms;

        private Boolean flexibleDates;

        private Boolean repeat;

        private Long attendeesPerDay;

        private String referenceNumber;

        private SpaceArea largestMeetingSpaceRequired;

        private String meetingRequestId;

        private EventFormatType formatType;

        private Long virtualAttendeesPerDay;

        private Double budget;

        private Double roomRateBudget;

        private Double foodBeverageBudget;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * Event details.
         */
        public Builder event(@Nullable Event12 event) {
            this.event = event;
            return this;
        }

        /**
         * Name of the event linked with the RFP.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * Location where the contract will be signed.
         */
        public Builder contractSignatureLocation(@Nullable String contractSignatureLocation) {
            this.contractSignatureLocation = contractSignatureLocation;
            return this;
        }

        /**
         * Destinations under consideration for the event.
         */
        public Builder destinationsUnderConsideration(@Nullable String destinationsUnderConsideration) {
            this.destinationsUnderConsideration = destinationsUnderConsideration;
            return this;
        }

        /**
         * True indicates that the event is associated with an external meeting request.
         */
        public Builder externalMeetingRequest(@Nullable Boolean externalMeetingRequest) {
            this.externalMeetingRequest = externalMeetingRequest;
            return this;
        }

        /**
         * Event type.
         */
        public Builder type(@Nullable EventType1 type) {
            this.type = type;
            return this;
        }

        /**
         * Space area divisons.
         */
        public Builder totalMeetingSpaceRequired(@Nullable SpaceArea totalMeetingSpaceRequired) {
            this.totalMeetingSpaceRequired = totalMeetingSpaceRequired;
            return this;
        }

        /**
         * Audio visual requirements.
         */
        public Builder audioVisualNeeds(@Nullable String audioVisualNeeds) {
            this.audioVisualNeeds = audioVisualNeeds;
            return this;
        }

        /**
         * Maximum number of meeting rooms required during the event.
         */
        public Builder peakMeetingRooms(@Nullable Long peakMeetingRooms) {
            this.peakMeetingRooms = peakMeetingRooms;
            return this;
        }

        /**
         * True indicates the event dates are flexible.
         */
        public Builder flexibleDates(@Nullable Boolean flexibleDates) {
            this.flexibleDates = flexibleDates;
            return this;
        }

        /**
         * True indicates event is a repeat occurrence.
         */
        public Builder repeat(@Nullable Boolean repeat) {
            this.repeat = repeat;
            return this;
        }

        /**
         * Number of in-person attendees per day.
         */
        public Builder attendeesPerDay(@Nullable Long attendeesPerDay) {
            this.attendeesPerDay = attendeesPerDay;
            return this;
        }

        /**
         * Reference number for the event.
         */
        public Builder referenceNumber(@Nullable String referenceNumber) {
            this.referenceNumber = referenceNumber;
            return this;
        }

        /**
         * Space area divisons.
         */
        public Builder largestMeetingSpaceRequired(@Nullable SpaceArea largestMeetingSpaceRequired) {
            this.largestMeetingSpaceRequired = largestMeetingSpaceRequired;
            return this;
        }

        /**
         * Unique identifier for meeting request associated with the event.
         */
        public Builder meetingRequestId(@Nullable String meetingRequestId) {
            this.meetingRequestId = meetingRequestId;
            return this;
        }

        /**
         * Event format type.
         */
        public Builder formatType(@Nullable EventFormatType formatType) {
            this.formatType = formatType;
            return this;
        }

        /**
         * Number of virtual attendees per day.
         */
        public Builder virtualAttendeesPerDay(@Nullable Long virtualAttendeesPerDay) {
            this.virtualAttendeesPerDay = virtualAttendeesPerDay;
            return this;
        }

        /**
         * Total budget amount.
         */
        public Builder budget(@Nullable Double budget) {
            this.budget = budget;
            return this;
        }

        /**
         * Budget for rooms rates.
         */
        public Builder roomRateBudget(@Nullable Double roomRateBudget) {
            this.roomRateBudget = roomRateBudget;
            return this;
        }

        /**
         * Budget for food and beverage.
         */
        public Builder foodBeverageBudget(@Nullable Double foodBeverageBudget) {
            this.foodBeverageBudget = foodBeverageBudget;
            return this;
        }

        public RfpEvent build() {
            return new RfpEvent(
                    event,
                    name,
                    contractSignatureLocation,
                    destinationsUnderConsideration,
                    externalMeetingRequest,
                    type,
                    totalMeetingSpaceRequired,
                    audioVisualNeeds,
                    peakMeetingRooms,
                    flexibleDates,
                    repeat,
                    attendeesPerDay,
                    referenceNumber,
                    largestMeetingSpaceRequired,
                    meetingRequestId,
                    formatType,
                    virtualAttendeesPerDay,
                    budget,
                    roomRateBudget,
                    foodBeverageBudget);
        }
    }
}
