/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 * RfpGuestRooms
 *
 * <p>Guest Room Requirements
 */
public class RfpGuestRooms {
    /**
     * Sum of the number of rooms required each night across all the nights for the event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("totalRooms")
    private Long totalRooms;

    /**
     * The number of rooms required during peak nights.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("peakRooms")
    private Long peakRooms;

    /**
     * Occupancies for every room type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("occupancies")
    private List<GuestRoomOccupancyPerRoomType> occupancies;

    /**
     * The ISO 8601 check-in date.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("checkInDate")
    private LocalDate checkInDate;

    /**
     * List of room blocks required.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("roomBlocks")
    private List<RoomBlock> roomBlocks;

    /**
     * Additional Info (if any).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("additionalInformation")
    private String additionalInformation;

    @JsonCreator
    public RfpGuestRooms(
            @JsonProperty("totalRooms") @Nullable Long totalRooms,
            @JsonProperty("peakRooms") @Nullable Long peakRooms,
            @JsonProperty("occupancies") @Nullable List<GuestRoomOccupancyPerRoomType> occupancies,
            @JsonProperty("checkInDate") @Nullable LocalDate checkInDate,
            @JsonProperty("roomBlocks") @Nullable List<RoomBlock> roomBlocks,
            @JsonProperty("additionalInformation") @Nullable String additionalInformation) {
        this.totalRooms = totalRooms;
        this.peakRooms = peakRooms;
        this.occupancies = occupancies;
        this.checkInDate = checkInDate;
        this.roomBlocks = roomBlocks;
        this.additionalInformation = additionalInformation;
    }

    public RfpGuestRooms() {
        this(null, null, null, null, null, null);
    }

    /**
     * Sum of the number of rooms required each night across all the nights for the event.
     */
    public Optional<Long> totalRooms() {
        return Optional.ofNullable(this.totalRooms);
    }

    /**
     * The number of rooms required during peak nights.
     */
    public Optional<Long> peakRooms() {
        return Optional.ofNullable(this.peakRooms);
    }

    /**
     * Occupancies for every room type.
     */
    public Optional<List<GuestRoomOccupancyPerRoomType>> occupancies() {
        return Optional.ofNullable(this.occupancies);
    }

    /**
     * The ISO 8601 check-in date.
     */
    public Optional<LocalDate> checkInDate() {
        return Optional.ofNullable(this.checkInDate);
    }

    /**
     * List of room blocks required.
     */
    public Optional<List<RoomBlock>> roomBlocks() {
        return Optional.ofNullable(this.roomBlocks);
    }

    /**
     * Additional Info (if any).
     */
    public Optional<String> additionalInformation() {
        return Optional.ofNullable(this.additionalInformation);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Sum of the number of rooms required each night across all the nights for the event.
     */
    public RfpGuestRooms withTotalRooms(@Nullable Long totalRooms) {
        this.totalRooms = totalRooms;
        return this;
    }

    /**
     * The number of rooms required during peak nights.
     */
    public RfpGuestRooms withPeakRooms(@Nullable Long peakRooms) {
        this.peakRooms = peakRooms;
        return this;
    }

    /**
     * Occupancies for every room type.
     */
    public RfpGuestRooms withOccupancies(@Nullable List<GuestRoomOccupancyPerRoomType> occupancies) {
        this.occupancies = occupancies;
        return this;
    }

    /**
     * The ISO 8601 check-in date.
     */
    public RfpGuestRooms withCheckInDate(@Nullable LocalDate checkInDate) {
        this.checkInDate = checkInDate;
        return this;
    }

    /**
     * List of room blocks required.
     */
    public RfpGuestRooms withRoomBlocks(@Nullable List<RoomBlock> roomBlocks) {
        this.roomBlocks = roomBlocks;
        return this;
    }

    /**
     * Additional Info (if any).
     */
    public RfpGuestRooms withAdditionalInformation(@Nullable String additionalInformation) {
        this.additionalInformation = additionalInformation;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RfpGuestRooms other = (RfpGuestRooms) o;
        return Utils.enhancedDeepEquals(this.totalRooms, other.totalRooms)
                && Utils.enhancedDeepEquals(this.peakRooms, other.peakRooms)
                && Utils.enhancedDeepEquals(this.occupancies, other.occupancies)
                && Utils.enhancedDeepEquals(this.checkInDate, other.checkInDate)
                && Utils.enhancedDeepEquals(this.roomBlocks, other.roomBlocks)
                && Utils.enhancedDeepEquals(this.additionalInformation, other.additionalInformation);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(totalRooms, peakRooms, occupancies, checkInDate, roomBlocks, additionalInformation);
    }

    @Override
    public String toString() {
        return Utils.toString(
                RfpGuestRooms.class,
                "totalRooms",
                totalRooms,
                "peakRooms",
                peakRooms,
                "occupancies",
                occupancies,
                "checkInDate",
                checkInDate,
                "roomBlocks",
                roomBlocks,
                "additionalInformation",
                additionalInformation);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private Long totalRooms;

        private Long peakRooms;

        private List<GuestRoomOccupancyPerRoomType> occupancies;

        private LocalDate checkInDate;

        private List<RoomBlock> roomBlocks;

        private String additionalInformation;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * Sum of the number of rooms required each night across all the nights for the event.
         */
        public Builder totalRooms(@Nullable Long totalRooms) {
            this.totalRooms = totalRooms;
            return this;
        }

        /**
         * The number of rooms required during peak nights.
         */
        public Builder peakRooms(@Nullable Long peakRooms) {
            this.peakRooms = peakRooms;
            return this;
        }

        /**
         * Occupancies for every room type.
         */
        public Builder occupancies(@Nullable List<GuestRoomOccupancyPerRoomType> occupancies) {
            this.occupancies = occupancies;
            return this;
        }

        /**
         * The ISO 8601 check-in date.
         */
        public Builder checkInDate(@Nullable LocalDate checkInDate) {
            this.checkInDate = checkInDate;
            return this;
        }

        /**
         * List of room blocks required.
         */
        public Builder roomBlocks(@Nullable List<RoomBlock> roomBlocks) {
            this.roomBlocks = roomBlocks;
            return this;
        }

        /**
         * Additional Info (if any).
         */
        public Builder additionalInformation(@Nullable String additionalInformation) {
            this.additionalInformation = additionalInformation;
            return this;
        }

        public RfpGuestRooms build() {
            return new RfpGuestRooms(
                    totalRooms, peakRooms, occupancies, checkInDate, roomBlocks, additionalInformation);
        }
    }
}
