/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SleepingRoomTypeJson
 * 
 * <p>Sleeping room type
 */
public enum SleepingRoomTypeJson {
    ANY("ANY"),
    SINGLE("SINGLE"),
    DOUBLE("DOUBLE"),
    SUITE("SUITE"),
    STAFF("STAFF");

    @JsonValue
    private final String value;

    SleepingRoomTypeJson(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SleepingRoomTypeJson> fromValue(String value) {
        for (SleepingRoomTypeJson o: SleepingRoomTypeJson.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

