/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.LazySingletonValue;
import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * Speaker
 *
 * <p>An event speaker.
 */
public class Speaker {
    /**
     * The event the speaker is linked to.
     */
    @JsonProperty("event")
    private SpeakerEvent event;

    /**
     * The speaker's first name.
     */
    @JsonProperty("firstName")
    private String firstName;

    /**
     * The speaker's last name.
     */
    @JsonProperty("lastName")
    private String lastName;

    /**
     * The unique code associated with the speaker in an event
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private String code;

    /**
     * The speaker's email address
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    private String email;

    /**
     * Used to denote what is traditionally a title of an individual. For example, Mr., Mrs., Dr., etc.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prefix")
    private String prefix;

    /**
     * The speaker's Designation
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("designation")
    private String designation;

    /**
     * The company to which the speaker is associated
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company")
    private String company;

    /**
     * The speaker's title
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private String title;

    /**
     * A defined speaker category.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("category")
    private CategoryIdNameJson category;

    /**
     * Collection of social media links for the contact.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("links")
    private ContactLinksJsonInput links;

    /**
     * Indicates if a given speaker should be displayed on Event Website
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("visibility")
    private Boolean visibility;

    /**
     * The speaker's biography
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("biography")
    private String biography;

    /**
     * The Internal Note of the speaker
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("internalNote")
    private String internalNote;

    /**
     * Indicates if a given speaker is a featured speaker
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("featured")
    private Boolean featured;

    /**
     * Returned when the `match` filter is applied. Indicates how relevant the `match` filter term is to
     * the search result. Larger numbers represent higher relevance with respect to other search results in
     * the request.
     *
     * <p>Null if no `match` filter is provided.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("relevance")
    private Double relevance;

    @JsonCreator
    public Speaker(
            @JsonProperty("event") @Nonnull SpeakerEvent event,
            @JsonProperty("firstName") @Nonnull String firstName,
            @JsonProperty("lastName") @Nonnull String lastName,
            @JsonProperty("code") @Nullable String code,
            @JsonProperty("email") @Nullable String email,
            @JsonProperty("prefix") @Nullable String prefix,
            @JsonProperty("designation") @Nullable String designation,
            @JsonProperty("company") @Nullable String company,
            @JsonProperty("title") @Nullable String title,
            @JsonProperty("category") @Nullable CategoryIdNameJson category,
            @JsonProperty("links") @Nullable ContactLinksJsonInput links,
            @JsonProperty("visibility") @Nullable Boolean visibility,
            @JsonProperty("biography") @Nullable String biography,
            @JsonProperty("internalNote") @Nullable String internalNote,
            @JsonProperty("featured") @Nullable Boolean featured,
            @JsonProperty("relevance") @Nullable Double relevance) {
        this.event = Optional.ofNullable(event).orElseThrow(() -> new IllegalArgumentException("event cannot be null"));
        this.firstName = Optional.ofNullable(firstName)
                .orElseThrow(() -> new IllegalArgumentException("firstName cannot be null"));
        this.lastName = Optional.ofNullable(lastName)
                .orElseThrow(() -> new IllegalArgumentException("lastName cannot be null"));
        this.code = code;
        this.email = email;
        this.prefix = prefix;
        this.designation = designation;
        this.company = company;
        this.title = title;
        this.category = category;
        this.links = links;
        this.visibility = Optional.ofNullable(visibility).orElse(Builder._SINGLETON_VALUE_Visibility.value());
        this.biography = biography;
        this.internalNote = internalNote;
        this.featured = Optional.ofNullable(featured).orElse(Builder._SINGLETON_VALUE_Featured.value());
        this.relevance = relevance;
    }

    public Speaker(@Nonnull SpeakerEvent event, @Nonnull String firstName, @Nonnull String lastName) {
        this(event, firstName, lastName, null, null, null, null, null, null, null, null, null, null, null, null, null);
    }

    /**
     * The event the speaker is linked to.
     */
    public SpeakerEvent event() {
        return this.event;
    }

    /**
     * The speaker's first name.
     */
    public String firstName() {
        return this.firstName;
    }

    /**
     * The speaker's last name.
     */
    public String lastName() {
        return this.lastName;
    }

    /**
     * The unique code associated with the speaker in an event
     */
    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    /**
     * The speaker's email address
     */
    public Optional<String> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * Used to denote what is traditionally a title of an individual. For example, Mr., Mrs., Dr., etc.
     */
    public Optional<String> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    /**
     * The speaker's Designation
     */
    public Optional<String> designation() {
        return Optional.ofNullable(this.designation);
    }

    /**
     * The company to which the speaker is associated
     */
    public Optional<String> company() {
        return Optional.ofNullable(this.company);
    }

    /**
     * The speaker's title
     */
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * A defined speaker category.
     */
    public Optional<CategoryIdNameJson> category() {
        return Optional.ofNullable(this.category);
    }

    /**
     * Collection of social media links for the contact.
     */
    public Optional<ContactLinksJsonInput> links() {
        return Optional.ofNullable(this.links);
    }

    /**
     * Indicates if a given speaker should be displayed on Event Website
     */
    public Optional<Boolean> visibility() {
        return Optional.ofNullable(this.visibility);
    }

    /**
     * The speaker's biography
     */
    public Optional<String> biography() {
        return Optional.ofNullable(this.biography);
    }

    /**
     * The Internal Note of the speaker
     */
    public Optional<String> internalNote() {
        return Optional.ofNullable(this.internalNote);
    }

    /**
     * Indicates if a given speaker is a featured speaker
     */
    public Optional<Boolean> featured() {
        return Optional.ofNullable(this.featured);
    }

    /**
     * Returned when the `match` filter is applied. Indicates how relevant the `match` filter term is to
     * the search result. Larger numbers represent higher relevance with respect to other search results in
     * the request.
     *
     * <p>Null if no `match` filter is provided.
     */
    public Optional<Double> relevance() {
        return Optional.ofNullable(this.relevance);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * The event the speaker is linked to.
     */
    public Speaker withEvent(@Nonnull SpeakerEvent event) {
        this.event = Utils.checkNotNull(event, "event");
        return this;
    }

    /**
     * The speaker's first name.
     */
    public Speaker withFirstName(@Nonnull String firstName) {
        this.firstName = Utils.checkNotNull(firstName, "firstName");
        return this;
    }

    /**
     * The speaker's last name.
     */
    public Speaker withLastName(@Nonnull String lastName) {
        this.lastName = Utils.checkNotNull(lastName, "lastName");
        return this;
    }

    /**
     * The unique code associated with the speaker in an event
     */
    public Speaker withCode(@Nullable String code) {
        this.code = code;
        return this;
    }

    /**
     * The speaker's email address
     */
    public Speaker withEmail(@Nullable String email) {
        this.email = email;
        return this;
    }

    /**
     * Used to denote what is traditionally a title of an individual. For example, Mr., Mrs., Dr., etc.
     */
    public Speaker withPrefix(@Nullable String prefix) {
        this.prefix = prefix;
        return this;
    }

    /**
     * The speaker's Designation
     */
    public Speaker withDesignation(@Nullable String designation) {
        this.designation = designation;
        return this;
    }

    /**
     * The company to which the speaker is associated
     */
    public Speaker withCompany(@Nullable String company) {
        this.company = company;
        return this;
    }

    /**
     * The speaker's title
     */
    public Speaker withTitle(@Nullable String title) {
        this.title = title;
        return this;
    }

    /**
     * A defined speaker category.
     */
    public Speaker withCategory(@Nullable CategoryIdNameJson category) {
        this.category = category;
        return this;
    }

    /**
     * Collection of social media links for the contact.
     */
    public Speaker withLinks(@Nullable ContactLinksJsonInput links) {
        this.links = links;
        return this;
    }

    /**
     * Indicates if a given speaker should be displayed on Event Website
     */
    public Speaker withVisibility(@Nullable Boolean visibility) {
        this.visibility = visibility;
        return this;
    }

    /**
     * The speaker's biography
     */
    public Speaker withBiography(@Nullable String biography) {
        this.biography = biography;
        return this;
    }

    /**
     * The Internal Note of the speaker
     */
    public Speaker withInternalNote(@Nullable String internalNote) {
        this.internalNote = internalNote;
        return this;
    }

    /**
     * Indicates if a given speaker is a featured speaker
     */
    public Speaker withFeatured(@Nullable Boolean featured) {
        this.featured = featured;
        return this;
    }

    /**
     * Returned when the `match` filter is applied. Indicates how relevant the `match` filter term is to
     * the search result. Larger numbers represent higher relevance with respect to other search results in
     * the request.
     *
     * <p>Null if no `match` filter is provided.
     */
    public Speaker withRelevance(@Nullable Double relevance) {
        this.relevance = relevance;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Speaker other = (Speaker) o;
        return Utils.enhancedDeepEquals(this.event, other.event)
                && Utils.enhancedDeepEquals(this.firstName, other.firstName)
                && Utils.enhancedDeepEquals(this.lastName, other.lastName)
                && Utils.enhancedDeepEquals(this.code, other.code)
                && Utils.enhancedDeepEquals(this.email, other.email)
                && Utils.enhancedDeepEquals(this.prefix, other.prefix)
                && Utils.enhancedDeepEquals(this.designation, other.designation)
                && Utils.enhancedDeepEquals(this.company, other.company)
                && Utils.enhancedDeepEquals(this.title, other.title)
                && Utils.enhancedDeepEquals(this.category, other.category)
                && Utils.enhancedDeepEquals(this.links, other.links)
                && Utils.enhancedDeepEquals(this.visibility, other.visibility)
                && Utils.enhancedDeepEquals(this.biography, other.biography)
                && Utils.enhancedDeepEquals(this.internalNote, other.internalNote)
                && Utils.enhancedDeepEquals(this.featured, other.featured)
                && Utils.enhancedDeepEquals(this.relevance, other.relevance);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(
                event,
                firstName,
                lastName,
                code,
                email,
                prefix,
                designation,
                company,
                title,
                category,
                links,
                visibility,
                biography,
                internalNote,
                featured,
                relevance);
    }

    @Override
    public String toString() {
        return Utils.toString(
                Speaker.class,
                "event",
                event,
                "firstName",
                firstName,
                "lastName",
                lastName,
                "code",
                code,
                "email",
                email,
                "prefix",
                prefix,
                "designation",
                designation,
                "company",
                company,
                "title",
                title,
                "category",
                category,
                "links",
                links,
                "visibility",
                visibility,
                "biography",
                biography,
                "internalNote",
                internalNote,
                "featured",
                featured,
                "relevance",
                relevance);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private SpeakerEvent event;

        private String firstName;

        private String lastName;

        private String code;

        private String email;

        private String prefix;

        private String designation;

        private String company;

        private String title;

        private CategoryIdNameJson category;

        private ContactLinksJsonInput links;

        private Boolean visibility;

        private String biography;

        private String internalNote;

        private Boolean featured;

        private Double relevance;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * The event the speaker is linked to.
         */
        public Builder event(@Nonnull SpeakerEvent event) {
            this.event = Utils.checkNotNull(event, "event");
            return this;
        }

        /**
         * The speaker's first name.
         */
        public Builder firstName(@Nonnull String firstName) {
            this.firstName = Utils.checkNotNull(firstName, "firstName");
            return this;
        }

        /**
         * The speaker's last name.
         */
        public Builder lastName(@Nonnull String lastName) {
            this.lastName = Utils.checkNotNull(lastName, "lastName");
            return this;
        }

        /**
         * The unique code associated with the speaker in an event
         */
        public Builder code(@Nullable String code) {
            this.code = code;
            return this;
        }

        /**
         * The speaker's email address
         */
        public Builder email(@Nullable String email) {
            this.email = email;
            return this;
        }

        /**
         * Used to denote what is traditionally a title of an individual. For example, Mr., Mrs., Dr., etc.
         */
        public Builder prefix(@Nullable String prefix) {
            this.prefix = prefix;
            return this;
        }

        /**
         * The speaker's Designation
         */
        public Builder designation(@Nullable String designation) {
            this.designation = designation;
            return this;
        }

        /**
         * The company to which the speaker is associated
         */
        public Builder company(@Nullable String company) {
            this.company = company;
            return this;
        }

        /**
         * The speaker's title
         */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /**
         * A defined speaker category.
         */
        public Builder category(@Nullable CategoryIdNameJson category) {
            this.category = category;
            return this;
        }

        /**
         * Collection of social media links for the contact.
         */
        public Builder links(@Nullable ContactLinksJsonInput links) {
            this.links = links;
            return this;
        }

        /**
         * Indicates if a given speaker should be displayed on Event Website
         */
        public Builder visibility(@Nullable Boolean visibility) {
            this.visibility = visibility;
            return this;
        }

        /**
         * The speaker's biography
         */
        public Builder biography(@Nullable String biography) {
            this.biography = biography;
            return this;
        }

        /**
         * The Internal Note of the speaker
         */
        public Builder internalNote(@Nullable String internalNote) {
            this.internalNote = internalNote;
            return this;
        }

        /**
         * Indicates if a given speaker is a featured speaker
         */
        public Builder featured(@Nullable Boolean featured) {
            this.featured = featured;
            return this;
        }

        /**
         * Returned when the `match` filter is applied. Indicates how relevant the `match` filter term is to
         * the search result. Larger numbers represent higher relevance with respect to other search results in
         * the request.
         *
         * <p>Null if no `match` filter is provided.
         */
        public Builder relevance(@Nullable Double relevance) {
            this.relevance = relevance;
            return this;
        }

        public Speaker build() {
            return new Speaker(
                    event,
                    firstName,
                    lastName,
                    code,
                    email,
                    prefix,
                    designation,
                    company,
                    title,
                    category,
                    links,
                    visibility,
                    biography,
                    internalNote,
                    featured,
                    relevance);
        }

        private static final LazySingletonValue<Boolean> _SINGLETON_VALUE_Visibility =
                new LazySingletonValue<>("visibility", "true", new TypeReference<Boolean>() {});

        private static final LazySingletonValue<Boolean> _SINGLETON_VALUE_Featured =
                new LazySingletonValue<>("featured", "false", new TypeReference<Boolean>() {});
    }
}
