/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

public class SpeakerFileFile {
    /**
     * A string that has to be a format matching the industry standard uuid
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    @JsonCreator
    public SpeakerFileFile(@JsonProperty("id") @Nullable String id) {
        this.id = id;
    }

    public SpeakerFileFile() {
        this(null);
    }

    /**
     * A string that has to be a format matching the industry standard uuid
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * A string that has to be a format matching the industry standard uuid
     */
    public SpeakerFileFile withId(@Nullable String id) {
        this.id = id;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SpeakerFileFile other = (SpeakerFileFile) o;
        return Utils.enhancedDeepEquals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(id);
    }

    @Override
    public String toString() {
        return Utils.toString(SpeakerFileFile.class, "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String id;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * A string that has to be a format matching the industry standard uuid
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public SpeakerFileFile build() {
            return new SpeakerFileFile(id);
        }
    }
}
