/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

/**
 * StandardSurveyJson
 * 
 * <p>A standard survey.
 */
public class StandardSurveyJson {
    /**
     * The ISO 8601 zoned date time when this record was created.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created")
    private OffsetDateTime created;

    /**
     * The identifier of the user that created this record.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdBy")
    private String createdBy;

    /**
     * The ISO 8601 zoned date time when this record was updated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastModified")
    private OffsetDateTime lastModified;

    /**
     * The identifier of the user that last updated this record.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastModifiedBy")
    private String lastModifiedBy;

    /**
     * Id of the survey or Id of the chapter in case of event survey
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    /**
     * Title of the survey or Title of the chapter in case of event survey
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private String title;

    /**
     * Survey Code or Chapter Code in case of event survey
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private String code;

    /**
     * Timezone of the survey
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timezone")
    private String timezone;

    /**
     * Author of the survey
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("author")
    private SurveyAuthorJson author;

    /**
     * Survey description
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;

    /**
     * The survey will be closed after this ISO 8601 formatted date and time.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("closeAfter")
    private OffsetDateTime closeAfter;

    /**
     * The count of responses.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("responseCount")
    private Long responseCount;

    /**
     * Survey Status
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private SurveyStatusJson status;

    /**
     * The survey will be archived after this ISO 8601 formatted date and time.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("archiveAfter")
    private OffsetDateTime archiveAfter;

    /**
     * Collection of survey custom fields.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customFields")
    private List<CustomFieldJson2> customFields;

    @JsonCreator
    public StandardSurveyJson(
            @JsonProperty("created") @Nullable OffsetDateTime created,
            @JsonProperty("createdBy") @Nullable String createdBy,
            @JsonProperty("lastModified") @Nullable OffsetDateTime lastModified,
            @JsonProperty("lastModifiedBy") @Nullable String lastModifiedBy,
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("title") @Nullable String title,
            @JsonProperty("code") @Nullable String code,
            @JsonProperty("timezone") @Nullable String timezone,
            @JsonProperty("author") @Nullable SurveyAuthorJson author,
            @JsonProperty("description") @Nullable String description,
            @JsonProperty("closeAfter") @Nullable OffsetDateTime closeAfter,
            @JsonProperty("responseCount") @Nullable Long responseCount,
            @JsonProperty("status") @Nullable SurveyStatusJson status,
            @JsonProperty("archiveAfter") @Nullable OffsetDateTime archiveAfter,
            @JsonProperty("customFields") @Nullable List<CustomFieldJson2> customFields) {
        this.created = created;
        this.createdBy = createdBy;
        this.lastModified = lastModified;
        this.lastModifiedBy = lastModifiedBy;
        this.id = id;
        this.title = title;
        this.code = code;
        this.timezone = timezone;
        this.author = author;
        this.description = description;
        this.closeAfter = closeAfter;
        this.responseCount = responseCount;
        this.status = status;
        this.archiveAfter = archiveAfter;
        this.customFields = customFields;
    }
    
    public StandardSurveyJson() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null);
    }

    /**
     * The ISO 8601 zoned date time when this record was created.
     */
    public Optional<OffsetDateTime> created() {
        return Optional.ofNullable(this.created);
    }

    /**
     * The identifier of the user that created this record.
     */
    public Optional<String> createdBy() {
        return Optional.ofNullable(this.createdBy);
    }

    /**
     * The ISO 8601 zoned date time when this record was updated.
     */
    public Optional<OffsetDateTime> lastModified() {
        return Optional.ofNullable(this.lastModified);
    }

    /**
     * The identifier of the user that last updated this record.
     */
    public Optional<String> lastModifiedBy() {
        return Optional.ofNullable(this.lastModifiedBy);
    }

    /**
     * Id of the survey or Id of the chapter in case of event survey
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Title of the survey or Title of the chapter in case of event survey
     */
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * Survey Code or Chapter Code in case of event survey
     */
    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    /**
     * Timezone of the survey
     */
    public Optional<String> timezone() {
        return Optional.ofNullable(this.timezone);
    }

    /**
     * Author of the survey
     */
    public Optional<SurveyAuthorJson> author() {
        return Optional.ofNullable(this.author);
    }

    /**
     * Survey description
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The survey will be closed after this ISO 8601 formatted date and time.
     */
    public Optional<OffsetDateTime> closeAfter() {
        return Optional.ofNullable(this.closeAfter);
    }

    /**
     * The count of responses.
     */
    public Optional<Long> responseCount() {
        return Optional.ofNullable(this.responseCount);
    }

    /**
     * Survey Status
     */
    public Optional<SurveyStatusJson> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * The survey will be archived after this ISO 8601 formatted date and time.
     */
    public Optional<OffsetDateTime> archiveAfter() {
        return Optional.ofNullable(this.archiveAfter);
    }

    /**
     * Collection of survey custom fields.
     */
    public Optional<List<CustomFieldJson2>> customFields() {
        return Optional.ofNullable(this.customFields);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ISO 8601 zoned date time when this record was created.
     */
    public StandardSurveyJson withCreated(@Nullable OffsetDateTime created) {
        this.created = created;
        return this;
    }


    /**
     * The identifier of the user that created this record.
     */
    public StandardSurveyJson withCreatedBy(@Nullable String createdBy) {
        this.createdBy = createdBy;
        return this;
    }


    /**
     * The ISO 8601 zoned date time when this record was updated.
     */
    public StandardSurveyJson withLastModified(@Nullable OffsetDateTime lastModified) {
        this.lastModified = lastModified;
        return this;
    }


    /**
     * The identifier of the user that last updated this record.
     */
    public StandardSurveyJson withLastModifiedBy(@Nullable String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }


    /**
     * Id of the survey or Id of the chapter in case of event survey
     */
    public StandardSurveyJson withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    /**
     * Title of the survey or Title of the chapter in case of event survey
     */
    public StandardSurveyJson withTitle(@Nullable String title) {
        this.title = title;
        return this;
    }


    /**
     * Survey Code or Chapter Code in case of event survey
     */
    public StandardSurveyJson withCode(@Nullable String code) {
        this.code = code;
        return this;
    }


    /**
     * Timezone of the survey
     */
    public StandardSurveyJson withTimezone(@Nullable String timezone) {
        this.timezone = timezone;
        return this;
    }


    /**
     * Author of the survey
     */
    public StandardSurveyJson withAuthor(@Nullable SurveyAuthorJson author) {
        this.author = author;
        return this;
    }


    /**
     * Survey description
     */
    public StandardSurveyJson withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    /**
     * The survey will be closed after this ISO 8601 formatted date and time.
     */
    public StandardSurveyJson withCloseAfter(@Nullable OffsetDateTime closeAfter) {
        this.closeAfter = closeAfter;
        return this;
    }


    /**
     * The count of responses.
     */
    public StandardSurveyJson withResponseCount(@Nullable Long responseCount) {
        this.responseCount = responseCount;
        return this;
    }


    /**
     * Survey Status
     */
    public StandardSurveyJson withStatus(@Nullable SurveyStatusJson status) {
        this.status = status;
        return this;
    }


    /**
     * The survey will be archived after this ISO 8601 formatted date and time.
     */
    public StandardSurveyJson withArchiveAfter(@Nullable OffsetDateTime archiveAfter) {
        this.archiveAfter = archiveAfter;
        return this;
    }


    /**
     * Collection of survey custom fields.
     */
    public StandardSurveyJson withCustomFields(@Nullable List<CustomFieldJson2> customFields) {
        this.customFields = customFields;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StandardSurveyJson other = (StandardSurveyJson) o;
        return 
            Utils.enhancedDeepEquals(this.created, other.created) &&
            Utils.enhancedDeepEquals(this.createdBy, other.createdBy) &&
            Utils.enhancedDeepEquals(this.lastModified, other.lastModified) &&
            Utils.enhancedDeepEquals(this.lastModifiedBy, other.lastModifiedBy) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.timezone, other.timezone) &&
            Utils.enhancedDeepEquals(this.author, other.author) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.closeAfter, other.closeAfter) &&
            Utils.enhancedDeepEquals(this.responseCount, other.responseCount) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.archiveAfter, other.archiveAfter) &&
            Utils.enhancedDeepEquals(this.customFields, other.customFields);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            created, createdBy, lastModified,
            lastModifiedBy, id, title,
            code, timezone, author,
            description, closeAfter, responseCount,
            status, archiveAfter, customFields);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StandardSurveyJson.class,
                "created", created,
                "createdBy", createdBy,
                "lastModified", lastModified,
                "lastModifiedBy", lastModifiedBy,
                "id", id,
                "title", title,
                "code", code,
                "timezone", timezone,
                "author", author,
                "description", description,
                "closeAfter", closeAfter,
                "responseCount", responseCount,
                "status", status,
                "archiveAfter", archiveAfter,
                "customFields", customFields);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private OffsetDateTime created;

        private String createdBy;

        private OffsetDateTime lastModified;

        private String lastModifiedBy;

        private String id;

        private String title;

        private String code;

        private String timezone;

        private SurveyAuthorJson author;

        private String description;

        private OffsetDateTime closeAfter;

        private Long responseCount;

        private SurveyStatusJson status;

        private OffsetDateTime archiveAfter;

        private List<CustomFieldJson2> customFields;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ISO 8601 zoned date time when this record was created.
         */
        public Builder created(@Nullable OffsetDateTime created) {
            this.created = created;
            return this;
        }

        /**
         * The identifier of the user that created this record.
         */
        public Builder createdBy(@Nullable String createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * The ISO 8601 zoned date time when this record was updated.
         */
        public Builder lastModified(@Nullable OffsetDateTime lastModified) {
            this.lastModified = lastModified;
            return this;
        }

        /**
         * The identifier of the user that last updated this record.
         */
        public Builder lastModifiedBy(@Nullable String lastModifiedBy) {
            this.lastModifiedBy = lastModifiedBy;
            return this;
        }

        /**
         * Id of the survey or Id of the chapter in case of event survey
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /**
         * Title of the survey or Title of the chapter in case of event survey
         */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /**
         * Survey Code or Chapter Code in case of event survey
         */
        public Builder code(@Nullable String code) {
            this.code = code;
            return this;
        }

        /**
         * Timezone of the survey
         */
        public Builder timezone(@Nullable String timezone) {
            this.timezone = timezone;
            return this;
        }

        /**
         * Author of the survey
         */
        public Builder author(@Nullable SurveyAuthorJson author) {
            this.author = author;
            return this;
        }

        /**
         * Survey description
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /**
         * The survey will be closed after this ISO 8601 formatted date and time.
         */
        public Builder closeAfter(@Nullable OffsetDateTime closeAfter) {
            this.closeAfter = closeAfter;
            return this;
        }

        /**
         * The count of responses.
         */
        public Builder responseCount(@Nullable Long responseCount) {
            this.responseCount = responseCount;
            return this;
        }

        /**
         * Survey Status
         */
        public Builder status(@Nullable SurveyStatusJson status) {
            this.status = status;
            return this;
        }

        /**
         * The survey will be archived after this ISO 8601 formatted date and time.
         */
        public Builder archiveAfter(@Nullable OffsetDateTime archiveAfter) {
            this.archiveAfter = archiveAfter;
            return this;
        }

        /**
         * Collection of survey custom fields.
         */
        public Builder customFields(@Nullable List<CustomFieldJson2> customFields) {
            this.customFields = customFields;
            return this;
        }

        public StandardSurveyJson build() {
            return new StandardSurveyJson(
                created, createdBy, lastModified,
                lastModifiedBy, id, title,
                code, timezone, author,
                description, closeAfter, responseCount,
                status, archiveAfter, customFields);
        }

    }
}
