/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * TableAssignmentJson
 *
 * <p>The assignment of an attendee to a seat on a table for a given event seating
 */
public class TableAssignmentJson {
    /**
     * An object that contains the associated seating ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a seating
     * object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("seating")
    private ExpandableSeatingJson seating;

    /**
     * An object that contains the associated table ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a table object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("table")
    private ExpandableTableJson table;

    /**
     * An object that contains the associated seat ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a seat object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("seat")
    private ExpandableSeatJson seat;

    /**
     * The attendee object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("attendee")
    private TableAssignmentJsonAttendee attendee;

    @JsonCreator
    public TableAssignmentJson(
            @JsonProperty("seating") @Nullable ExpandableSeatingJson seating,
            @JsonProperty("table") @Nullable ExpandableTableJson table,
            @JsonProperty("seat") @Nullable ExpandableSeatJson seat,
            @JsonProperty("attendee") @Nullable TableAssignmentJsonAttendee attendee) {
        this.seating = seating;
        this.table = table;
        this.seat = seat;
        this.attendee = attendee;
    }

    public TableAssignmentJson() {
        this(null, null, null, null);
    }

    /**
     * An object that contains the associated seating ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a seating
     * object.
     */
    public Optional<ExpandableSeatingJson> seating() {
        return Optional.ofNullable(this.seating);
    }

    /**
     * An object that contains the associated table ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a table object.
     */
    public Optional<ExpandableTableJson> table() {
        return Optional.ofNullable(this.table);
    }

    /**
     * An object that contains the associated seat ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a seat object.
     */
    public Optional<ExpandableSeatJson> seat() {
        return Optional.ofNullable(this.seat);
    }

    /**
     * The attendee object.
     */
    public Optional<TableAssignmentJsonAttendee> attendee() {
        return Optional.ofNullable(this.attendee);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * An object that contains the associated seating ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a seating
     * object.
     */
    public TableAssignmentJson withSeating(@Nullable ExpandableSeatingJson seating) {
        this.seating = seating;
        return this;
    }

    /**
     * An object that contains the associated table ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a table object.
     */
    public TableAssignmentJson withTable(@Nullable ExpandableTableJson table) {
        this.table = table;
        return this;
    }

    /**
     * An object that contains the associated seat ID.
     *
     * <p>This is an **expandable** object and if requested will contain all the properties of a seat object.
     */
    public TableAssignmentJson withSeat(@Nullable ExpandableSeatJson seat) {
        this.seat = seat;
        return this;
    }

    /**
     * The attendee object.
     */
    public TableAssignmentJson withAttendee(@Nullable TableAssignmentJsonAttendee attendee) {
        this.attendee = attendee;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TableAssignmentJson other = (TableAssignmentJson) o;
        return Utils.enhancedDeepEquals(this.seating, other.seating)
                && Utils.enhancedDeepEquals(this.table, other.table)
                && Utils.enhancedDeepEquals(this.seat, other.seat)
                && Utils.enhancedDeepEquals(this.attendee, other.attendee);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(seating, table, seat, attendee);
    }

    @Override
    public String toString() {
        return Utils.toString(
                TableAssignmentJson.class, "seating", seating, "table", table, "seat", seat, "attendee", attendee);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private ExpandableSeatingJson seating;

        private ExpandableTableJson table;

        private ExpandableSeatJson seat;

        private TableAssignmentJsonAttendee attendee;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * An object that contains the associated seating ID.
         *
         * <p>This is an **expandable** object and if requested will contain all the properties of a seating
         * object.
         */
        public Builder seating(@Nullable ExpandableSeatingJson seating) {
            this.seating = seating;
            return this;
        }

        /**
         * An object that contains the associated table ID.
         *
         * <p>This is an **expandable** object and if requested will contain all the properties of a table object.
         */
        public Builder table(@Nullable ExpandableTableJson table) {
            this.table = table;
            return this;
        }

        /**
         * An object that contains the associated seat ID.
         *
         * <p>This is an **expandable** object and if requested will contain all the properties of a seat object.
         */
        public Builder seat(@Nullable ExpandableSeatJson seat) {
            this.seat = seat;
            return this;
        }

        /**
         * The attendee object.
         */
        public Builder attendee(@Nullable TableAssignmentJsonAttendee attendee) {
            this.attendee = attendee;
            return this;
        }

        public TableAssignmentJson build() {
            return new TableAssignmentJson(seating, table, seat, attendee);
        }
    }
}
