/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * TableAssignmentJsonAttendee
 * 
 * <p>The attendee object.
 */
public class TableAssignmentJsonAttendee {
    /**
     * The unique ID of the attendee assigned.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    @JsonCreator
    public TableAssignmentJsonAttendee(
            @JsonProperty("id") @Nullable String id) {
        this.id = id;
    }
    
    public TableAssignmentJsonAttendee() {
        this(null);
    }

    /**
     * The unique ID of the attendee assigned.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique ID of the attendee assigned.
     */
    public TableAssignmentJsonAttendee withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TableAssignmentJsonAttendee other = (TableAssignmentJsonAttendee) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TableAssignmentJsonAttendee.class,
                "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The unique ID of the attendee assigned.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public TableAssignmentJsonAttendee build() {
            return new TableAssignmentJsonAttendee(
                id);
        }

    }
}
