/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * TransactionType
 *
 * <p>The proposal transaction type
 */
public enum TransactionType {
    AWARD("AWARD"),
    CANCEL("CANCEL"),
    COPY("COPY"),
    CREATE("CREATE"),
    DECLINE("DECLINE"),
    DELETE("DELETE"),
    EXPIRE("EXPIRE"),
    MODIFY("MODIFY"),
    OBFUSCATE("OBFUSCATE"),
    PUBLISH("PUBLISH"),
    PUBLISH_CANCEL("PUBLISH_CANCEL"),
    PUBLISH_REQUEST("PUBLISH_REQUEST"),
    REOPEN("REOPEN"),
    RESEND_EMAIL("RESEND_EMAIL"),
    SUBMIT("SUBMIT"),
    VALIDATE("VALIDATE"),
    WITHDRAW("WITHDRAW");

    @JsonValue
    private final String value;

    TransactionType(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static Optional<TransactionType> fromValue(String value) {
        for (TransactionType o : TransactionType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
