/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.components;

import com.cvent.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * Uuid
 *
 * <p>The reference to the related entity. Contains only the ID of the related entity.
 */
public class Uuid {
    /**
     * A string that has to be a format matching the industry standard uuid
     */
    @JsonProperty("id")
    private String id;

    @JsonCreator
    public Uuid(@JsonProperty("id") @Nonnull String id) {
        this.id = Optional.ofNullable(id).orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
    }

    /**
     * A string that has to be a format matching the industry standard uuid
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * A string that has to be a format matching the industry standard uuid
     */
    public Uuid withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Uuid other = (Uuid) o;
        return Utils.enhancedDeepEquals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(id);
    }

    @Override
    public String toString() {
        return Utils.toString(Uuid.class, "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String id;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * A string that has to be a format matching the industry standard uuid
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public Uuid build() {
            return new Uuid(id);
        }
    }
}
