/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type AnswerBudgetCustomFieldRequest = {
  /**
   * Unique ID of an event.
   */
  id: string;
  /**
   * Unique ID of a budget item.
   */
  budgetItemId: string;
  /**
   * Unique ID of the custom field.
   */
  customFieldId: string;
  /**
   * Custom field answer to be updated.
   */
  customField1: components.CustomField1Input;
};

/** @internal */
export type AnswerBudgetCustomFieldRequest$Outbound = {
  id: string;
  budgetItemId: string;
  customFieldId: string;
  "custom-field1": components.CustomField1Input$Outbound;
};

/** @internal */
export const AnswerBudgetCustomFieldRequest$outboundSchema: z.ZodType<
  AnswerBudgetCustomFieldRequest$Outbound,
  z.ZodTypeDef,
  AnswerBudgetCustomFieldRequest
> = z.object({
  id: z.string(),
  budgetItemId: z.string(),
  customFieldId: z.string(),
  customField1: components.CustomField1Input$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    customField1: "custom-field1",
  });
});

export function answerBudgetCustomFieldRequestToJSON(
  answerBudgetCustomFieldRequest: AnswerBudgetCustomFieldRequest,
): string {
  return JSON.stringify(
    AnswerBudgetCustomFieldRequest$outboundSchema.parse(
      answerBudgetCustomFieldRequest,
    ),
  );
}
