/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteProgramItemRequest = {
  /**
   * Unique ID of a session program item.
   */
  programItemId: string;
};

/** @internal */
export type DeleteProgramItemRequest$Outbound = {
  programItemId: string;
};

/** @internal */
export const DeleteProgramItemRequest$outboundSchema: z.ZodType<
  DeleteProgramItemRequest$Outbound,
  z.ZodTypeDef,
  DeleteProgramItemRequest
> = z.object({
  programItemId: z.string(),
});

export function deleteProgramItemRequestToJSON(
  deleteProgramItemRequest: DeleteProgramItemRequest,
): string {
  return JSON.stringify(
    DeleteProgramItemRequest$outboundSchema.parse(deleteProgramItemRequest),
  );
}
