/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteContactProfileImageRequest = {
  /**
   * ID of a contact.
   */
  id: string;
};

/** @internal */
export type DeleteContactProfileImageRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteContactProfileImageRequest$outboundSchema: z.ZodType<
  DeleteContactProfileImageRequest$Outbound,
  z.ZodTypeDef,
  DeleteContactProfileImageRequest
> = z.object({
  id: z.string(),
});

export function deleteContactProfileImageRequestToJSON(
  deleteContactProfileImageRequest: DeleteContactProfileImageRequest,
): string {
  return JSON.stringify(
    DeleteContactProfileImageRequest$outboundSchema.parse(
      deleteContactProfileImageRequest,
    ),
  );
}
