/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DisassociateVenueImageRequest = {
  /**
   * Unique Cvent based identifier for a Venue.
   */
  venueId: string;
  /**
   * Unique identifier of a venue image.
   */
  venueImageId: string;
};

/** @internal */
export type DisassociateVenueImageRequest$Outbound = {
  venueId: string;
  venueImageId: string;
};

/** @internal */
export const DisassociateVenueImageRequest$outboundSchema: z.ZodType<
  DisassociateVenueImageRequest$Outbound,
  z.ZodTypeDef,
  DisassociateVenueImageRequest
> = z.object({
  venueId: z.string(),
  venueImageId: z.string(),
});

export function disassociateVenueImageRequestToJSON(
  disassociateVenueImageRequest: DisassociateVenueImageRequest,
): string {
  return JSON.stringify(
    DisassociateVenueImageRequest$outboundSchema.parse(
      disassociateVenueImageRequest,
    ),
  );
}
