/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListRfpAgendaItemSchedulesRequest = {
  /**
   * The unique identifier of the RFP we are requesting
   */
  rfpId: string;
  /**
   * The maximum number of records to return per page.
   */
  limit?: number | undefined;
  /**
   * The continuation token returned from a previous class. This must be a valid UUID v4 if provided.
   *
   * @remarks
   * This will override any other pageable parameters provided.
   */
  token?: string | undefined;
};

export type ListRfpAgendaItemSchedulesResponse = {
  result: components.PaginatedRfpAgendaItemsSchedule;
};

/** @internal */
export type ListRfpAgendaItemSchedulesRequest$Outbound = {
  rfpId: string;
  limit: number;
  token?: string | undefined;
};

/** @internal */
export const ListRfpAgendaItemSchedulesRequest$outboundSchema: z.ZodType<
  ListRfpAgendaItemSchedulesRequest$Outbound,
  z.ZodTypeDef,
  ListRfpAgendaItemSchedulesRequest
> = z.object({
  rfpId: z.string(),
  limit: z.number().int().default(100),
  token: z.string().optional(),
});

export function listRfpAgendaItemSchedulesRequestToJSON(
  listRfpAgendaItemSchedulesRequest: ListRfpAgendaItemSchedulesRequest,
): string {
  return JSON.stringify(
    ListRfpAgendaItemSchedulesRequest$outboundSchema.parse(
      listRfpAgendaItemSchedulesRequest,
    ),
  );
}

/** @internal */
export const ListRfpAgendaItemSchedulesResponse$inboundSchema: z.ZodType<
  ListRfpAgendaItemSchedulesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.PaginatedRfpAgendaItemsSchedule$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listRfpAgendaItemSchedulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListRfpAgendaItemSchedulesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListRfpAgendaItemSchedulesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRfpAgendaItemSchedulesResponse' from JSON`,
  );
}
