/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PropertyApiGetPropertyRoomRequest = {
  /**
   * The ID of the property room.
   */
  roomId: string;
};

/** @internal */
export type PropertyApiGetPropertyRoomRequest$Outbound = {
  roomId: string;
};

/** @internal */
export const PropertyApiGetPropertyRoomRequest$outboundSchema: z.ZodType<
  PropertyApiGetPropertyRoomRequest$Outbound,
  z.ZodTypeDef,
  PropertyApiGetPropertyRoomRequest
> = z.object({
  roomId: z.string(),
});

export function propertyApiGetPropertyRoomRequestToJSON(
  propertyApiGetPropertyRoomRequest: PropertyApiGetPropertyRoomRequest,
): string {
  return JSON.stringify(
    PropertyApiGetPropertyRoomRequest$outboundSchema.parse(
      propertyApiGetPropertyRoomRequest,
    ),
  );
}
