/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type UpdateCustomFieldTranslationRequest = {
  /**
   * The unique identifier of a custom field.
   */
  customFieldId: string;
  /**
   * Translation details to be updated for the custom field.
   */
  translation1: components.Translation1;
};

/** @internal */
export type UpdateCustomFieldTranslationRequest$Outbound = {
  customFieldId: string;
  translation1: components.Translation1$Outbound;
};

/** @internal */
export const UpdateCustomFieldTranslationRequest$outboundSchema: z.ZodType<
  UpdateCustomFieldTranslationRequest$Outbound,
  z.ZodTypeDef,
  UpdateCustomFieldTranslationRequest
> = z.object({
  customFieldId: z.string(),
  translation1: components.Translation1$outboundSchema,
});

export function updateCustomFieldTranslationRequestToJSON(
  updateCustomFieldTranslationRequest: UpdateCustomFieldTranslationRequest,
): string {
  return JSON.stringify(
    UpdateCustomFieldTranslationRequest$outboundSchema.parse(
      updateCustomFieldTranslationRequest,
    ),
  );
}
