//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Models.Components;
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// The Badge Print Job that was created.
    /// </summary>
    public class BadgePrintJobCreatedInput
    {
        /// <summary>
        /// This is used to indicate the status of the badge print job.
        /// </summary>
        [JsonProperty("status")]
        public BadgePrintJobStatusJson? Status { get; set; }

        /// <summary>
        /// Reference to a Badge Print Pool.
        /// </summary>
        [JsonProperty("pool")]
        public BadgePrinterPoolReferenceJson Pool { get; set; } = default!;

        /// <summary>
        /// A unique id of the attendee for badge printing, which could be confirmation number or secured badge id depending on whether secured badge id is enabled.
        /// </summary>
        [JsonProperty("badgeId")]
        public string BadgeId { get; set; } = default!;
    }
}