//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Models.Components;
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Page of Badge Printer Pools.
    /// </summary>
    public class BadgePrinterPoolsPaginatedResponse
    {
        /// <summary>
        /// Represents pagination information for a collection of resources.
        /// </summary>
        [JsonProperty("paging")]
        public PagingJson? Paging { get; set; }

        /// <summary>
        /// Collection of badge printer pools.
        /// </summary>
        [JsonProperty("data")]
        public List<ExistingBadgePrinterPool>? Data { get; set; }
    }
}