//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Models.Components;
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CompositeValueJsonType
    {
        private CompositeValueJsonType(string value) { Value = value; }

        public string Value { get; private set; }

        public static CompositeValueJsonType ArrayOfMeetingRoomRequirementJson { get { return new CompositeValueJsonType("arrayOfMeetingRoomRequirementJson"); } }

        public static CompositeValueJsonType ArrayOfSleepingRoomRequirementJson { get { return new CompositeValueJsonType("arrayOfSleepingRoomRequirementJson"); } }

        public static CompositeValueJsonType ArrayOfBudgetEstimateJson { get { return new CompositeValueJsonType("arrayOfBudgetEstimateJson"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CompositeValueJsonType v) { return v.Value; }
        public static CompositeValueJsonType FromString(string v) {
            switch(v) {
                case "arrayOfMeetingRoomRequirementJson": return ArrayOfMeetingRoomRequirementJson;
                case "arrayOfSleepingRoomRequirementJson": return ArrayOfSleepingRoomRequirementJson;
                case "arrayOfBudgetEstimateJson": return ArrayOfBudgetEstimateJson;
                default: throw new ArgumentException("Invalid value for CompositeValueJsonType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CompositeValueJsonType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// A set of answers to complex questions, which is READ-ONLY. A complex question can be a Meeting Room requirement, Sleeping Room requirement, or Budget Estimate based on the question ID. The ID determines the type of requirement: Meeting Room requirement for **&quot;9a224e41-58d9-43a2-ae59-6d1aa16442ce&quot;**, Sleeping Room requirement for **&quot;cc63aa7c-0800-4fa5-a04b-073793e197f3&quot;**, or Budget Estimate for **&quot;1479fb2d-e94c-4bfb-a63f-4af808a22160&quot;**.
    /// </summary>
    [JsonConverter(typeof(CompositeValueJson.CompositeValueJsonConverter))]
    public class CompositeValueJson
    {
        public CompositeValueJson(CompositeValueJsonType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public List<MeetingRoomRequirementJson>? ArrayOfMeetingRoomRequirementJson { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<SleepingRoomRequirementJson>? ArrayOfSleepingRoomRequirementJson { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<BudgetEstimateJson>? ArrayOfBudgetEstimateJson { get; set; }

        public CompositeValueJsonType Type { get; set; }
        public static CompositeValueJson CreateArrayOfMeetingRoomRequirementJson(List<MeetingRoomRequirementJson> arrayOfMeetingRoomRequirementJSON)
        {
            CompositeValueJsonType typ = CompositeValueJsonType.ArrayOfMeetingRoomRequirementJson;

            CompositeValueJson res = new CompositeValueJson(typ);
            res.ArrayOfMeetingRoomRequirementJson = arrayOfMeetingRoomRequirementJSON;
            return res;
        }
        public static CompositeValueJson CreateArrayOfSleepingRoomRequirementJson(List<SleepingRoomRequirementJson> arrayOfSleepingRoomRequirementJSON)
        {
            CompositeValueJsonType typ = CompositeValueJsonType.ArrayOfSleepingRoomRequirementJson;

            CompositeValueJson res = new CompositeValueJson(typ);
            res.ArrayOfSleepingRoomRequirementJson = arrayOfSleepingRoomRequirementJSON;
            return res;
        }
        public static CompositeValueJson CreateArrayOfBudgetEstimateJson(List<BudgetEstimateJson> arrayOfBudgetEstimateJSON)
        {
            CompositeValueJsonType typ = CompositeValueJsonType.ArrayOfBudgetEstimateJson;

            CompositeValueJson res = new CompositeValueJson(typ);
            res.ArrayOfBudgetEstimateJson = arrayOfBudgetEstimateJSON;
            return res;
        }

        public class CompositeValueJsonConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CompositeValueJson);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CompositeValueJson(CompositeValueJsonType.ArrayOfMeetingRoomRequirementJson)
                    {
                        ArrayOfMeetingRoomRequirementJson = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<MeetingRoomRequirementJson>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<MeetingRoomRequirementJson>), new CompositeValueJson(CompositeValueJsonType.ArrayOfMeetingRoomRequirementJson), "ArrayOfMeetingRoomRequirementJson"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CompositeValueJson(CompositeValueJsonType.ArrayOfSleepingRoomRequirementJson)
                    {
                        ArrayOfSleepingRoomRequirementJson = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<SleepingRoomRequirementJson>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<SleepingRoomRequirementJson>), new CompositeValueJson(CompositeValueJsonType.ArrayOfSleepingRoomRequirementJson), "ArrayOfSleepingRoomRequirementJson"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CompositeValueJson(CompositeValueJsonType.ArrayOfBudgetEstimateJson)
                    {
                        ArrayOfBudgetEstimateJson = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<BudgetEstimateJson>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<BudgetEstimateJson>), new CompositeValueJson(CompositeValueJsonType.ArrayOfBudgetEstimateJson), "ArrayOfBudgetEstimateJson"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CompositeValueJson res = (CompositeValueJson)value;

                if (res.ArrayOfMeetingRoomRequirementJson != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfMeetingRoomRequirementJson));
                    return;
                }

                if (res.ArrayOfSleepingRoomRequirementJson != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfSleepingRoomRequirementJson));
                    return;
                }

                if (res.ArrayOfBudgetEstimateJson != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfBudgetEstimateJson));
                    return;
                }
            }

        }

    }
}