//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Event type.
    /// </summary>
    public enum EventTypeJson0
    {
        [JsonProperty("ANNIVERSARY_BIRTHDAY")] AnniversaryBirthday,
        [JsonProperty("BACHELOR_BACHELORETTE_PARTY")] BachelorBacheloretteParty,
        [JsonProperty("BAR_BAT_MITZVAH")] BarBatMitzvah,
        [JsonProperty("BUSINESS_MEETING")] BusinessMeeting,
        [JsonProperty("CONFERENCE_CONVENTION")] ConferenceConvention,
        [JsonProperty("CORPORATE_EVENT")] CorporateEvent,
        [JsonProperty("CUSTOMER_EVENT")] CustomerEvent,
        [JsonProperty("EDUCATIONAL_SEMINAR")] EducationalSeminar,
        [JsonProperty("FRATERNITY_SORORITY_GROUP")] FraternitySororityGroup,
        [JsonProperty("FUNDRAISER_CHARITY_EVENT")] FundraiserCharityEvent,
        [JsonProperty("RECEPTION_HOLIDAY_PARTY")] ReceptionHolidayParty,
        [JsonProperty("INCENTIVE_TRAVEL")] IncentiveTravel,
        [JsonProperty("REUNION")] Reunion,
        [JsonProperty("SHAREHOLDERS_MEETING")] ShareholdersMeeting,
        [JsonProperty("SPECIAL_EVENT")] SpecialEvent,
        [JsonProperty("SPORTS_EVENT")] SportsEvent,
        [JsonProperty("TEAM_BUILDING_EVENT")] TeamBuildingEvent,
        [JsonProperty("TOUR_GROUP_VACATION")] TourGroupVacation,
        [JsonProperty("TRADE_SHOW_CONSUMER_SHOW")] TradeShowConsumerShow,
        [JsonProperty("TRAINING")] Training,
        [JsonProperty("WEDDING")] Wedding,
        [JsonProperty("OTHER")] Other,
    }

    public static class EventTypeJson0Extension
    {
        public static string Value(this EventTypeJson0 value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static EventTypeJson0 ToEnum(this string value)
        {
            foreach (var field in typeof(EventTypeJson0).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is EventTypeJson0)
                    {
                        return (EventTypeJson0)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum EventTypeJson0");
        }
    }
}