//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Schema for address information.
    /// </summary>
    public class LeadAddressJson
    {
        /// <summary>
        /// The first line of an address.
        /// </summary>
        [JsonProperty("address1")]
        public string? Address1 { get; set; }

        /// <summary>
        /// The second line of an address.
        /// </summary>
        [JsonProperty("address2")]
        public string? Address2 { get; set; }

        /// <summary>
        /// The name of the city.
        /// </summary>
        [JsonProperty("city")]
        public string? City { get; set; }

        /// <summary>
        /// The name of the state/province/region of the address.
        /// </summary>
        [JsonProperty("region")]
        public string? Region { get; set; }

        /// <summary>
        /// The abbreviation of the state/province/region of the address.
        /// </summary>
        [JsonProperty("regionCode")]
        public string? RegionCode { get; set; }

        /// <summary>
        /// postal code (also known as zipcode) of the address.
        /// </summary>
        [JsonProperty("postalCode")]
        public string? PostalCode { get; set; }

        /// <summary>
        /// Name of the country for example, 'United States'
        /// </summary>
        [JsonProperty("country")]
        public string? Country { get; set; }

        /// <summary>
        /// ISO 3166 two-letter (alpha-2) country code.
        /// </summary>
        [JsonProperty("countryCode")]
        public string? CountryCode { get; set; }
    }
}