//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Models.Components;
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Details of organization which is hosting the event.
    /// </summary>
    public class RfpEventOrganizationJson
    {
        /// <summary>
        /// Organization details.
        /// </summary>
        [JsonProperty("organization")]
        public OrganizationJson? Organization { get; set; }

        /// <summary>
        /// True indicates organization profile has to be kept confidential.
        /// </summary>
        [JsonProperty("confidentialProfile")]
        public bool? ConfidentialProfile { get; set; }

        /// <summary>
        /// Industry.
        /// </summary>
        [JsonProperty("industry")]
        public IndustryJson0? Industry { get; set; }

        /// <summary>
        /// Name of the organization hosting the event.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Organization type.
        /// </summary>
        [JsonProperty("type")]
        public OrganizationTypeJson0 Type { get; set; } = default!;

        /// <summary>
        /// Address details.
        /// </summary>
        [JsonProperty("address")]
        public AddressJson0? Address { get; set; }

        /// <summary>
        /// Number of events per year.
        /// </summary>
        [JsonProperty("eventsPerYear")]
        public long? EventsPerYear { get; set; }
    }
}