//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The solution where the video exists. Attendee Hub and Events+ represent two different solutions where the video can be found.
    /// </summary>
    public enum SolutionJson
    {
        [JsonProperty("ATTENDEE_HUB")]
        AttendeeHub,
        [JsonProperty("EVENTS_PLUS")]
        EventsPlus,
    }

    public static class SolutionJsonExtension
    {
        public static string Value(this SolutionJson value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SolutionJson ToEnum(this string value)
        {
            foreach(var field in typeof(SolutionJson).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SolutionJson)
                    {
                        return (SolutionJson)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SolutionJson");
        }
    }

}