//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Models.Components;
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Paginated list of need dates for a venue.
    /// </summary>
    public class VenueNeedDatesPaginatedResponse
    {
        /// <summary>
        /// Represents pagination information for a collection of resources.
        /// </summary>
        [JsonProperty("paging")]
        public Paging Paging { get; set; } = default!;

        /// <summary>
        /// List of need date ranges for the venue. Each item represents a contiguous period when the venue is actively seeking event business.
        /// </summary>
        [JsonProperty("data")]
        public List<ExistingVenueNeedDate> Data { get; set; } = default!;
    }
}