//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Cvent.SDK.Models.Components
{
    using Cvent.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Link details for a webcast host.
    /// </summary>
    public class WebcastHostLinkJson
    {
        /// <summary>
        /// A url to the webcast.
        /// </summary>
        [JsonProperty("href")]
        public string? Href { get; set; }

        /// <summary>
        /// Access code of webcast link.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; }

        /// <summary>
        /// Host key for the webcast.
        /// </summary>
        [JsonProperty("key")]
        public string? Key { get; set; }
    }
}