/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations.async;

import static com.cvent.operations.Operations.AsyncRequestOperation;

import com.cvent.SDKConfiguration;
import com.cvent.models.operations.CreateAppointmentRequest;
import com.cvent.operations.CreateAppointment;
import com.cvent.utils.Headers;
import com.cvent.utils.Options;
import com.cvent.utils.RetryConfig;
import com.cvent.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;

public class CreateAppointmentRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private CreateAppointmentRequest request;
    private final Options.Builder optionsBuilder;

    public CreateAppointmentRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public CreateAppointmentRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public CreateAppointmentRequestBuilder request(@Nonnull CreateAppointmentRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private CreateAppointmentRequest _buildRequest() {
        return this.request;
    }

    public CreateAppointmentRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
     * Executes the request and returns the response.
     *
     * @return The response from the server.
     */
    public CompletableFuture<CreateAppointmentResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<CreateAppointmentRequest, CreateAppointmentResponse> operation =
                new CreateAppointment.Async(sdkConfiguration, options, sdkConfiguration.retryScheduler(), _headers);
        return operation.doRequest(this._buildRequest()).thenCompose(operation::handleResponse);
    }
}
