/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.cvent.models.operations.async;

import static com.cvent.operations.Operations.AsyncRequestOperation;
import static com.cvent.utils.reactive.ReactiveUtils.mapAsync;

import com.cvent.SDKConfiguration;
import com.cvent.models.operations.ListSpeakersPostFilterRequest;
import com.cvent.operations.ListSpeakersPostFilter;
import com.cvent.utils.Blob;
import com.cvent.utils.Headers;
import com.cvent.utils.Utils;
import com.cvent.utils.pagination.AsyncPaginator;
import com.cvent.utils.pagination.CursorTracker;
import jakarta.annotation.Nonnull;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Flow;
import org.reactivestreams.FlowAdapters;
import org.reactivestreams.Publisher;
import org.reactivestreams.Subscriber;

public class ListSpeakersPostFilterRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ListSpeakersPostFilterRequest request;

    public ListSpeakersPostFilterRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListSpeakersPostFilterRequestBuilder request(@Nonnull ListSpeakersPostFilterRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private ListSpeakersPostFilterRequest _buildRequest() {
        return this.request;
    }
    
    public ListSpeakersPostFilterRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<ListSpeakersPostFilterResponse> call() {
        AsyncRequestOperation<ListSpeakersPostFilterRequest, ListSpeakersPostFilterResponse> operation
              = new ListSpeakersPostFilter.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
    
    /**
     * Returns a {@link Publisher} that performs next page calls till no more pages
     * are returned.
     *
     * <p>The returned {@link Publisher} can be used with reactive frameworks:
     * <pre><code>
     * Publisher&lt;ListSpeakersPostFilterResponse&gt; publisher = builder.callAsPublisher();
     * publisher.subscribe(new Subscriber&lt;ListSpeakersPostFilterResponse&gt;() {
     *     // Handle onNext, onError, onComplete
     * });
     * </code></pre>
     *
     * @return A {@link Publisher} that emits pages asynchronously
     */
    public Publisher<ListSpeakersPostFilterResponse> callAsPublisher() {
        ListSpeakersPostFilterRequest request = this.request;
        AsyncRequestOperation<ListSpeakersPostFilterRequest, ListSpeakersPostFilterResponse> operation
              = new ListSpeakersPostFilter.Async(sdkConfiguration, _headers);

        Flow.Publisher<HttpResponse<Blob>> asyncPaginator = new AsyncPaginator<>(
            request,
            new CursorTracker<>("$.paging.nextToken", String.class),
            ListSpeakersPostFilterRequest::withToken,
            operation::doRequest);

        Flow.Publisher<ListSpeakersPostFilterResponse> flowPublisher = mapAsync(asyncPaginator, operation::handleResponse);

        // Convert Flow.Publisher to Reactive Streams Publisher at the last stage
        return FlowAdapters.toPublisher(flowPublisher);
    }
}
