name: Publish PUBLIC-JAVA
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Enable test mode (dry-run only)'
        type: boolean
        default: true
        required: false
jobs:
  publish:
    uses: ./.github/workflows/sdk-publish.yaml
    with:
      target: public-java
      test_mode: ${{ inputs.test_mode }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # GPG secrets used by the publishing plugin for signing JAR files before publishing to Maven Central
      # These are required by Sonatype when publishing to Maven Central for artifact integrity verification.
      # The SRE team manages generating private/public key and distributing the public keys and setting them in GitHub Secrets
      java_gpg_passphrase: ${{ secrets.JAVA_GPG_PASSPHRASE }}  # Passphrase for the GPG private key
      java_gpg_secret_key: ${{ secrets.JAVA_GPG_SECRET_KEY }}  # Base64-encoded GPG private key for signing artifacts
      # OSSRH (OSS Repository Hosting) credentials for publishing to Maven Central
      # These authenticate with Sonatype's repository hosting service.
      # SRE team manages generating these credentials for Cvent SDKs and setting them in GitHub Secrets
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}  # Password for OSSRH/Sonatype account's active token for Cvent SDKs
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}  # Username for OSSRH/Sonatype account's active token for Cvent SDKs
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
