name: Publish PUBLIC-CSHARP
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Enable test mode (dry-run only)'
        type: boolean
        default: true
        required: false
      dotnet_version:
        description: "The version of dotnet to use when compiling the C# SDK"
        required: false
        type: string
        default: "8.x"

jobs:
  publish:
    uses: ./.github/workflows/sdk-publish.yaml
    with:
      target: public-csharp
      test_mode: ${{ github.event.inputs.test_mode }}
      dotnet_version: ${{ github.event.inputs.dotnet_version }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
